### ISSUE TITLE
New books won't sync through kobo sync

### ISSUE THREAD

**Issue by garrettjones331** [janeczku/calibre-web#2195] opened 2021-11-27 17:27 UTC
**Describe the bug/problem**
I haven't synced my kobo in a few months, however, when I went to sync it recently I get the "sync complete" message on my device, however, no new books are added.  I did delete and recreate my token and update it in the kobo configuration because I was debugging an issue an issue that ended up being unrelated, so I'm unsure if that could have anything to do with it.  As an additional test I removed a book from my current library on my kobo and went to re-sync and it **wasn't** added back

**Logfile**

```
[2021-11-27 12:09:34,532]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-11-27 12:09:34,532] DEBUG {cps.kobo:141} SyncToken: 
eyJ0eXAiOjEsInZlciI6bnVsbCwicHR5cCI6IlN5bmNUb2tlbiJ9.eyJJbnRlcm5hbFN5bmNUb2tlbiI6ImV5SjBlWEFpT2pFc0luWmxjaUk2SW5ZeUlpd2ljSFI1Y0NJNklsTjVibU5VYjJ0bGJpSjkuZXlKVGRXSnpZM0pwY0hScGIyNUZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTVRrd01DMHdNUzB3TVZRd01Eb3dNRG93TUZvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlN3aVJuVjBkWEpsVTNWaWMyTnlhWEIwYVc5dVJXNTBhWFJzWlcxbGJuUnpJanB1ZFd4c0xDSkZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU1DMHhNaTB5T1ZReU1EbzFPRG8xTTFvaUxDSkRhR1ZqYTFOMWJTSTZJbnRjSWxOcmFYQkRjbVZoZEdWa1hDSTZabUZzYzJVc1hDSkRjbVZoZEdWa1EyOTFiblJjSWpvd0xGd2lRM0psWVhSbFpGd2lPbHRkTEZ3aVUydHBjRTF2WkdsbWFXVmtYQ0k2Wm1Gc2MyVXNYQ0pOYjJScFptbGxaRndpT2x0ZGZTSXNJa2xrSWpvaU1EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd0luMHNJa1JsYkdWMFpXUkZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU1DMHhNaTB5T1ZReU1EbzFPRG8xTTFvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlN3aVVtVmhaR2x1WjFOMFlYUmxjeUk2ZXlKSmMwbHVhWFJwWVd3aU9tNTFiR3dzSWtkbGJtVnlZWFJwYjI1VWFXMWxJanB1ZFd4c0xDSlVhVzFsYzNSaGJYQWlPaUl5TURJd0xURXlMVEk1VkRJd09qVTRPalV6V2lJc0lrTm9aV05yVTNWdElqcHVkV3hzTENKSlpDSTZJakF3TURBd01EQXdMVEF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF3TURBd01EQXdNQ0o5TENKVVlXZHpJanA3SWtselNXNXBkR2xoYkNJNmJuVnNiQ3dpUjJWdVpYSmhkR2x2YmxScGJXVWlPbTUxYkd3c0lsUnBiV1Z6ZEdGdGNDSTZJakl3TWpBdE1USXRNamxVTWpBNk5UZzZOVE5hSWl3aVEyaGxZMnRUZFcwaU9tNTFiR3dzSWtsa0lqb2lNREF3TURBd01EQXRNREF3TUMwd01EQXdMVEF3TURBdE1EQXdNREF3TURBd01EQXdJbjBzSWtSbGJHVjBaV1JVWVdkeklqcDdJa2x6U1c1cGRHbGhiQ0k2Ym5Wc2JDd2lSMlZ1WlhKaGRHbHZibFJwYldVaU9tNTFiR3dzSWxScGJXVnpkR0Z0Y0NJNklqRTVNREF0TURFdE1ERlVNREE2TURBNk1EQmFJaXdpUTJobFkydFRkVzBpT201MWJHd3NJa2xrSWpvaU1EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd0luMHNJbEJ5YjJSMVkzUk5aWFJoWkdGMFlTSTZleUpKYzBsdWFYUnBZV3dpT201MWJHd3NJa2RsYm1WeVlYUnBiMjVVYVcxbElqcHVkV3hzTENKVWFXMWxjM1JoYlhBaU9pSXlNREl4TFRFeExUSXpWREF3T2pFM09qQTJXaUlzSWtOb1pXTnJVM1Z0SWpwdWRXeHNMQ0pKWkNJNkltWmpOV016Wm1JMkxUVXhPR1V0TkdVeFppMWhOemcwTFRaa056QTFZemN5TkRnd01TSjlmUSIsIklzQ29udGludWF0aW9uVG9rZW4iOmZhbHNlfQ,2021-07-03 14:20:57.049122,2021-07-03 14:21:20.852841,0001-01-01 00:00:00,2021-11-27 16:28:09.701760,0001-01-01 00:00:00
[2021-11-27 12:09:34,532] DEBUG {cps.kobo:143} Kobo: Received unproxied request, changed request port to external server port
[2021-11-27 12:09:34,557] DEBUG {cps.kobo:270} Remaining books to Sync: 0
[2021-11-27 12:09:34,827] DEBUG {cps.kobo:980} Unimplemented User Request received: http://192.168.1.75/kobo/[MyToken]/v1/user/wishlist
[2021-11-27 12:09:35,348] DEBUG {cps.kobo:995} Unimplemented Products Request received: http://192.168.1.75/kobo/[MyToken]/v1/products/books/series/ab83e0cd-5bf2-356e-90e2-afc3e74a7147
[2021-11-27 12:09:35,490] DEBUG {cps.kobo:995} Unimplemented Products Request received: http://192.168.1.75/kobo/[MyToken]/v1/products/books/series/f59de287-48a6-3d65-9043-9d9399c9b94d
[2021-11-27 12:09:35,689] DEBUG {cps.kobo:980} Unimplemented User Request received: http://192.168.1.75/kobo/[MyToken]/v1/user/recommendations
[2021-11-27 12:09:36,735] DEBUG {cps.kobo:980} Unimplemented User Request received: http://192.168.1.75/kobo/[MyToken]/v1/analytics/event
[2021-11-27 12:09:37,481] DEBUG {cps.kobo:995} Unimplemented Products Request received: http://192.168.1.75/kobo/[MyToken]/v1/products/468547f2-8f73-497a-bbb7-6593e961cbdf/nextread
[2021-11-27 12:09:37,682] DEBUG {cps.kobo:995} Unimplemented Products Request received: http://192.168.1.75/kobo/[MyToken]/v1/products/819bcdd2-9b51-462f-9ba9-226a7f498ea6/nextread
[2021-11-27 12:09:37,920] DEBUG {cps.kobo:995} Unimplemented Products Request received: http://192.168.1.75/kobo/[MyToken]/v1/products/502c3026-3886-45a8-86b3-67160e5b2622/nextread
```

**Expected behavior**
I have 14 new kepub files since my previous sync that should be added to my device after I sync

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux 5.10.28-Unraid SMP Wed Apr 7 08:23:18 PDT 2021 x86_64 x86_64
 - Python version: 3.8.10 
 - Calibre-Web version: 0.6.15 Beta - 7f9da94a18daadb9e6b4c9cede41667a1402b5af - 2021-11-27T17:43:51+01:00
 - Docker container: LinuxServer
 - Special Hardware: None
 - Browser: Firefox 94.0.1

**Additional context**
Syncing over LAN using LAN address.  As mentioned before I did delete and recreate my token and update it in the kobo configuration between the previous and current syncs.  

Here are my configuration settings within calibre-web
![image](https://user-images.githubusercontent.com/1960790/143691059-879aa488-13a1-49e6-ad77-520a2ae831bd.png)

**Comment by SSKWhiteShadow** [comment] 2021-11-29 08:40
Having the exact same issue here:
[2021-11-29 01:38:00,668]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-11-29 01:38:00,668] DEBUG {cps.kobo:141} SyncToken: eyJ0eXAiOjEsInZlciI6bnVsbCwicHR5cCI6IlN5bmNUb2tlbiJ9.eyJJbnRlcm5hbFN5bmNUb2tlbiI6ImV5SjBlWEFpT2pFc0luWmxjaUk2SW5ZeUlpd2ljSFI1Y0NJNklsTjVibU5VYjJ0bGJpSjkuZXlKVGRXSnpZM0pwY0hScGIyNUZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTVRrd01DMHdNUzB3TVZRd01Eb3dNRG93TUZvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlN3aVJuVjBkWEpsVTNWaWMyTnlhWEIwYVc5dVJXNTBhWFJzWlcxbGJuUnpJanB1ZFd4c0xDSkZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU1TMHdPUzB3TmxRd09Ub3hNam94T1ZvaUxDSkRhR1ZqYTFOMWJTSTZJbnRjSWxOcmFYQkRjbVZoZEdWa1hDSTZabUZzYzJVc1hDSkRjbVZoZEdWa1EyOTFiblJjSWpvd0xGd2lRM0psWVhSbFpGd2lPbHRkTEZ3aVUydHBjRTF2WkdsbWFXVmtYQ0k2Wm1Gc2MyVXNYQ0pOYjJScFptbGxaRndpT2x0ZGZTSXNJa2xrSWpvaU1EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd0luMHNJa1JsYkdWMFpXUkZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU1TMHdPUzB3TmxRd09Ub3hNam94T1ZvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlN3aVVtVmhaR2x1WjFOMFlYUmxjeUk2ZXlKSmMwbHVhWFJwWVd3aU9tNTFiR3dzSWtkbGJtVnlZWFJwYjI1VWFXMWxJanB1ZFd4c0xDSlVhVzFsYzNSaGJYQWlPaUl5TURJeExURXhMVEk1VkRBNE9qSTBPakV6V2lJc0lrTm9aV05yVTNWdElqcHVkV3hzTENKSlpDSTZJalk1TVRKaE5XRTRMV1V6WVRrdE5HSmhPUzA0TnpaaUxXWTRNV0kyWkRCbU5EQmlaaUo5TENKVVlXZHpJanA3SWtselNXNXBkR2xoYkNJNmJuVnNiQ3dpUjJWdVpYSmhkR2x2YmxScGJXVWlPbTUxYkd3c0lsUnBiV1Z6ZEdGdGNDSTZJakl3TWpFdE1Ea3RNRFpVTURrNk1USTZNVGxhSWl3aVEyaGxZMnRUZFcwaU9tNTFiR3dzSWtsa0lqb2lNREF3TURBd01EQXRNREF3TUMwd01EQXdMVEF3TURBdE1EQXdNREF3TURBd01EQXdJbjBzSWtSbGJHVjBaV1JVWVdkeklqcDdJa2x6U1c1cGRHbGhiQ0k2Ym5Wc2JDd2lSMlZ1WlhKaGRHbHZibFJwYldVaU9tNTFiR3dzSWxScGJXVnpkR0Z0Y0NJNklqRTVNREF0TURFdE1ERlVNREE2TURBNk1EQmFJaXdpUTJobFkydFRkVzBpT201MWJHd3NJa2xrSWpvaU1EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd0luMHNJbEJ5YjJSMVkzUk5aWFJoWkdGMFlTSTZleUpKYzBsdWFYUnBZV3dpT201MWJHd3NJa2RsYm1WeVlYUnBiMjVVYVcxbElqcHVkV3hzTENKVWFXMWxjM1JoYlhBaU9pSXlNREl4TFRBNUxUQTJWREE1T2pFeU9qRTVXaUlzSWtOb1pXTnJVM1Z0SWpwdWRXeHNMQ0pKWkNJNklqQXdNREF3TURBd0xUQXdNREF0TURBd01DMHdNREF3TFRBd01EQXdNREF3TURBd01DSjlmUSIsIklzQ29udGludWF0aW9uVG9rZW4iOmZhbHNlfQ,2021-11-29 07:17:57.623407,2021-11-29 07:17:57.623410,0001-01-01 00:00:00,2021-09-18 23:05:54.472597,2021-11-29 06:56:39.739506
[2021-11-29 01:38:00,669] DEBUG {cps.kobo:143} Kobo: Received unproxied request, changed request port to external server port
[2021-11-29 01:38:00,682] DEBUG {cps.kobo:270} Remaining books to Sync: 0

**Comment by OzzieIsaacs** [comment] 2021-11-29 09:03
I started working on it. I think I could reproduce it (but not sure yet why, be patient)

**Comment by SSKWhiteShadow** [comment] 2021-11-29 10:21
SO I really wanted things to sync. 

So deleted my kobo token.. and boy that went bad it landed me into issue where i needed to delete app.db. 

okay recovered from that, and re-enabled kobo sync. Went ahead and factory reset my kobo. Copied my new id and all that over and went to sync. I got all my books synced.. YAY..

So i went further and noticed some of my series info in wrong. updated all that went to update kobo... none of it updated.. not yay. So i guess bug in metadata updating as well.

Thought okay i will factory reset kobo and i will resync again.. 

Well i went to reync using the same user/kobo token and I get the error saying no books to sync again:
`[2021-11-29 03:15:00,208]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-11-29 03:15:00,208] DEBUG {cps.kobo:141} SyncToken: <text>
[2021-11-29 03:15:00,208] DEBUG {cps.kobo:143} Kobo: Received unproxied request, changed request port to external server port
[2021-11-29 03:15:00,224] DEBUG {cps.kobo:270} Remaining books to Sync: 0
`
So it seems it uses a old session info:
[2021-11-29 03:15:00,207] DEBUG {cps.ub:80} Found stored session: fe0dbe99f3ac845e049aa8344e9fb61a132ae780cd4e0d472359c222c9ab43b771cf4849e3b9c71e79fe9c5c7b3fd463389610903f8351ca6cd77888bf72e5b4

Then based on that being a good ysnc it doesnt check not to sure.. but really strange on a  freshly wiped kobo i get the same  error saying no books to sync

**Comment by SSKWhiteShadow** [comment] 2021-11-29 10:50
After deleting app.db again and setting everything up again.. I am able to sync again. havent tried add new items and sync yet.

**Comment by OzzieIsaacs** [comment] 2021-11-29 11:09
This is plausible. But at some time calibre-Web thinks the book is already synced, I have to figure out why

**Comment by serenewaffles** [comment] 2021-11-29 15:34
As far as deleting `app.db`, I have some insight.

When resetting the Kobo or otherwise non-standardly removing a book from the Kobo, Calibre-Web is not informed. Instead of deleting all of `app.db`, I have had success purging only the `kobo_synced_books` table. I am the only user of my instance, but I assume that you would only need to purge the entries relating to your user.

I am *extremely* reliably able to reproduce this state by the following actions:
1) Factory reset Kobo and log in as normal
2) Update api address to point to Calibre-Web
3) Repair Kobo reader database and sync
4) Repeat steps 1-3
5) Nothing syncs to the Kobo because Calibre-Web's `app.db` indicates that the books are already synced.

I don't believe this behavior is related to the OP issue of "books won't download for some reason", but I am not an expert.

**Comment by garrettjones331** [comment] 2021-11-29 19:17
Your edit is correct, they don’t show up on my kobo at all.

**Comment by OzzieIsaacs** [comment] 2021-12-01 19:34
Calibre-web has a table of books it thinks are synced, in some cases (aborted/incomplete syncs maybe) the table on calibre-web side is filled. Afterwards books are not synced anymore (because calibre-web thinks they are synced). 
Additional bug, archiving and unarchiving books didn't change the sync status on calibre-web side.
With the newest nightly build it should be possible to archive books and unarchive them right directly afterwards and then they get synced.
This is not a final solution, but better than "re-setting" the whole kobo sync config.
Currently there is no option to mass archive/unarchive books. I'm working on the issues

**Comment by OzzieIsaacs** [comment] 2021-12-01 19:37
One additional remark: Activating "proxy kobo requests" seems to make things worse

**Comment by garrettjones331** [comment] 2021-12-02 01:40
Is there a step I'm missing as part of this archive/unarchive process?  I go to the book, check archive, then go back to the main window, then go back to the book and uncheck archive.  When I go to sync my kobo, those books aren't being displayed.

**Comment by OzzieIsaacs** [comment] 2021-12-04 10:10
Normally just ticking the archive flag in calibre-web and right afterwards unticking it should cause the book to be synced. In the next kobo sync.

**Comment by OzzieIsaacs** [comment] 2021-12-04 20:48
I found a bug in multiuser applications the archive bit is checked globally. I'll fix this hopefully tomorrow

**Comment by garrettjones331** [comment] 2021-12-05 18:13
After updating to the latest nightly build (0.6.15 Beta - fd5ab0ef533891e3bfbf2fc4bd961d0259e95651 - 2021-12-05T18:01:56+01:00) Pre token change added books still aren't syncing.  I tried archiving/unarchiving on both the admin account and the account tied to the kobo.  I also tried archiving/unarchiving books added pre/post token change, and in either case, no books appear to be synced.

As another test, I removed one of the books that synced to the kobo post token change.  But going in and archiving/unarchiving fails to add it back when I perform another sync. 

`[2021-12-05 13:02:44,425]  INFO {cps.kobo:144} Kobo library sync request received.
[2021-12-05 13:02:44,425] DEBUG {cps.kobo:145} SyncToken: 2021-12-01 14:28:35.100614,2021-12-01 14:29:56.193027,0001-01-01 00:00:00,2021-12-02 11:36:14.822188,0001-01-01 00:00:00,eyJ0eXAiOjEsInZlciI6bnVsbCwicHR5cCI6IlN5bmNUb2tlbiJ9.eyJJbnRlcm5hbFN5bmNUb2tlbiI6ImV5SjBlWEFpT2pFc0luWmxjaUk2SW5ZeUlpd2ljSFI1Y0NJNklsTjVibU5VYjJ0bGJpSjkuZXlKVGRXSnpZM0pwY0hScGIyNUZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTVRrd01DMHdNUzB3TVZRd01Eb3dNRG93TUZvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlN3aVJuVjBkWEpsVTNWaWMyTnlhWEIwYVc5dVJXNTBhWFJzWlcxbGJuUnpJanB1ZFd4c0xDSkZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU1DMHhNaTB5T1ZReU1EbzFPRG8xTTFvaUxDSkRhR1ZqYTFOMWJTSTZJbnRjSWxOcmFYQkRjbVZoZEdWa1hDSTZabUZzYzJVc1hDSkRjbVZoZEdWa1EyOTFiblJjSWpvd0xGd2lRM0psWVhSbFpGd2lPbHRkTEZ3aVUydHBjRTF2WkdsbWFXVmtYQ0k2Wm1Gc2MyVXNYQ0pOYjJScFptbGxaRndpT2x0ZGZTSXNJa2xrSWpvaU1EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd0luMHNJa1JsYkdWMFpXUkZiblJwZEd4bGJXVnVkSE1pT25zaVNYTkpibWwwYVdGc0lqcHVkV3hzTENKSFpXNWxjbUYwYVc5dVZHbHRaU0k2Ym5Wc2JDd2lWR2x0WlhOMFlXMXdJam9pTWpBeU1DMHhNaTB5T1ZReU1EbzFPRG8xTTFvaUxDSkRhR1ZqYTFOMWJTSTZiblZzYkN3aVNXUWlPaUl3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREFpZlN3aVVtVmhaR2x1WjFOMFlYUmxjeUk2ZXlKSmMwbHVhWFJwWVd3aU9tNTFiR3dzSWtkbGJtVnlZWFJwYjI1VWFXMWxJanB1ZFd4c0xDSlVhVzFsYzNSaGJYQWlPaUl5TURJd0xURXlMVEk1VkRJd09qVTRPalV6V2lJc0lrTm9aV05yVTNWdElqcHVkV3hzTENKSlpDSTZJakF3TURBd01EQXdMVEF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF3TURBd01EQXdNQ0o5TENKVVlXZHpJanA3SWtselNXNXBkR2xoYkNJNmJuVnNiQ3dpUjJWdVpYSmhkR2x2YmxScGJXVWlPbTUxYkd3c0lsUnBiV1Z6ZEdGdGNDSTZJakl3TWpBdE1USXRNamxVTWpBNk5UZzZOVE5hSWl3aVEyaGxZMnRUZFcwaU9tNTFiR3dzSWtsa0lqb2lNREF3TURBd01EQXRNREF3TUMwd01EQXdMVEF3TURBdE1EQXdNREF3TURBd01EQXdJbjBzSWtSbGJHVjBaV1JVWVdkeklqcDdJa2x6U1c1cGRHbGhiQ0k2Ym5Wc2JDd2lSMlZ1WlhKaGRHbHZibFJwYldVaU9tNTFiR3dzSWxScGJXVnpkR0Z0Y0NJNklqRTVNREF0TURFdE1ERlVNREE2TURBNk1EQmFJaXdpUTJobFkydFRkVzBpT201MWJHd3NJa2xrSWpvaU1EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd0luMHNJbEJ5YjJSMVkzUk5aWFJoWkdGMFlTSTZleUpKYzBsdWFYUnBZV3dpT201MWJHd3NJa2RsYm1WeVlYUnBiMjVVYVcxbElqcHVkV3hzTENKVWFXMWxjM1JoYlhBaU9pSXlNREl4TFRFeExUSXpWREF3T2pFM09qQTJXaUlzSWtOb1pXTnJVM1Z0SWpwdWRXeHNMQ0pKWkNJNkltWmpOV016Wm1JMkxUVXhPR1V0TkdVeFppMWhOemcwTFRaa056QTFZemN5TkRnd01TSjlmUSIsIklzQ29udGludWF0aW9uVG9rZW4iOmZhbHNlfQ
[2021-12-05 13:02:44,425] DEBUG {cps.kobo:147} Kobo: Received unproxied request, changed request port to external server port
[2021-12-05 13:02:44,442] DEBUG {cps.kobo:212} Books to Sync: 0
[2021-12-05 13:02:44,456] DEBUG {cps.kobo:275} Remaining books to Sync: 0
[2021-12-05 13:02:44,462] DEBUG {cps.kobo:338} Kobo Sync Content: []`

**Comment by OzzieIsaacs** [comment] 2021-12-06 20:22
Please update to the newest nightly commit. There is now a button in the users own section (below the create sync token button) to force a full sync with your kobo reader. Please try this

**Comment by garrettjones331** [comment] 2021-12-06 21:07
Updated and used the button, received a notice "187 sync entries deleted". 
![image](https://user-images.githubusercontent.com/1960790/144921933-520ef79b-de3f-4a1f-b1c2-6a4ee5169da5.png)
However, upon syncing I'm still only getting the 171 books that were added using the old token.  I know the sync is actually doing something now because it hangs on "downloading books covers" for a while, and the book count temporarily jumps up to 342 (171*2).  

Some things I noticed that may help debug the issue further.  After clearing the sync entires and resyncing, the book I removed pre token change now appears on my kobo (yay!), however, the one I removed post token change does not appear on my device.

**Comment by shivalwolf** [comment] 2021-12-07 04:22
I have tried the same thing as above and getting a similar result. 
I setup a new instance of calibre-web but with my existing calibre database.
I factory reset my kobo and put the new instance IP and token into the config.

1st sync got 101 books.
2nd sync nothing now
used the force full sync button
It tried to update got 200 books on the kobo screen but then went back to 100 again afterwards.

One thing i did notice when doing the force full sync it displayed "2333 sync entries deleted"
As i think has been mentioned previously the table for kobo synced books fills up with all books not just the ones it has synced.
I tried fiddling with this table. 1st deleting all entries over 100 as it was the 1st 100 books that were synced. Then tried to sync. Sometimes it would get afew new books but most of the time it would jsut revert back to the previous number of books.
I also tried deleting just the 1st 100 entries from the table leaving only the ones it had not synced and this also showed nothing new to sync.

I was looking at the archive trick to try and archive all books. and then unarchive in batches of 100 between syncs but i ended up corrupting my app.db and having to reset the entire instance again.

I have been looking at the sync data code trying to work out why it fills the table with all the books even though its only appearing to sync to the max number defined in the code. I was pondering seeing if i could do a limit per sync to the defined value and then each sync it grabs 100 more. so while it cant seem to sync all at once just hitting sync several times shoudl get everything new in batches

**Comment by shivalwolf** [comment] 2021-12-07 05:16
I just noticed something in the debug logs. These are just thoughts hopefully it helps with finding the causes of the sync issues.

When you start a sync on the on a clean device and an empty kobosyncedbooks table
There are multiple get requests made to the sync API endpoint.

::ffff:10.10.10.17 - - [2021-12-07 15:57:53] "GET /kobo/(token)/v1/library/sync?Filter=ALL&DownloadUrlFilter=Generic,Android&PrioritizeRecentReads=true HTTP/1.1" 200 188278 4.713651

when looking at the result of that query it appears to be the 100 books that get synced.

However within seconds of the 1st GET request there are more every 5 seconds or so. for me totalling about 15 requests. 
Looking at the kobo function HandleSyncRequest the commands are rerun to populate the changed_enteries list and the calls to the   add_synced_books function. 

The kobo seems to only use the data out of the 1st GET request and the others all seem to be ignored. It almost looks like there is a race condition for every time a sync is done since multiple calls are made to the /sync endpoint. I want to try and block the additional calls to sync endpoint until the 1st one is complete.

**Comment by shivalwolf** [comment] 2021-12-07 08:33
I was able to get my kobo to get a full sync of all my ebooks (2333 in total)
I do not believe the code changes are the best solution but I think it shows that the issue may be related to the logic around the last_created and last_modified timestamps. but only after the 1st GET request for sync is made.

I commented out these 2 lines from the kobo.py script
    #sync_token.books_last_created = new_books_last_created
    #sync_token.books_last_modified = new_books_last_modified

I have a suspicion but have not been able to find the full cause that the values that are set in these 2 variables result in an issue that arrives after the 1st sync request where the kobo will get 100 books but no more even though it keeps asking for and receiving the rest of the data. I have a suspicion that the date values in these variables are causing the kobo to ignore all the following sync data after the 1st GET request. I have been trying to understand why this change appears to have resolved the syncing problem and i have a suspicion that when the value if put into the SyncToken for books_last_modified or books_last_created that since that value is possibly earlier in the 2nd and beyond GET requests the kobo ignores the new sync data. I have not been able to confirm this fully as i cant see the kobo side of the sync logs. 


My testing with the above commented out lines of code.

Steps Taken:
1. Kobo Reset to factory default
2. Force full kobo Sync to clear the kobosyncedbooks table.
3. Token added to kobo config
4. Sync was able to get ALL ebooks (2333) 
5. All covers were successfully fetched
6. 5 random ebooks downloaded to kobo as part of the sync process
7. Sync finished successfully.


Tests post full sync:
1. Setting book to read in calibre and sync = shows as read on kobo
2. Book marked as finished on kobo and sync = Book updated in Calibre as read    
3. Setting book to archived in calibre and sync = does not seem to make a change on the kobo
    3.1 Delete book from kobo, removing book from archive and sync. = book added back to kobo
5. Adding new book to calibre and sync = new book downloaded to kobo

**Comment by OzzieIsaacs** [comment] 2021-12-07 09:14
In which timezone are you living ?

**Comment by shivalwolf** [comment] 2021-12-07 10:06
> 

Australia +11

**Comment by aob1au** [comment] 2021-12-10 02:39
Exact same outcome for me after replicating ShivaWolf's steps, and coincidentally I am in the exact same timezone of GMT+11

**Comment by OzzieIsaacs** [comment] 2021-12-12 18:56
@SSKWhiteShadow:
```
So it seems it uses a old session info:
[2021-11-29 03:15:00,207] DEBUG {cps.ub:80} Found stored session: fe0dbe99f3ac845e049aa8344e9fb61a132ae780cd4e0d472359c222c9ab43b771cf4849e3b9c71e79fe9c5c7b3fd463389610903f8351ca6cd77888bf72e5b4
```
This message is just related to logging in to calibre-web. The session id is based on the browser and ip-adress used, so your kobo reader will always use this session. Because there is no routine on the kobo sync game to log out this will always show up after one at least partly successful sync.
-> I think your problem is solved?

@serenewaffles:
`I am extremely reliably able to reproduce this state by the following actions:`
That correct. As deleting the kobo will not delete the sync progress in calibre-web. Introducing the chunked sync it was needed to save progress of sync in a calibre-web database. Before the timestamp of the newest synced book was the indicator for where to continue, but there could be books with exactly the same timestamp, so it was not possible anymore to check where to continue. For this case the only help is the "force full sync button".
-> Your problem is/was a different one

**Comment by OzzieIsaacs** [comment] 2021-12-12 18:57
@shivalwolf 
I think I found it. All synced books showing up as "ChangedEntitlement" in the debug sync output, right? This is why they don't show up, they should be "NewEntitlement". 
Stupid error. I have to think on how to fix this

**Comment by OzzieIsaacs** [comment] 2021-12-12 19:35
So next try. Please update to the newest commit. After pressing force full sync it should sync all books

**Comment by garrettjones331** [comment] 2021-12-13 18:08
That seems to have fixed it on my end!

**Closed** 2021-12-13 18:08 UTC
Labels: bug
