### ISSUE TITLE
Suggestion: add toggable language button/filter

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#51] opened 2016-08-03 14:32 UTC
Would be nice to be able to enable/disable languages when you are browsing your collection. Perhaps a flag that gets greyed out/enabled when clicked located at the top bar?

**Comment by OzzieIsaacs** [comment] 2016-08-03 18:53
I've implemented something like this. Until this is merged by Janeczku you can try it from my repro fork:
https://github.com/OzzieIsaacs/calibre-web

Feedback is welcome.

**Comment by simkin** [comment] 2016-09-28 11:15
@OzzieIsaacs : When using your fork I get the following error when accessing the Languages section (500 error in browser):

> [2016-09-28 13:12:51,296] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1587} ERROR - Exception on /language [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/calibre-web/vendor/flask_login.py", line 717, in decorated_view
>     return func(*args, **kwargs)
>   File "/opt/calibre-web2/cps/web.py", line 590, in language_overview
>     cur_l = LC.parse(lang.lang_code)
>   File "/opt/calibre-web/vendor/babel/core.py", line 313, in parse
>     raise UnknownLocaleError(input_id)
> UnknownLocaleError: unknown locale u'lat'

**Comment by OzzieIsaacs** [comment] 2016-09-29 17:55
@simkin 
It seems that the problem is related to a latin book language, it try to fix this on this weekend

**Comment by OzzieIsaacs** [comment] 2016-10-01 09:13
It should now work basically (language code is shown instead of language name)

**Comment by simkin** [comment] 2016-10-03 12:21
@OzzieIsaacs , hereby confirmed, your fix works :) Thanks!

**Closed** 2017-01-09 10:55 UTC
Labels: enhancement
