### ISSUE TITLE
Nginx proxy_pass 308 Permanent Redirect?

### ISSUE THREAD

**Issue by petrukngantuk** [janeczku/calibre-web#1026] opened 2019-08-26 16:52 UTC
Hello all, after I can change the port to 8085,
new issue,
after I config it, with google drive enabled than click login, then input the username n password
FYI: I using Centos 7 and nginx proxy_pass :
```
server {
    listen      178.128.108.140:80;
    server_name calibre.skrinsutwitter.com ;
    root        /home/calibre/web/calibre.skrinsutwitter.com/public_html;
    index       index.php index.html index.htm;
    access_log  /var/log/nginx/domains/calibre.skrinsutwitter.com.log combined;
    access_log  /var/log/nginx/domains/calibre.skrinsutwitter.com.bytes bytes;
    error_log   /var/log/nginx/domains/calibre.skrinsutwitter.com.error.log error;

    location / {
        proxy_pass http://127.0.0.1:8085;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Script-Name /;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```

I given this error? I try using ssl or non-ssl it's same, why?

Flask stdout in terminal
```
::ffff:127.0.0.1 - - [2019-08-26 16:46:04] "GET / HTTP/1.0" 308 473 0.003364
::ffff:127.0.0.1 - - [2019-08-26 16:46:05] "GET / HTTP/1.0" 308 473 0.003282
::ffff:127.0.0.1 - - [2019-08-26 16:46:11] "GET / HTTP/1.0" 308 473 0.003637
::ffff:127.0.0.1 - - [2019-08-26 16:46:11] "GET / HTTP/1.0" 308 473 0.004124
::ffff:127.0.0.1 - - [2019-08-26 16:46:11] "GET / HTTP/1.0" 308 473 0.002939
::ffff:127.0.0.1 - - [2019-08-26 16:46:11] "GET / HTTP/1.0" 308 473 0.002927
::ffff:127.0.0.1 - - [2019-08-26 16:46:11] "GET / HTTP/1.0" 308 473 0.003470
::ffff:127.0.0.1 - - [2019-08-26 16:46:11] "GET / HTTP/1.0" 308 473 0.003046
::ffff:127.0.0.1 - - [2019-08-26 16:46:11] "GET / HTTP/1.0" 308 473 0.003379
::ffff:127.0.0.1 - - [2019-08-26 16:46:12] "GET / HTTP/1.0" 308 473 0.003297
::ffff:127.0.0.1 - - [2019-08-26 16:46:12] "GET / HTTP/1.0" 308 473 0.003716
::ffff:127.0.0.1 - - [2019-08-26 16:46:12] "GET / HTTP/1.0" 308 473 0.003053
::ffff:127.0.0.1 - - [2019-08-26 16:46:12] "GET / HTTP/1.0" 308 473 0.003123
::ffff:127.0.0.1 - - [2019-08-26 16:46:12] "GET / HTTP/1.0" 308 473 0.003004
::ffff:127.0.0.1 - - [2019-08-26 16:46:12] "GET / HTTP/1.0" 308 473 0.003198
::ffff:127.0.0.1 - - [2019-08-26 16:46:12] "GET / HTTP/1.0" 308 473 0.003467
::ffff:127.0.0.1 - - [2019-08-26 16:46:12] "GET / HTTP/1.0" 308 473 0.003030
::ffff:127.0.0.1 - - [2019-08-26 16:46:12] "GET / HTTP/1.0" 308 473 0.004139
::ffff:127.0.0.1 - - [2019-08-26 16:46:13] "GET / HTTP/1.0" 308 473 0.004236
::ffff:127.0.0.1 - - [2019-08-26 16:46:13] "GET / HTTP/1.0" 308 473 0.003459
::ffff:127.0.0.1 - - [2019-08-26 16:46:14] "GET / HTTP/1.0" 308 473 0.003131
::ffff:127.0.0.1 - - [2019-08-26 16:46:14] "GET / HTTP/1.0" 308 473 0.003021
```
nginx access log : 
```
NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:12 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:12 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:12 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:12 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:12 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:12 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:12 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:12 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:13 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:13 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:14 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
103.129.221.153 - - [26/Aug/2019:16:46:14 +0000] "GET / HTTP/1.1" 308 275 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
```
anyone can help?

**Comment by petrukngantuk** [comment] 2019-08-26 16:55
@OzzieIsaacs please help sir?

**Comment by OzzieIsaacs** [comment] 2019-08-26 17:26
Could you please try exactly the example given in the wiki. I'm pretty sure this one is working. (https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx) Afterwards we can try to figure out what exactly causes the problems.

**Comment by SubrataM3** [comment] 2019-09-08 20:27
> Could you please try exactly the example given in the wiki. I'm pretty sure this one is working. (https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx) Afterwards we can try to figure out what exactly causes the problems.

Hi, 
I have exactly the same issue, i have tried exactly same configuration as wiki.
I think the  issue is within the application itself, because on first run, i can access config page just fine, but problem starts just after saving the configuration and reloading page.
The page redirects infinite time.
If you need any more info, please let me know. I am using the docker image, so this issue should be easily reproducible.

**Comment by SubrataM3** [comment] 2019-09-09 05:40
Alright, I have found a solution, 

```
location /calibre/web/ {
	proxy_bind              $server_addr;
        proxy_pass              http://127.0.0.1:8083;
        proxy_set_header        Host            $http_host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Scheme        $scheme;
	proxy_set_header X-Script-Name /calibre/web/;
}
```
Removing trailing slash from `X-Script-Name` header , i.e 

> proxy_set_header X-Script-Name /calibre/web/;

fixes this issue. But still i think this is a little bug which should be fixed.

**Comment by OzzieIsaacs** [comment] 2019-09-11 17:18
I doublecheck it. It's working with the trailing slash on apache, only nginx is having a problem. I decided to add an additional hint for nginx config and not to change the code

**Closed by OzzieIsaacs** 2019-09-11 17:18 UTC
Labels: question
