### ISSUE TITLE
first call to 'webserver' calibre-web after x time is slow

### ISSUE THREAD

**Issue by aroundmyroom** [janeczku/calibre-web#676] opened 2018-10-13 07:29 UTC
When I try to access my calibre-web instance I notice that it takes several seconds (up to 20) before the server gives my books. After that the application is quick, but it seems there is a kind process putting the server into idle / sleep mode and when called it takes time to restart again. 

In what way can I try /see why the initial call to the server is so slow after a period not using it?

**Comment by OzzieIsaacs** [comment] 2018-10-13 09:40
I personally never had this effect. Is it possible that your hdd spins down, goes into a power safe mode and needs some time to wake up?

**Comment by aroundmyroom** [comment] 2018-10-13 10:01
that would not be the case, I run it in a VM where the machine is always busy ;)

**Comment by jim3ma** [comment] 2018-10-14 09:01
How many files in static folder ?
Calibre web will read all files, if there are many files in those folder, calibre web will start slowly.

**Comment by OzzieIsaacs** [comment] 2018-11-02 13:15
As @jim3ma pointed out a initial start of calibre-web might take some time, because a cache is build up to detect changed java script files (very useful for debugging and after updating). During this time calibre-web is not accessible, after this is finished the "INFO in server: Starting Gevent/Tornado server" is logged. I can not reproduce any other slow responses after some time, the problem seems to be only existing in your configuration/setup. I'm closing this issue as not producible.

**Closed by OzzieIsaacs** 2018-11-02 13:15 UTC
Labels: question
