### ISSUE TITLE
Cannot logout from a userid

### ISSUE THREAD

**Issue by haertig** [janeczku/calibre-web#555] opened 2018-07-25 18:51 UTC
Yesterday, I was able to logout of a userid I created in calibre-web.  I went back and forth between this username ("books") and "admin" many times.  No problems.  Today, I automatically login as "books" (that was expected), but if I hit the Logout button, it flashes briefly as the page reloads, and I am right back logged in as "books".  I was expecting a login dialog where I could choose "admin" instead.  I can no longer get out of the "books" userid.

Cleared browser cookies, cache, etc.  No change.  Verified using different browsers on different desktop computers.  They were all locked into the "books" userid.

Environment:

Linux.  Docker: containers running linuxserver/calibre-web and linuxserver/letsencrypt (which is used as an NGINX reverse proxy for calibre-web).  Brought containers down then back up (using docker-compose).  No change.

Things that I did (that I remember!) between yesterday when Logout was working correctly, and today when it is not:

Left the docker containers running, and cleanly rebooted the server (to verify that the containers started running again automatically after a reboot - they did).  Used docker-compose to bring everything down, then up again (but I had done that many times yesterday without adverse things happening).  There were not any new docker images downloaded during the down/up.

[code]
# docker-compose.yml
---
version: '3'

networks:
  frontend:
    driver: bridge

services:

  www:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/opt/docker/letsencrypt/config:/config
    environment:
      - EMAIL=myemail@myprovider.com
      - URL=my.personal.domain
      - VALIDATION=http
      - TZ=America/Denver
      - PUID=1001
      - PGID=999
    networks:
      - frontend
    depends_on:
      - books
    restart: always

  books:
    image: linuxserver/calibre-web
    container_name: calibre-web
    volumes:
      - /var/opt/docker/calibre-web/config:/config
      - /var/opt/calibre:/books
    environment:
      - PUID=1002
      - PGID=1001
    networks:
      - frontend
    restart: unless-stopped
[/code]

[code]
server {
	listen 80;
	server_name _;
	return 301 https://$host$request_uri;
}

# main server block
server {
	listen 443 ssl default_server;

        blah, blah, blah...

	location /calibre-web {
		proxy_pass              http://calibre-web:8083;
		proxy_set_header        Host            $http_host;
		proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header        X-Scheme        $scheme;
		proxy_set_header        X-Script-Name   /calibre-web;
	}

        blah, blah, blah...
}
[/code]

[code]
docker@linux-server-1 /var/opt/docker/letsencrypt/config/nginx/site-confs $ docker-compose -f /var/opt/docker/docker-compose.yml down
Stopping letsencrypt ... done
Stopping calibre-web ... done
Removing letsencrypt ... done
Removing calibre-web ... done
Removing network docker_frontend

docker@linux-server-1 /var/opt/docker/letsencrypt/config/nginx/site-confs $ docker-compose -f /var/opt/docker/docker-compose.yml up -d
Creating network "docker_frontend" with driver "bridge"
Creating calibre-web ... done
Creating letsencrypt ... done

docker@linux-server-1 /var/opt/docker/letsencrypt/config/nginx/site-confs $ docker logs calibre-web
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1002
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2018-07-25 18:37:53,974] INFO in web: Starting Calibre Web...
[2018-07-25 18:37:54,080] INFO in server: Starting Gevent server
::ffff:XXX:XX:X:X - - [2018-07-25 18:38:13] "GET /calibre-web/logout HTTP/1.0" 302 436 0.096115
::ffff:XXX:XX:X:X - - [2018-07-25 18:38:13] "GET /calibre-web/login HTTP/1.0" 302 421 0.090366
::ffff:XXX:XX:X:X - - [2018-07-25 18:38:14] "GET /calibre-web/ HTTP/1.0" 200 47951 0.339344
docker@linux-server-1 /var/opt/docker/letsencrypt/config/nginx/site-confs $ 
[/code]

**Comment by haertig** [comment] 2018-07-25 18:54
Those are not my highlights in bold large text above.  Apparently, so of the stuff I cut-n-pasted into the [ code ] blocks in the above post triggered formatting into large bold text.  Sorry about that...

**Comment by haertig** [comment] 2018-07-26 02:40
Successful workaround:

$ docker-compose -f /var/opt/docker/docker-compose.yml down
$ cd /var/app/docker/calibre-web/config
$ mv app.db OLD.app.db
$ docker-compose -f /var/opt/docker/docker-compose.yml up -d

So either some bug, or a calibre-web feature that I don't understand, was contained within calibre-web's database.  Wipe out the database and start from scratch "fixed" the issue.

**Comment by OzzieIsaacs** [comment] 2018-07-26 19:12
If it‘s working now, I‘m closing the issue

**Closed by OzzieIsaacs** 2018-07-26 19:12 UTC

**Comment by 917huB** [comment] 2019-08-09 18:36
I've actually just stumbled into this issue as well. Couple of differences, Im not using docker containers. I am running under Debian Stretch. Deleting the app.db and restarting didnt actually help my case. Also updated to latest Calibre and Calibre-web versions. I'm running behind a nginx reverse proxy which I think this is is related too. Its 100% reproducible for me so happy to help try and identify root cause.

**Comment by OzzieIsaacs** [comment] 2019-08-09 19:22
My experience is that this is caused by a caching issue from the Webbrowser. If you close the webbrowser and Open it afterwards you should be logged out.
