### ISSUE TITLE
OperationalError: no such table: custom_columns after submit of basic configuration

### ISSUE THREAD

**Issue by epicDove** [janeczku/calibre-web#1901] opened 2021-03-18 01:51 UTC
Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: custom_columns
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/admin.py", line 103, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 649, in basic_configuration
return _configuration_update_helper(configured=filepicker)
File "/app/calibre-web/cps/admin.py", line 915, in _configuration_update_helper
if not calibre_db.setup_db(config, ub.app_DB_path):
File "/app/calibre-web/cps/db.py", line 482, in setup_db
cc = conn.execute("SELECT id, datatype FROM custom_columns")
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1003, in execute
return self._execute_text(object_, multiparams, params)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
ret = self._execute_context(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: custom_columns
[SQL: SELECT id, datatype FROM custom_columns]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by OzzieIsaacs** [comment] 2021-03-21 13:27
Your calibre library seems to miss the "custom_columns". 
Please try to fix this in Calibre itself or generate a new library (metadata.db file).
A working metadata.db can be found here:
https://github.com/OzzieIsaacs/calibre-web-test/blob/master/test/Calibre_db/metadata.db

**Comment by epicDove** [comment] 2021-03-23 11:03
> Your calibre library seems to miss the "custom_columns".
> Please try to fix this in Calibre itself or generate a new library (metadata.db file).
> A working metadata.db can be found here:
> https://github.com/OzzieIsaacs/calibre-web-test/blob/master/test/Calibre_db/metadata.db

I replaced metadata.db with the working metadata.db, it still throws execeptions:

![image](https://user-images.githubusercontent.com/13879520/112136836-7b3ba480-8c0a-11eb-86e5-29ce411681f7.png)

**Comment by OzzieIsaacs** [comment] 2021-05-28 16:28
I can't reproduce this, without more details, I'll close the issue

**Closed by OzzieIsaacs** 2021-05-28 16:28 UTC
Labels: not reproducible, question
