### ISSUE TITLE
Add .CBR, .CBZ support for Comic Books

### ISSUE THREAD

**Issue by pyrostic** [janeczku/calibre-web#126] opened 2017-02-27 19:42 UTC
There are not many web readers for downloaded items available.  This would be great.  Also I'm not sure of your stance on Usenet, but you might consider Mylar and LazyLibrarian integration.

**Comment by OzzieIsaacs** [comment] 2017-03-06 18:40
duplicate of #63

**Closed** 2017-09-17 11:39 UTC
Labels: enhancement
