### ISSUE TITLE
Edit eBook Metadata -> Convert eBook format : Internal Server Error

### ISSUE THREAD

**Issue by Ribero** [janeczku/calibre-web#616] opened 2018-09-07 15:48 UTC
Calibre-Web is running from a Docker container (Technosfot2k) and is configured to use calibre-convert.

When trying to convert an eBook (epub -> mobi) the server immediately throw an "Internal Server Error". (same error of trying to convert to any other format).

**Note:** ebook-convert works perfectly when invoked from "_send to kindle_".

Log:
```
[2018-09-07 17:44:13,131] ERROR in app: Exception on /admin/book/convert/1309 [POST]                                                                                                   
Traceback (most recent call last):                                                                                                                                                     
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app                                                                                                         
    response = self.full_dispatch_request()                                                                                                                                            
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request                                                                                            
    rv = self.handle_user_exception(e)                                                                                                                                                 
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception                                                                                            
    reraise(exc_type, exc_value, tb)                                                                                                                                                   
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request                                                                                            
    rv = self.dispatch_request()                                                                                                                                                       
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request                                                                                                 
    return self.view_functions[rule.endpoint](**req.view_args)                                                                                                                         
  File "/calibre-web/app/cps/web.py", line 331, in decorated_view                                                                                                                      
    return login_required(func)(*args, **kwargs)                                                                                                                                       
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view                                                                                            
    return func(*args, **kwargs)                                                                                                                                                       
  File "/calibre-web/app/cps/web.py", line 482, in inner                                                                                                                               
    return f(*args, **kwargs)                                                                                                                                                          
  File "/calibre-web/app/cps/web.py", line 3734, in convert_bookformat                                                                                                                 
    book_format_to.upper(), current_user.nickname)                                                                                                                                     
  File "/calibre-web/app/cps/helper.py", line 79, in convert_book_format                                                                                                               
    settings['old_book_format'] = u'EPUB'                                                                                                                                              
UnboundLocalError: local variable 'settings' referenced before assignment                                                                                                              
::ffff:172.17.0.1 - - [2018-09-07 17:44:13] "POST /admin/book/convert/1309 HTTP/1.1" 500 412 0.117427    
```

**Comment by OzzieIsaacs** [comment] 2018-09-07 15:50
Duplicate of #609. Is already fixed

**Comment by Ribero** [comment] 2018-09-07 15:51
Ouupps, duplicate of #609

**Closed by OzzieIsaacs** 2018-09-07 15:50 UTC
