### ISSUE TITLE
Ability to hide certain formats

### ISSUE THREAD

**Issue by jeff47** [janeczku/calibre-web#2194] opened 2021-11-27 17:07 UTC
I would love to be able to hide certain formats.  I use calibre to "polish" my books, so I have a lot of "original_epub" files floating around.  Those are confusing to my family members who aren't so tech savvy.  It would be very useful if I could specify certain formats to hide from the calibre-web UI, either globally or on a user-specific basis.

**Comment by OzzieIsaacs** [comment] 2021-11-27 17:33
Duplicate of #2120.

I would have implemented it, but the first requester started conversation, which was not so nice. So I will do it later

**Comment by jeff47** [comment] 2021-11-27 17:34
Well I'm nice. :)

**Comment by jeff47** [comment] 2021-11-28 01:03
So an update: actually now that I see how to stop the creation of "original_epub" etc files in calibre, this request is a bit less pressing.  I'm not sure polishing in calibre is worth the time anyway.

**Comment by OzzieIsaacs** [comment] 2021-11-29 09:08
So I close this issue and we track the progress in issue 2120

**Closed by OzzieIsaacs** 2021-11-29 09:08 UTC
