### ISSUE TITLE
Convert only from edit metadata page not working

### ISSUE THREAD

**Issue by kianrafiee** [janeczku/calibre-web#609] opened 2018-09-06 02:14 UTC
First off, when I run a new setup of calibre-web, I always seem to get this HTTP error page when I add the initial setup info even though it starts to function fine afterwards:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

BUT, after going to the edit metadata page of a book and trying to convert from XXX to MOBI/AWZ/etc I get the same HTTP error page. It also does not do the convert, no Task is created, and the log file shows:

```
[2018-09-06 02:13:55,990] DEBUG in web: converting: book id: 47 from: EPUB to: MOBI                                                          
[2018-09-06 02:13:56,007] ERROR in app: Exception on /admin/book/convert/47 [POST]                                                           
Traceback (most recent call last):                                                                                                           
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app                                                               
    response = self.full_dispatch_request()                                                                                                  
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request                                                  
    rv = self.handle_user_exception(e)                                                                                                       
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception                                                  
    reraise(exc_type, exc_value, tb)                                                                                                         
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request                                                  
    rv = self.dispatch_request()                                                                                                             
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request                                                       
    return self.view_functions[rule.endpoint](**req.view_args)                                                                               
  File "/calibre-web/app/cps/web.py", line 331, in decorated_view                                                                            
    return login_required(func)(*args, **kwargs)                                                                                             
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view                                                  
    return func(*args, **kwargs)                                                                                                             
  File "/calibre-web/app/cps/web.py", line 482, in inner                                                                                     
    return f(*args, **kwargs)                                                                                                                
  File "/calibre-web/app/cps/web.py", line 3734, in convert_bookformat                                                                       
    book_format_to.upper(), current_user.nickname)                                                                                           
  File "/calibre-web/app/cps/helper.py", line 79, in convert_book_format                                                                     
    settings['old_book_format'] = u'EPUB'                                                                                                    
UnboundLocalError: local variable 'settings' referenced before assignment                                                                    
::ffff:172.17.0.1 - - [2018-09-06 02:13:56] "POST /admin/book/convert/47 HTTP/1.1" 500 412 0.029396  
```

**Comment by KaraokeStu** [comment] 2018-09-06 16:52
I'm getting the same issue and it looks like the variable "Settings" is being called a bit early in the page

**Comment by KaraokeStu** [comment] 2018-09-06 16:54
Looks to me like line 75 wants moving to before line 74 (the beginning of the "if" block)

**Comment by KaraokeStu** [comment] 2018-09-06 16:57
PS: I've made this edit locally and it works perfectly now 😃

**Comment by OzzieIsaacs** [comment] 2018-09-06 18:56
I'm sorry progrmmed totally rubish while refactoring the code. The fix from @KaraokeStu is only working for conversion from epub to mobi, but I fixed it now. I will open another issue for the login after first config problem

**Comment by kianrafiee** [comment] 2018-09-07 01:26
Wooh! Thanks guys.

**Comment by kianrafiee** [comment] 2018-09-07 01:47
Woops I spoke too soon. Looks like the conversions are resulting in ~10KB files with no data.

**Comment by kianrafiee** [comment] 2018-09-07 03:18
```
::ffff:192.168.1.49 - - [2018-09-07 03:18:10] "POST /admin/book/convert/64 HTTP/1.1" 302 706 0.017709                                        
::ffff:192.168.1.49 - - [2018-09-07 03:18:10] "GET /admin/book/64 HTTP/1.1" 200 19402 0.053448                                               
/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftohtml)               
/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftohtml)               
/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)        
/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)  
```

**Comment by OzzieIsaacs** [comment] 2018-09-07 08:01
Please check if the book can be converted from calibre without docker -> Problem of calibre or the corresponding book
If calibre is capable of converting the book -> please check if calibre-web without docker is capable of converting the book (or you could send me the book and I'll check myself)  -> docker problem, please report the problem at the corresponding github repro.

**Comment by kianrafiee** [comment] 2018-09-07 15:35
The problem seems to happen with every book I throw at it so I am of the suspicion this is not a book problem with a converter/calibre-web problem. Here is a log of an ePUB:

```
::ffff:192.168.1.49 - - [2018-09-07 15:33:24] "POST /admin/book/convert/37 HTTP/1.1" 302 898 0.166279                                        
::ffff:192.168.1.49 - - [2018-09-07 15:33:24] "GET /admin/book/37 HTTP/1.1" 200 18981 0.050287                                               
Traceback (most recent call last):                                                                                                           
  File "site.py", line 77, in main                                                                                                           
  File "site-packages/calibre/ebooks/conversion/cli.py", line 362, in main                                                                   
  File "site-packages/calibre/ebooks/conversion/cli.py", line 320, in create_option_parser                                                   
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 755, in __init__                                                           
ValueError: No plugin to handle output format: azw                                                                                           
[2018-09-07 15:33:28,003] INFO in worker: ebook converter failed with error while converting book                                            
[2018-09-07 15:33:28,027] ERROR in worker: Ebook converter failed with unknown error
```

Every EPUB I try gives this same error.

Every PDF I try gives the previous error I posted.

**Comment by OzzieIsaacs** [comment] 2018-09-07 18:12
I doublechecked it. Converting is working for me (outside docker).
`/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftohtml`
in the first error looks like some libraries are missing in the container.
`ValueError: No plugin to handle output format: azw`
In the second error message looks like calibre is missing something to handle azw files (calibre is e.g. not able to create cbr files from epub without plugin, and is creating an errormessage like this one). It think this is also a problem of the docker container. To figure out if I'm right you could do the following:
Please check if the book can be converted from calibre without docker -> Problem of calibre or the corresponding book
If calibre is capable of converting the book -> please check if calibre-web without docker is capable of converting the book (or you could send me the book and I'll check it for you, because I understand that you are using docker, because you don't want to install python, all the depencencies and so on) -> docker problem, please report the problem at the corresponding github repro.

**Comment by Ribero** [comment] 2018-09-07 21:57
Just to add my own experience : ePUB -> MOBI is working (I verified, the .MOBI file is readable).
I'm running calibre-web in Docker ([Technosoft2000](https://github.com/Technosoft2000/docker-calibre-web).

ePub -> AZW : Failed (`ERROR - Ebook converter failed with unknown error`)
ePub -> AZW3 : Ok (file size is coherent but I cannot test AZW3)
ePub -> PDF : Failed (`ERROR - Ebook converter failed with unknown error`)
AZW3 -> AZW : Failed (`ERROR - Ebook converter failed with unknown error`)

**Comment by kianrafiee** [comment] 2018-09-08 01:40
I can confirm the exact same. It seems EPUB to MOBI works for me as well. 

PDF to Anything fails. Along with everything @Ribero mentioned.

Thanks for testing @Ribero !

**Comment by OzzieIsaacs** [comment] 2018-09-08 04:44
PDFs are working for me.

**Comment by OzzieIsaacs** [comment] 2018-09-08 11:38
@technosoft2000 and @bodybybuddha could you please check if the docker container is capabale of converting pdfs to something else. The errors the users having reproted in this issue are not reproducible with a "normal" installation on Windows or Linux Mint, Ubuntu.

**Comment by Technosoft2000** [comment] 2018-09-08 15:42
@OzzieIsaacs 

Ok I'll check it tomorrow and give feedback :)

**Comment by kianrafiee** [comment] 2018-09-08 18:03
@Technosoft2000 I'm also going to post an issue here and on your repository regarding mounted folders. For some reason, my config and app folder have no contents even after calibre-web is setup and running. I am on a Synology using docker and have been pulling my hair out trying to get permissions correct using your guide and what not. Nothing seems to work and I'm not sure if this is just how its suppose to be.

**Comment by Technosoft2000** [comment] 2018-09-09 12:41
> PDF to Anything fails. Along with everything @Ribero mentioned.

I've detected that PDF conversion needs an additional package **libxcomposite** which I've added for local tests and afterwards I've tested the supported output formats which are described here:
https://manual.calibre-ebook.com/generated/en/ebook-convert.html

So AZW (file extension .azw) is not support as output format, but AZW3 (file extension .azw3).

Here my tests which I've done inside the docker container on CLI - **ebook-convert v3.30.0** :

Installed missing dependency: `apk add libxcomposite`

PDF => AZW3
-> sucessful: checked with Calibre Viewer 

PDF => DOCX
-> sucessful: checked with Microsoft Word

PDF => EPUB
-> sucessful: checked with Calibre Viewer 

PDF => FB2
-> sucessful: checked with Calibre Viewer 

PDF => HTML  /  EPUB => HTML
-> _ValueError: No plugin to handle output format: html_

PDF => HTMLZ
-> sucessful: checked with 7-Zip

PDF => LIT
-> sucessful: but not checked with a LIT Viewer

PDF => LRF
-> sucessful: checked with Calibre Viewer

PDF => MOBI
-> sucessful: checked with Calibre Viewer

PDF => OEB
-> sucessful: checked generated XHTML files with Google Chrome

PDF => PDB
-> sucessful: checked with Calibre Viewer 

EPUB => PDF 
-> sucessful: checked with Adobe Acrobat Reader

PDF => PML
-> _ValueError: No plugin to handle output format: pml_

PDF => RB
-> sucessful: but not checked with a RB Viewer

PDF => RTF
-> sucessful: checked with LibreOffice Writer 

PDF => SNB
-> sucessful: but not checked with a SNB Viewer

PDF => TCR
-> sucessful: but not checked with a TCR Viewer

PDF => TXT
-> checked with Notepad++

PDF => TXTZ
-> checked with 7-Zip

At the moment I build a new docker image with the added library and this image will also include the actual calibre **ebook-convert v3.31.0** where I want to test again the **PDF => HTML**  and **PDF => PML** which failed with **ebook-convert v3.30.0**.

@kianrafiee 
I've no issues on my Synology NAS with the config and app folder - do you create the conatiner via Synology Docker UI or via SSH on the shell? I'll need information about your 'docker create ...' statement and the log file 'docker log ...'; please create a new issue at [**Technosoft2000/docker-calibre-web**](https://github.com/Technosoft2000/docker-calibre-web)

**Comment by Technosoft2000** [comment] 2018-09-09 12:56
A cross check with the Calibre v3.31.0 Convert UI shows that the following target formats are supported:

- EPUB
- AZW3
- MOBI
- DOCX
- FB2
- HTMLZ
- LIT
- LRF
- PDB
- PDF
- PMLZ
- RB
- RTF
- SNB
- TCR
- TXT
- TXTZ
- ZIP

so **HTML** and **PML** are not supported anymore and instead **HTMLZ** and **PMLZ** should be used :)

**Comment by OzzieIsaacs** [comment] 2018-09-09 13:26
Currently Calibre-Web supports upload/conversion of the following formats:
'txt', 'pdf', 'epub', 'mobi', 'azw', 'azw3', 'cbr', 'cbz', 'cbt', 'djvu', 'prc', 'doc', 'docx', 'fb2'
HTML and PML are not among them, but: doc, cbr, cbz, cbt, djvu, prc. I‘ll change the allowed conversion formats

**Comment by Technosoft2000** [comment] 2018-09-09 13:28
I've detected the same mismatch regarding the supported/allowed formats - would be great to change to the formats which are allowed by ebook-convert, thanks.

**Comment by kianrafiee** [comment] 2018-09-09 16:16
@Technosoft2000 I used the docker app to create the container. I am not sure how to find the docker create statement used. Also, I have the log file but be aware this log is after a lot of trials of creating the container and using different PUID/PGID/User/Groups. Either way I will be posting an issue to your repository right now.

**Closed** 2018-09-09 16:17 UTC

**Comment by Ribero** [comment] 2018-09-09 17:08
just for the record : @kianrafiee I confirm that I'm also running docker on a Synology NAS without any issue.

**Comment by kianrafiee** [comment] 2018-09-09 17:13
@Ribero mind sharing with me your container setup and what user/group settings you used for container and folders?

**Comment by kianrafiee** [comment] 2018-09-09 18:48
Here is log:

::ffff:192.168.1.49 - - [2018-09-09 18:47:42] "POST /admin/book/convert/64 HTTP/1.1" 302 898 0.017439                                        
::ffff:192.168.1.49 - - [2018-09-09 18:47:42] "GET /admin/book/64 HTTP/1.1" 200 18593 0.051851                                               
::ffff:192.168.1.49 - - [2018-09-09 18:47:44] "GET /tasks HTTP/1.1" 200 10891 0.049928                                                       
::ffff:192.168.1.49 - - [2018-09-09 18:47:44] "GET /ajax/emailstat?sort=id&order=asc HTTP/1.1" 200 335 0.007634                              
/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftohtml)               
/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftohtml)               
/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)        
/opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66) 

Using latest image.

**Comment by OzzieIsaacs** [comment] 2018-09-09 18:55
You need to update the container. This is a pure docker issue. I don‘t know enough about the docker container stuff to help you. Please ask for help at the technosoft2000 Calibre web docker repro.

**Comment by kianrafiee** [comment] 2018-09-09 18:56
Ah ok.

**Comment by Technosoft2000** [comment] 2018-09-09 19:03
'... no version information ...' message is not an error message, it is only an info and this message is also shown when executing ebook-convert on the shell.

I've successful converted the Calibre Manual from EPUB -> PDF and then from PDF -> AZW3

I use the my Docker container v1.2.3 and the latest commit from today

**Comment by kianrafiee** [comment] 2018-09-09 19:05
@Technosoft2000 i will post additional q's in issue in your repo. I think i have proof of failure.
