### ISSUE TITLE
Error When Launching From Other Directory

### ISSUE THREAD

**Issue by BzowK** [janeczku/calibre-web#31] opened 2016-06-20 17:36 UTC
Good Afternoon - 

Thanks for your work on this - much better than the OEM server!  I have a potential issue or question, please.  I have multiple Calibre libraries - each dedicated to specific content (Magazines, Technical Reference, Books, etc.)  I found that I could run multiple instances of this script at once - each set to a different port, of course.  

When I attempt to launch them using a string like 
`python "C:\Program Files (x86)\Calibre Web Servers\Books\cps.py"`
, I get the error 
`python: can't open file 'C:\Program': [Errno 2] No such file or directory.`
However, changing to that directory then executing "python cps.py" works.

I'm not a Python expert so really don't know if this is a script or Python thing, but is there a way to launch without first changing directory?  Python is in my path.

Thanks!

**Comment by OzzieIsaacs** [comment] 2016-08-03 05:32
If I'm doing as described I'm getting a diffrent error. I get this error if I remove the "" from the command.
This is might be a duplicate of #45. I created a pull request to solve this one. Could you please check again?

**Closed** 2016-11-10 19:26 UTC
