### ISSUE TITLE
I want to konw the bookmark is there working when I close the website?

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#285] opened 2017-08-16 05:34 UTC
When I reed books ，not finsihed read the whole books。I click the bookmark buttons
![image](https://user-images.githubusercontent.com/28710685/29348560-2b41dc14-8287-11e7-84c3-d5922df46c71.png)
But I funod when I closed the website ,the bookmark is missing when i login in same users.
How can I place bookmark when i next time read the same books?

**Comment by jkrehm** [comment] 2017-08-16 14:15
Seems to be a duplicate of #266.

**Closed** 2017-09-18 02:29 UTC
