### ISSUE TITLE
Read books with guest account not working,I still not konw how to solve

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#349] opened 2017-09-27 02:08 UTC
I try to create  totally a new calibre-web application ,but old metadata.db ,new app.db.
When i click enable anonymous browsing and use inner guest account,i can't read books.
I find the problem but still no one pull requests. I still don't konw why?
just me happen this?

**Comment by jkrehm** [comment] 2017-09-27 03:22
This is a duplicate of #332

**Closed** 2017-09-28 19:56 UTC
