### ISSUE TITLE
Sending emails without email from failes - empty field is not checked

### ISSUE THREAD

**Issue by tamet83** [janeczku/calibre-web#1906] opened 2021-03-22 21:37 UTC
**Describe the bug/problem**
Hi, the mail service doesn’t work anymore.
I always receive the failure error, but the log give me a generic error.
I’ve checked the mail parameters and are all fine.
I have the latest update available in Nightly mode.

**To Reproduce**

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

```

Download Calibre-Web Log
[2021-03-22 21:09:52,760]  INFO {cps.server:272} webserver stop (restart=False)
[2021-03-22 21:10:01,941] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named betterreads.client
[2021-03-22 21:10:01,942] DEBUG {cps.services:37} Cannot import simpleldap, logging in with ldap will not work: No module named flask_simpleldap
[2021-03-22 21:10:01,942] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named jsonschema
[2021-03-22 21:10:02,070] DEBUG {cps.gdriveutils:69} Cannot import pydrive,httplib2, using gdrive will not work: No module named pydrive.auth
[2021-03-22 21:10:02,429] DEBUG {cps.comic:44} Cannot import comicapi, extracting comic metadata will not work: No module named comicapi.comicarchive
[2021-03-22 21:10:02,430] DEBUG {cps.comic:51} Cannot import rarfile, extracting cover files from rar files will not work: No module named rarfile
[2021-03-22 21:10:02,438] DEBUG {cps.uploader:63} Cannot import epub, extracting epub metadata will not work: No module named lxml
[2021-03-22 21:10:02,438] DEBUG {cps.uploader:70} Cannot import fb2, extracting fb2 metadata will not work: No module named lxml
[2021-03-22 21:10:02,444] DEBUG {cps.admin:74} Cannot import Flask-Dance, login with Oauth will not work: No module named flask_dance.consumer
[2021-03-22 21:10:02,447] DEBUG {cps.gdrive:46} Cannot import googleapiclient, using GDrive will not work: No module named googleapiclient.errors
[2021-03-22 21:10:02,457]  INFO {cps:101} Starting Calibre Web...
[2021-03-22 21:10:02,457]  INFO {cps:103} Python2 is EOL since end of 2019, this version of Calibre-Web supporting Python2 please consider upgrading to Python3
[2021-03-22 21:10:02,698]  INFO {cps.server:227} Starting Tornado server on :8083
[2021-03-22 21:10:09,389] DEBUG {cps.config_sql:326} _ConfigSQL updating storage
[2021-03-22 21:10:09,435] ERROR {cps.services.worker:61} _log() got an unexpected keyword argument 'stacklevel'
[2021-03-22 21:11:56,103] DEBUG {cps.config_sql:326} _ConfigSQL updating storage
[2021-03-22 21:12:01,941]  INFO {cps.admin:1288} Update status requested
[2021-03-22 21:12:02,128] DEBUG {cps.updater:541} Updater status: 
[2021-03-22 21:12:33,310] DEBUG {cps.config_sql:326} _ConfigSQL updating storage
[2021-03-22 21:12:33,622] ERROR {cps.services.worker:61} _log() got an unexpected keyword argument 'stacklevel'
```

**Screenshots**

![F1397A22-5C54-44A7-BE0A-2E2C1F33383C](https://user-images.githubusercontent.com/7949570/112059834-aebff580-8b5c-11eb-85a6-820ef77b30b5.jpeg)

**Environment (please complete the following information):**
 - OS: Proxmox
 - Python version: 2.7
 - Calibre-Web version: latest
 - Docker container: None

**Comment by tamet83** [comment] 2021-03-25 09:08
Any update about it?

**Comment by OzzieIsaacs** [comment] 2021-03-27 11:26
python2 is end of life since over one year, I will not fix any python 2 problems, please try to update to python 3:
https://forum.proxmox.com/threads/updating-python-from-2-x-to-3-x-in-proxmox-ve-6-1-7.69567/

**Comment by tamet83** [comment] 2021-03-27 15:47
Ok thanks for your advice.
I’ve update python version but the system still doesn’t send the email.
I have another installation of calibre web on another container and it works perfectly.
Is there a way to solve this issue?
The log doesn’t show any problem or error to show you

**Comment by OzzieIsaacs** [comment] 2021-03-27 16:04
This error should be gone:
`[2021-03-22 21:10:09,435] ERROR {cps.services.worker:61} _log() got an unexpected keyword argument 'stacklevel'`
Instead you might see a new one (if you have set the loglevel to `debug`). (Might be hard to see)
Does "latest" for the version mean you are using 0.6.11 or the newest nightly build (I added some more outputs one week or so ago)? 
Please try to update to the newest nightly version (admin -> basic configuration -> server config -> updater -> nightly).
The problem could be the same as here: #1905

**Comment by tamet83** [comment] 2021-03-27 16:11
The error is gone.
The log is in debug mode.
I’ve updated to the latest nightly version.
But still the system give me a failure when I try to send the test email.
I tried to use another mail account without any result.
Is there a way to reset some of this settings?
If not I’ll try to do a fresh install.

**Comment by tamet83** [comment] 2021-03-27 16:20
Actually I noticed that the sending goes in stale or something similar as you can see from the screenshot.

![F4F653C3-2A94-4A1B-88A2-37339592CBDA](https://user-images.githubusercontent.com/7949570/112727015-a848c980-8f20-11eb-99a1-b4778adf6fc3.png)

**Comment by OzzieIsaacs** [comment] 2021-03-27 16:22
There should be a lot of relevant out there:
[2021-03-27 17:19:43,226] DEBUG {cps.tasks.mail:47} send: ehlo [127.0.1.1]
[2021-03-27 17:19:43,293] DEBUG {cps.tasks.mail:73} ('reply:', "b'250-xxx.de Hello [127.0.1.1] [91.xx.xx.70]\\r\\n'")
[2021-03-27 17:19:43,293] DEBUG {cps.tasks.mail:73} ('reply:', "b'250-8BITMIME\\r\\n'")
[2021-03-27 17:19:43,293] DEBUG {cps.tasks.mail:73} ('reply:', "b'250-AUTH LOGIN PLAIN\\r\\n'")
[2021-03-27 17:19:43,293] DEBUG {cps.tasks.mail:73} ('reply:', "b'250 SIZE 141557760\\r\\n'")
[2021-03-27 17:19:43,294] DEBUG {cps.tasks.mail:73} ("reply: retcode (250); Msg: b'xxx.de Hello [127.0.1.1] [91.13.83.70]\\n8BITMIME\\nAUTH LOGIN PLAIN\\nSIZE 141557760'",)
[2021-03-27 17:19:43,294] DEBUG {cps.tasks.mail:47} send: AUTH PLAIN
[2021-03-27 17:19:43,349] DEBUG {cps.tasks.mail:73} ('reply:', "b'235 Authentication succeeded\\r\\n'")
[2021-03-27 17:19:43,349] DEBUG {cps.tasks.mail:73} ("reply: retcode (235); Msg: b'Authentication succeeded'",)
[2021-03-27 17:19:49,180] DEBUG {cps.tasks.mail:47} send: mail FROM:<xxxxx@xxx.de> size=30811
[2021-03-27 17:19:49,193] DEBUG {cps.tasks.mail:73} ('reply:', "b'250 Requested mail action okay, completed\\r\\n'")
[2021-03-27 17:19:49,193] DEBUG {cps.tasks.mail:73} ("reply: retcode (250); Msg: b'Requested mail action okay, completed'",)
[2021-03-27 17:19:49,193] DEBUG {cps.tasks.mail:47} send: rcpt TO:<xxxxx@xxx.de>
[2021-03-27 17:19:49,209] DEBUG {cps.tasks.mail:73} ('reply:', "b'250 OK\\r\\n'")
[2021-03-27 17:19:49,210] DEBUG {cps.tasks.mail:73} ("reply: retcode (250); Msg: b'OK'",)
[2021-03-27 17:19:49,210] DEBUG {cps.tasks.mail:47} send: data
[2021-03-27 17:19:49,219] DEBUG {cps.tasks.mail:73} ('reply:', "b'354 Start mail input; end with <CRLF>.<CRLF>\\r\\n'")
[2021-03-27 17:19:49,220] DEBUG {cps.tasks.mail:73} ("reply: retcode (354); Msg: b'Start mail input; end with <CRLF>.<CRLF>'",)
[2021-03-27 17:19:49,220] DEBUG {cps.tasks.mail:73} ('data:', (354, b'Start mail input; end with <CRLF>.<CRLF>'))
[2021-03-27 17:19:49,221] DEBUG {cps.tasks.mail:47} send: b'Content-Type: multipart/mixed; boundary="===============6433677374063613859=="\r\nMIME-Version: 1.0\r\nSubject: Send to Kindle\r\nMessage-Id: <161686198311.25681.429254712191602492.calibre-web@mint-desktop>\r\nDate: Sat, 27 Mar 2021 17:19:43 +0100\r\nFrom: xxxxx@xxx.de\r\nTo: xxxxx@xxx.de\r\n\r\n--='
[2021-03-27 17:19:49,267] DEBUG {cps.tasks.mail:73} ('reply:', "b'250 Requested mail action okay, completed: id=0MKrC4-1lQBfB0oLY-0007TK\\r\\n'")
[2021-03-27 17:19:49,267] DEBUG {cps.tasks.mail:73} ("reply: retcode (250); Msg: b'Requested mail action okay, completed: id=0MKrC4-1lQBfB0oLY-0007TK'",)
[2021-03-27 17:19:49,267] DEBUG {cps.tasks.mail:73} ('data:', (250, b'Requested mail action okay, completed: id=0MKrC4-1lQBfB0oLY-0007TK'))
[2021-03-27 17:19:50,284] DEBUG {cps.tasks.mail:47} send: quit
[2021-03-27 17:19:50,294] DEBUG {cps.tasks.mail:73} ('reply:', "b'221 xxx.de Service closing transmission channel\\r\\n'")
[2021-03-27 17:19:50,294] DEBUG {cps.tasks.mail:73} ("reply: retcode (221); Msg: bxxx.de Service closing transmission channel'",)

**Comment by OzzieIsaacs** [comment] 2021-03-27 16:23
All settings are stored in the app.db, you could do a backup of your current app.db, use the one which is working. Or just rename the app.db and start all over from the beginning

**Comment by tamet83** [comment] 2021-03-27 16:26
```

[2021-03-27 15:49:01,173] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'betterreads'
[2021-03-27 15:49:01,174] DEBUG {cps.services:37} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2021-03-27 15:49:01,175] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2021-03-27 15:49:01,306] DEBUG {cps.gdriveutils:69} Cannot import pydrive,httplib2, using gdrive will not work: No module named 'pydrive'
[2021-03-27 15:49:01,708] DEBUG {cps.comic:44} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2021-03-27 15:49:01,710] DEBUG {cps.comic:51} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2021-03-27 15:49:01,725] DEBUG {cps.uploader:63} Cannot import epub, extracting epub metadata will not work: No module named 'lxml'
[2021-03-27 15:49:01,726] DEBUG {cps.uploader:70} Cannot import fb2, extracting fb2 metadata will not work: No module named 'lxml'
[2021-03-27 15:49:01,743] DEBUG {cps.admin:74} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2021-03-27 15:49:01,747] DEBUG {cps.gdrive:46} Cannot import googleapiclient, using GDrive will not work: No module named 'googleapiclient'
[2021-03-27 15:49:01,770]  INFO {cps:101} Starting Calibre Web...
[2021-03-27 15:49:01,869]  INFO {cps.server:227} Starting Tornado server on :8083
[2021-03-27 15:54:06,112] DEBUG {cps.config_sql:326} _ConfigSQL updating storage
[2021-03-27 16:18:25,269] DEBUG {cps.config_sql:326} _ConfigSQL updating storage
[2021-03-27 16:18:30,569] DEBUG {cps.config_sql:326} _ConfigSQL updating storage
[2021-03-27 16:20:37,186]  INFO {cps.server:273} webserver stop (restart=True)
[2021-03-27 16:20:37,187]  INFO {cps.server:261} Performing restart of Calibre-Web
[2021-03-27 16:20:37,697] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'betterreads'
[2021-03-27 16:20:37,698] DEBUG {cps.services:37} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2021-03-27 16:20:37,698] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2021-03-27 16:20:37,772] DEBUG {cps.gdriveutils:69} Cannot import pydrive,httplib2, using gdrive will not work: No module named 'pydrive'
[2021-03-27 16:20:38,043] DEBUG {cps.comic:44} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2021-03-27 16:20:38,044] DEBUG {cps.comic:51} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2021-03-27 16:20:38,057] DEBUG {cps.uploader:63} Cannot import epub, extracting epub metadata will not work: No module named 'lxml'
[2021-03-27 16:20:38,057] DEBUG {cps.uploader:70} Cannot import fb2, extracting fb2 metadata will not work: No module named 'lxml'
[2021-03-27 16:20:38,073] DEBUG {cps.admin:74} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2021-03-27 16:20:38,077] DEBUG {cps.gdrive:46} Cannot import googleapiclient, using GDrive will not work: No module named 'googleapiclient'
[2021-03-27 16:20:38,098]  INFO {cps:101} Starting Calibre Web...
[2021-03-27 16:20:38,192]  INFO {cps.server:227} Starting Tornado server on :8083
[2021-03-27 16:21:53,712] DEBUG {cps.config_sql:326} _ConfigSQL updating storage
[2021-03-27 16:22:19,562]  INFO {cps.server:273} webserver stop (restart=True)
[2021-03-27 16:22:19,564]  INFO {cps.server:261} Performing restart of Calibre-Web
[2021-03-27 16:22:20,070] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'betterreads'
[2021-03-27 16:22:20,071] DEBUG {cps.services:37} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2021-03-27 16:22:20,071] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2021-03-27 16:22:20,143] DEBUG {cps.gdriveutils:69} Cannot import pydrive,httplib2, using gdrive will not work: No module named 'pydrive'
[2021-03-27 16:22:20,409] DEBUG {cps.comic:44} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2021-03-27 16:22:20,410] DEBUG {cps.comic:51} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2021-03-27 16:22:20,422] DEBUG {cps.uploader:63} Cannot import epub, extracting epub metadata will not work: No module named 'lxml'
[2021-03-27 16:22:20,423] DEBUG {cps.uploader:70} Cannot import fb2, extracting fb2 metadata will not work: No module named 'lxml'
[2021-03-27 16:22:20,438] DEBUG {cps.admin:74} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2021-03-27 16:22:20,442] DEBUG {cps.gdrive:46} Cannot import googleapiclient, using GDrive will not work: No module named 'googleapiclient'
[2021-03-27 16:22:20,463]  INFO {cps:101} Starting Calibre Web...
[2021-03-27 16:22:20,555]  INFO {cps.server:227} Starting Tornado server on :8083
[2021-03-27 16:22:27,756]  INFO {cps.admin:1287} Update status requested
[2021-03-27 16:22:27,928] DEBUG {cps.updater:541} Updater status: 
[2021-03-27 16:23:40,330] DEBUG {cps.config_sql:326} _ConfigSQL updating storage

```

**Comment by OzzieIsaacs** [comment] 2021-03-27 16:32
Okay, I see there is really nothing to see. 
If replacing app.db doesn't help I need the debug_package file (from admin section). Please send it to me via email (email address on my profile page)

**Comment by OzzieIsaacs** [comment] 2021-03-27 17:26
Please enter a email address in the from-email field (the senders email address ...@outlook.it would be the safest one. This is the address which is displayed in your email program.
![grafik](https://user-images.githubusercontent.com/6438895/112728902-c23ada00-8f29-11eb-88ec-3095bf5062db.png)
It should work then

**Comment by tamet83** [comment] 2021-03-27 17:39
Ok, I tried but it didn’t work.
It’s still in pending...

![860B034E-B691-44D4-B679-0B3BD7E57245](https://user-images.githubusercontent.com/7949570/112729285-af290980-8f2b-11eb-8ad9-c4fb78037159.jpeg)
![967C734F-14BC-4233-88EC-8ABAF782C2CF](https://user-images.githubusercontent.com/7949570/112729286-b0f2cd00-8f2b-11eb-94e5-4c5c5c789b22.jpeg)

**Comment by OzzieIsaacs** [comment] 2021-03-27 17:50
I can reproduce stucking email task without any logentry by creating a firewall rule blocking outbound traffic on port 587 .....

**Comment by OzzieIsaacs** [comment] 2021-03-27 17:57
If have to correct myself: I get an timeout entry after almost 5min (as expected):
`[2021-03-27 18:52:52,399] ERROR {cps.tasks.mail:184} [Errno 110] Connection timed out`
I reproduced your settings (your login name from the debug package) I'm missing of course the password, so I get:
`[2021-03-27 18:45:58,540] ERROR {cps.tasks.mail:173} (535, b'Authentication credentials invalid')`
My conclusion: It's working from my side (I'm using a different distro and python 3.8 instead of 3.7 but 3.6/3.7 worked all the time)

**Comment by tamet83** [comment] 2021-03-27 18:01
Ok I’ll try to remove the app.db and start again from scratch.
Thanks again for your help :)

**Comment by OzzieIsaacs** [comment] 2021-03-27 18:04
Okay, but from the debug files I can't see any setting which can create such behaviour. (I checked meanwhile changing language to italian, but this did also not change anything). Maybe there is something wrong in your installation (some files are not updated to the last version or some of the dependencies is corrupt (??). So a complete reinstallation (by just renaming the calibre-web folder) and download everything from the web could also help

**Comment by tamet83** [comment] 2021-03-27 18:16
Deleting the app.db and starting from scratch solved the problem.
Could be useful have the option to save all the users.
Now all my friends need to recreate their account

**Comment by tamet83** [comment] 2021-03-27 18:28
I have to correct myself, it just worked once with the test email.
But now it’s broken again.
I’m going to recreate the container, I think something else is broken.

**Comment by tamet83** [comment] 2021-03-27 19:59
Just for complete information I created again the whole container and reinstalled calibre-web.
I did a bunch of test to send the test email:
1) install the default stable version -> ko;
2) install the nightly updated version -> ko;
3) create a new email form a different provider -> ko;

What I don’t understand is why my other container, with my private calibre library works perfectly.
Without any kind of error inside log I can’t provide you any useful information.

**Comment by OzzieIsaacs** [comment] 2021-03-27 20:04
I also have no idea what could be the reason. I‘m doing automated tests after I did changes, several usecases in relation with emails are tested, and all these tests are „passed“
Are there any relevant differences in the libraries, Python version of the containers? Or are the docker version different?

**Comment by tamet83** [comment] 2021-03-27 20:06
i did not use a docker version.
I installed calibre web cloning your git and run the vendor requirements.

I’ll try to install the docker version as last resource

**Comment by OzzieIsaacs** [comment] 2021-03-27 20:08
Okay, I thought you‘ve been referring to docker, because you used the term container

**Comment by tamet83** [comment] 2021-03-27 20:09
No i have Proxmox and created a dedicated LXC container based on Debian 10

**Comment by tamet83** [comment] 2021-03-27 22:30
Hi, I solved installing the linuxserver versione inside Docker.
Anyway thank you again for your help

**Closed** 2021-03-28 05:26 UTC
Labels: bug
