### ISSUE TITLE
[Windows] Kobo Sync Failed | OSError: [Errno 22] Invalid Argument

### ISSUE THREAD

**Issue by ATD555** [janeczku/calibre-web#1509] opened 2020-06-26 16:37 UTC
**Describe the bug/problem**
Syncing with Kobo fails on second attempt. After changing "Kobo ereader.conf" to enable syncing with Calibre-Web, the sync is successful however any attempt after the initial one fails. I have tried reinstalling Calibre-Web but the issue persists.

**To Reproduce**
1. Change "api_endpoint" in "Kobo ereader.conf" to reflect the one created in Calibre-Web
2. Sync Kobo with Calibre-Web. This is successful
3. Attempt a second sync. This fails.

**Logfile**
```
[2020-06-26 10:20:11,575] ERROR {cps:1891} Exception on /kobo/1ef9bf8b7402dd4df2eb383177e35214/v1/library/sync [GET]
Traceback (most recent call last):
  File "C:\Calibre-Web\vendor\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Calibre-Web\vendor\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Calibre-Web\vendor\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Calibre-Web\vendor\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Calibre-Web\vendor\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Calibre-Web\vendor\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Calibre-Web\cps\kobo_auth.py", line 112, in inner
    return f(*args, **kwargs)
  File "C:\Calibre-Web\cps\web.py", line 253, in inner
    return f(*args, **kwargs)
  File "C:\Calibre-Web\cps\kobo.py", line 131, in HandleSyncRequest
    sync_token = SyncToken.SyncToken.from_headers(request.headers)
  File "C:\Calibre-Web\cps\services\SyncToken.py", line 133, in from_headers
    archive_last_modified = get_datetime_from_json(data_json, "archive_last_modified")
  File "C:\Calibre-Web\cps\services\SyncToken.py", line 47, in get_datetime_from_json
    return datetime.utcfromtimestamp(json_object[field_name])
OSError: [Errno 22] Invalid argument
```

**Expected behavior**
Expect Kobo sync to go through without error/failing

**Screenshots**

**Environment (please complete the following information):**

- OS: Windows 10 10.0.18362 AMD64 Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
- Python version: 3.8.3 (tags/v3.8.3:6f8c832, May 13, 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
- Calibre-Web version: 0.6.8 -2ad329e64c0cfa67adc4a9f594481379ab8bb3ac - 2020-06-02T22:12:36+02:00
- Docker container: None
- Special Hardware: None
- Browser: Brave

**Additional context**
Running on local network

**Comment by ATD555** [comment] 2020-07-02 16:12
The only way I can get the Kobo to sync properly after adding the API_Endpoint is by doing the following:
• on the Kobo, go to Settings
• go to Device Information
• Press Repair button beside Repa_ir your Kobo account_

**Comment by DruidGreeneyes** [comment] 2020-07-04 03:31
I get OverflowError running in the linuxserver/calibre-web container, but I suspect the root cause is the same. I monkey-patched it and added some logging and here's what I saw:

```[2020-07-03 22:19:15,698]  INFO {cps.kobo:905} Init
[2020-07-03 22:19:16,172]  INFO {cps.services.SyncToken:50} datetime field books_last_modified content: 1593825708.15931
[2020-07-03 22:19:16,173]  INFO {cps.services.SyncToken:50} datetime field books_last_created content: 1593824412.848718
[2020-07-03 22:19:16,173]  INFO {cps.services.SyncToken:50} datetime field archive_last_modified content: -62135596800.0
[2020-07-03 22:19:16,174]  INFO {cps.services.SyncToken:50} datetime field reading_state_last_modified content: 1593827168.417047
[2020-07-03 22:19:16,174]  INFO {cps.services.SyncToken:50} datetime field tags_last_modified content: -62135596800.0
```

`archive_last_modified` and `tags_last_modified` were *probably* coming through as null, as I'd just done a factory reset on my kobo, and getting set to a min value by default somewhere, but integer.min isn't a valid datetime, so we get the problems above.

My patch against `cps/services/SyncToken.py`:

```
30c30,32
< from .. import logger as log
---
> from .. import logger
>
> log = logger.create()
47,48c49,52
<         return datetime.utcfromtimestamp(json_object[field_name])
<     except KeyError:
---
>         field_content = json_object[field_name]
>         log.info("datetime field {} content: {}".format(field_name, field_content))
>         return datetime.utcfromtimestamp(field_content)
>     except (KeyError, OverflowError):
```

ymmv; if you want to try this and you've got the app rolled out locally all you have to do is shut it down, update `SyncToken.py` as shown, and start it up again.

Be aware, though, that this change satisfies my immediate needs but was done without any contextual knowledge about the design of this application; I just found what was shouting and made it shut up. If anybody wants me to provide me some guidance I'd be happy to open up a PR, fix this crap up, and get it merged.

In the process, I believe I discovered another bug in SyncToken.py (you can see me fix it above):

`log` is imported as an alias for the `logger` module, which provides methods for creating logger objects. Down-file, however, it's referenced where we expect a logger object to be: `log.error("some message")`. This will fail (as I discovered) without creating and using a real logger object first.

**Closed** 2020-07-05 11:40 UTC
Labels: bug

**Comment by OzzieIsaacs** [comment] 2020-07-05 11:41
This bug only affected windows, the value -62135596800.0 should translate to timestamp 1.1.101, but throws error on windows, as only timestamps between 1970 and 2038 are handled.

**Comment by OzzieIsaacs** [comment] 2020-07-05 11:53
@DruidGreeneyes : Thanks for pointing out the logging error, it's also fixed now
