### ISSUE TITLE
500 error while uploading a pdf

### ISSUE THREAD

**Issue by konart** [janeczku/calibre-web#2313] opened 2022-02-11 14:18 UTC
**Describe the bug/problem**
Calibre-web fires a 500 http error while trying to upload a certain pdf file. The said file can be opened fine on macOS with the default Preview app. I also validated it with https://www.pdf-online.com/osa/validate.aspx Validation result is:

```
Document validated successfully.
--
The document does conform to the PDF 1.6 standard.
```

**To Reproduce**
1. Go to main page
2. Click on 'upload'
3. Chose a pdf (not sure if I can provide the pdf in question here)

**Trace**
```
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app   
    response = self.full_dispatch_request()   
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)        
  File "/app/calibre-web/cps/editbooks.py", line 65, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 1041, in upload
    db_book, input_authors, title_dir = create_book_on_upload(modif_date, meta)
  File "/app/calibre-web/cps/editbooks.py", line 963, in create_book_on_upload
    modif_date |= edit_book_tags(meta.tags, db_book)
  File "/app/calibre-web/cps/editbooks.py", line 442, in edit_book_tags
    input_tags = tags.split(',')
TypeError: a bytes-like object is required, not 'str'

```

**Expected behavior**
The pdf is uploaded without an error, user is redirected to the next page

**Environment (please complete the following information):**
 - OS: Linux 5.4.0-96-generic # 109-Ubuntu x86_64
 - Version: 0.6.16
 - Docker image: lscr.io/linuxserver/calibre-web:latest ([source](https://hub.docker.com/layers/linuxserver/calibre-web/latest/images/sha256-f301435da93a8e8c49fd6d4867c1761c264b2865f2ca73bebc0203d64663ac6b?context=explore))
 - Browser: Edge 98.0.1108.43

**Comment by OzzieIsaacs** [comment] 2022-02-12 08:53
I tried to figure out what the problem could be, but without the book in question I see no chance. Could you please send me the pdf file via private email (to the email account listed on my profile page)

**Comment by wgibcus** [comment] 2022-03-04 23:37
What language is the PDF?

**Comment by konart** [comment] 2022-03-09 07:13
First of all: sorry for the late reply.

The language is russian, but I don't think this was the problem as I have a number pdf's in russian.

Anyway - I've updated to 0.6.17 today and now the same pdf works well (uploading etc).

**Comment by OzzieIsaacs** [comment] 2022-03-09 12:02
Duplicate of #2302.
I checked your book, it was the same problem as the above mentioned issue. So I consider this as solved

**Closed by OzzieIsaacs** 2022-03-09 12:02 UTC
Labels: not reproducible
