### ISSUE TITLE
discussion forum

### ISSUE THREAD

**Issue by jagadeesh-s2104** [janeczku/calibre-web#1961] opened 2021-04-21 19:45 UTC
**Is your feature request related to a problem? Please describe.**
I have lot of questions about setting up - and I couldn't find any discussion forum for calibre-web.

**Describe the solution you'd like**
Any mods - can you create an official discussion forum for calibre-web??

**Comment by OzzieIsaacs** [comment] 2021-04-28 17:51
Duplicate of #1933

**Closed** 2021-05-04 18:47 UTC
