### ISSUE TITLE
[iOS] Caliblur! Download button not working on 0.6.12

### ISSUE THREAD

**Issue by gabmak** [janeczku/calibre-web#2013] opened 2021-06-05 16:36 UTC
**Describe the bug/problem**
- The download button is not working when using an iOS device (Safari or Chrome). When clicking the download button, nothing will happen, no drop-down menu appear.
- Background color shifted a bit, seems to be related to the div
- The problem only happens in iOS, Android and Windows is working fine
- Download button in 0.6.11 is working fine 

**To Reproduce**
1. Select any book
2. Click the download button
3. bug appears

**Logfile**
Nothing in the log file related to this bug

**Screenshots**
![IMG_8128](https://user-images.githubusercontent.com/22220745/120898659-6180f980-c65e-11eb-81c4-c1b54595fadd.PNG)

**Environment (please complete the following information):**
 - OS: Alpine Linux 3.12.4
 - Python version: python 3
 - Calibre-Web version: 0.6.12
 - Docker container: LinuxServer
 - Special Hardware: DS218+
 - Browser: iOS Safari / iOS Chrome

**Comment by OzzieIsaacs** [comment] 2021-06-05 16:39
Duplicate of #2003.
Please change theme to standard one, or update to the newest nightly version. The problem doesn't occur there or is fixed there.

**Closed** 2021-09-25 12:01 UTC
Labels: bug, duplicate, Caliblur! Theme
