### ISSUE TITLE
Login page not working behind reverse proxy

### ISSUE THREAD

**Issue by adriaanh** [janeczku/calibre-web#873] opened 2019-04-03 20:18 UTC
As in issue #327 and #304 I cannot access the login page. Everything is working fine, including downloading and browsing the ebooks.  When I access https://books.domain.com/me however, the webpage will go to the internal docker url (f.i. http://239klASDH/login?next=%2Fme. When I change this to https://books.domain.com/login?next=%2Fme, everything is working fine and I can login.

I've seen several issues regarding Traefik, and all indicate that I should set the 'passHostHeader' to 'true'. However, this does not change the behavior of Calibre. 

Is it possible to change the application in such a way that for the login screen it will 'search' for the host, but instead (as with all other links) just use the current URL?

Thanks!

**Comment by dsaoijhlgfdngfsd** [comment] 2019-04-08 07:20
I encountered the same issue yesterday, using calibre-web in a docker from linuxserver.io, together with Traefik as a reverse proxy (in docker as well). 

I did some investigation and came up with this: the issue is with redirects, all redirects point to the hostname of the **reverse proxy**. This is caused by cps/reverseproxy.py, specifically line 52:

`servr = environ.get('HTTP_X_FORWARDED_SERVER', '')`

I understand where this is coming from ([code snippet](http://flask.pocoo.org/snippets/35/)), however I suspect the comment under the snippet which was used as an inspiration for the code is wrong. [Apache documentation](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html) states the following:

> **X-Forwarded-Host**
    The original host requested by the client in the Host HTTP request header.
**X-Forwarded-Server**
    The hostname of the proxy server.

Since calibre-web is using **X-Forwarded-Server** and Traefik is populating the filed correctly, redirects within the calobre-web target the hostname of the reverse proxy itself, instead of the server of the application.

**Comment by OzzieIsaacs** [comment] 2019-04-08 12:07
There is already a pullrequest #871 available for fixing the issue

**Comment by adriaanh** [comment] 2019-04-08 15:58
Great! Thanks for the feedback and analysis. Looking forward to the fix.

**Comment by OzzieIsaacs** [comment] 2019-04-14 09:20
It's merged, please try the newest commit

**Closed by OzzieIsaacs** 2019-04-14 09:20 UTC
