### ISSUE TITLE
Message box from server admin

### ISSUE THREAD

**Issue by bppdddqqqq** [janeczku/calibre-web#1353] opened 2020-05-04 23:22 UTC
**Is your feature request related to a problem? Please describe.**
I would like to have a way to communicate certain things to my users on the server without needing to address them directly via email/IM. But currently it's not feasible.

**Describe the solution you'd like**
I would like to have a simple message box that would be visible to the user in the library view, with no limit on what it should have.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by OzzieIsaacs** [comment] 2020-05-24 06:48
Duplicate of #1308. I'll close this one.

**Closed by OzzieIsaacs** 2020-05-24 06:48 UTC
