### ISSUE TITLE
babel report AttributeError: 'NoneType' object has no attribute 'date_formats'

### ISSUE THREAD

**Issue by vagra** [janeczku/calibre-web#889] opened 2019-04-22 15:34 UTC
calibre-web report many error in the /var/log/messages :

python36: File "/path/calibre-web/vendor/babel/dates.py", line 378, in get_date_format
python36: return Locale.parse(locale).date_formats[format]
python36: AttributeError: 'NoneType' object has no attribute 'date_formats'

```
# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core

# python3 -V
Python 3.6.6

# vim /var/log/messages
Apr 22 22:43:54 Vagra python36: [2019-04-22 22:43:54,902] ERROR in app: Exception on /book/3632 [GET]
Apr 22 22:43:54 Vagra python36: Traceback (most recent call last):
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 2292, in wsgi_app
Apr 22 22:43:54 Vagra python36: response = self.full_dispatch_request()
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 1815, in full_dispatch_request
Apr 22 22:43:54 Vagra python36: rv = self.handle_user_exception(e)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 1718, in handle_user_exception
Apr 22 22:43:54 Vagra python36: reraise(exc_type, exc_value, tb)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/_compat.py", line 35, in reraise
Apr 22 22:43:54 Vagra python36: raise value
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 1813, in full_dispatch_request
Apr 22 22:43:54 Vagra python36: rv = self.dispatch_request()
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 1799, in dispatch_request
Apr 22 22:43:54 Vagra python36: return self.view_functions[rule.endpoint](**req.view_args)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/web.py", line 348, in decorated_view
Apr 22 22:43:54 Vagra python36: return func(*args, **kwargs)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/web.py", line 1611, in show_book
Apr 22 22:43:54 Vagra python36: have_read=have_read, kindle_list=kindle_list, reader_list=reader_list, page="book")
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/web.py", line 710, in render_title_template
Apr 22 22:43:54 Vagra python36: return render_template(instance=config.config_calibre_web_title, accept=EXTENSIONS_UPLOAD, *args, **kwargs)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/templating.py", line 135, in render_template
Apr 22 22:43:54 Vagra python36: context, ctx.app)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/templating.py", line 117, in _render
Apr 22 22:43:54 Vagra python36: rv = template.render(context)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/jinja2/asyncsupport.py", line 76, in render
Apr 22 22:43:54 Vagra python36: return original_render(self, *args, **kwargs)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/jinja2/environment.py", line 1008, in render
Apr 22 22:43:54 Vagra python36: return self.environment.handle_exception(exc_info, True)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/jinja2/environment.py", line 780, in handle_exception
Apr 22 22:43:54 Vagra python36: reraise(exc_type, exc_value, tb)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/jinja2/_compat.py", line 37, in reraise
Apr 22 22:43:54 Vagra python36: raise value.with_traceback(tb)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/templates/detail.html", line 1, in top-level template code
Apr 22 22:43:54 Vagra python36: {% extends is_xhr|yesno("fragment.html", "layout.html") %}
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/templates/layout.html", line 190, in top-level template code
Apr 22 22:43:54 Vagra python36: {% block body %}{% endblock %}
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/templates/detail.html", line 148, in block "body"
Apr 22 22:43:54 Vagra python36: <p>{{_('Publishing date')}}: {{entry.pubdate|formatdate}} </p>
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/web.py", line 412, in formatdate_filter
Apr 22 22:43:54 Vagra python36: return format_date(formatdate, format='medium', locale=get_locale())
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/babel/dates.py", line 698, in format_date
Apr 22 22:43:54 Vagra python36: format = get_date_format(format, locale=locale)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/babel/dates.py", line 378, in get_date_format
Apr 22 22:43:54 Vagra python36: return Locale.parse(locale).date_formats[format]
Apr 22 22:43:54 Vagra python36: AttributeError: 'NoneType' object has no attribute 'date_formats'
Apr 22 22:43:54 Vagra python36: ERROR:flask.app:Exception on /book/3632 [GET]
Apr 22 22:43:54 Vagra python36: Traceback (most recent call last):
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 2292, in wsgi_app
Apr 22 22:43:54 Vagra python36: response = self.full_dispatch_request()
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 1815, in full_dispatch_request
Apr 22 22:43:54 Vagra python36: rv = self.handle_user_exception(e)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 1718, in handle_user_exception
Apr 22 22:43:54 Vagra python36: reraise(exc_type, exc_value, tb)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/_compat.py", line 35, in reraise
Apr 22 22:43:54 Vagra python36: raise value
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 1813, in full_dispatch_request
Apr 22 22:43:54 Vagra python36: rv = self.dispatch_request()
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/app.py", line 1799, in dispatch_request
Apr 22 22:43:54 Vagra python36: return self.view_functions[rule.endpoint](**req.view_args)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/web.py", line 348, in decorated_view
Apr 22 22:43:54 Vagra python36: return func(*args, **kwargs)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/web.py", line 1611, in show_book
Apr 22 22:43:54 Vagra python36: have_read=have_read, kindle_list=kindle_list, reader_list=reader_list, page="book")
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/web.py", line 710, in render_title_template
Apr 22 22:43:54 Vagra python36: return render_template(instance=config.config_calibre_web_title, accept=EXTENSIONS_UPLOAD, *args, **kwargs)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/templating.py", line 135, in render_template
Apr 22 22:43:54 Vagra python36: context, ctx.app)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/flask/templating.py", line 117, in _render
Apr 22 22:43:54 Vagra python36: rv = template.render(context)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/jinja2/asyncsupport.py", line 76, in render
Apr 22 22:43:54 Vagra python36: return original_render(self, *args, **kwargs)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/jinja2/environment.py", line 1008, in render
Apr 22 22:43:54 Vagra python36: return self.environment.handle_exception(exc_info, True)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/jinja2/environment.py", line 780, in handle_exception
Apr 22 22:43:54 Vagra python36: reraise(exc_type, exc_value, tb)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/jinja2/_compat.py", line 37, in reraise
Apr 22 22:43:54 Vagra python36: raise value.with_traceback(tb)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/templates/detail.html", line 1, in top-level template code
Apr 22 22:43:54 Vagra python36: {% extends is_xhr|yesno("fragment.html", "layout.html") %}
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/templates/layout.html", line 190, in top-level template code
Apr 22 22:43:54 Vagra python36: {% block body %}{% endblock %}
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/templates/detail.html", line 148, in block "body"
Apr 22 22:43:54 Vagra python36: <p>{{_('Publishing date')}}: {{entry.pubdate|formatdate}} </p>
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/cps/web.py", line 412, in formatdate_filter
Apr 22 22:43:54 Vagra python36: return format_date(formatdate, format='medium', locale=get_locale())
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/babel/dates.py", line 698, in format_date
Apr 22 22:43:54 Vagra python36: format = get_date_format(format, locale=locale)
Apr 22 22:43:54 Vagra python36: File "/path/calibre-web/vendor/babel/dates.py", line 378, in get_date_format
Apr 22 22:43:54 Vagra python36: return Locale.parse(locale).date_formats[format]
Apr 22 22:43:54 Vagra python36: AttributeError: 'NoneType' object has no attribute 'date_formats'
Apr 22 22:43:54 Vagra python36: ERROR:tornado.access:500 GET /book/3632 (127.0.0.1) 22.20ms
```

**Comment by OzzieIsaacs** [comment] 2019-04-22 18:15
Many errors are kind of normal for unexpected errors, Python outputs the whole callstack, so errors can be tracked back.
Does the error occur on every book you try to view the details? Are you opening the book as logged in user or as guest? Which version of Babel is installed (-> on about/stats page visible) which user language did you choose?

**Comment by vagra** [comment] 2019-04-23 01:33
1、Just a few books have these errors

2、about/stats

```
Image Magick | ImageMagick 6.7.8-9 2019-02-01 Q16 http://www.imagemagick.org
-- | --
v1.26.0
v4.3.3.0
0.5.2
v6.0.0
v2.6.0
v1.3.2
v0.15.2
v2.10
v1.0.2
v0.4.1
v0.4.0
v0.4.5
v2018.9
v2.21.0
v2.6.0
v3.7.17
Amazon kindlegen(Linux) V2.9 build 1028-0897292
v6.0.2
3.6.6 (default, Mar 29 2019, 00:03:27)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]


```

**Comment by OzzieIsaacs** [comment] 2019-04-23 19:37
Looks good. I can reproduce the error if I destroy my settings database and delete the language setting. To make sure, you don't have this problem, please go to the users page and change the user language to something else than it is now (maybe english) and try again please. If this isn't helping please update to the newest commit, the problem should not occour anymore, but you should get an output in the log like:
`calibre-web/cps/web.py:415} ERROR - Babel error: 'NoneType' object has no attribute 'date_formats', Current user locale: None, Current User: admin`
Please post this line, I don't understand how this can happen

**Comment by vagra** [comment] 2019-04-24 02:59
when Guest language setting is en:
```
Apr 24 10:37:45 Vagra python36: [2019-04-24 10:37:45,265] ERROR in web: Babel error: 'NoneType' object has no attribute 'date_formats', Current user locale: en, Current User: Guest
Apr 24 10:37:45 Vagra python36: ERROR:flask.app:Babel error: 'NoneType' object has no attribute 'date_formats', Current user locale: en, Current User: Guest
Apr 24 10:42:37 Vagra python36: [2019-04-24 10:42:37,815] ERROR in web: Babel error: 'NoneType' object has no attribute 'date_formats', Current user locale: en, Current User: Guest
Apr 24 10:42:37 Vagra python36: ERROR:flask.app:Babel error: 'NoneType' object has no attribute 'date_formats', Current user locale: en, Current User: Guest
Apr 24 10:47:12 Vagra python36: [2019-04-24 10:47:12,822] ERROR in web: Babel error: 'NoneType' object has no attribute 'date_formats', Current user locale: en, Current User: Guest
Apr 24 10:47:12 Vagra python36: ERROR:flask.app:Babel error: 'NoneType' object has no attribute 'date_formats', Current user locale: en, Current User: Guest
```

when Guest language setting is zh_Hans_CN
```
Apr 24 10:50:01 Vagra systemd: Started Session 349 of user root.
Apr 24 10:52:06 Vagra python36: [2019-04-24 10:52:06,256] ERROR in web: Babel error: 'NoneType' object has no attribute 'date_formats', Current user locale: zh_Hans_CN, Current User: Guest
Apr 24 10:52:06 Vagra python36: ERROR:flask.app:Babel error: 'NoneType' object has no attribute 'date_formats', Current user locale: zh_Hans_CN, Current User: Guest
```



```
# locale -a | grep -E 'en|zh'
en_AG
en_AG.utf8
en_AU
en_AU.iso88591
en_AU.utf8
en_BW
en_BW.iso88591
en_BW.utf8
en_CA
en_CA.iso88591
en_CA.utf8
en_DK
en_DK.iso88591
en_DK.utf8
en_GB
en_GB.iso88591
en_GB.iso885915
en_GB.utf8
en_HK
en_HK.iso88591
en_HK.utf8
en_IE
en_IE@euro
en_IE.iso88591
en_IE.iso885915@euro
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ
en_NZ.iso88591
en_NZ.utf8
en_PH
en_PH.iso88591
en_PH.utf8
en_SG
en_SG.iso88591
en_SG.utf8
en_US
en_US.iso88591
en_US.iso885915
en_US.utf8
en_ZA
en_ZA.iso88591
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW
en_ZW.iso88591
en_ZW.utf8
french
slovene
slovenian
zh_CN
zh_CN.gb18030
zh_CN.gb2312
zh_CN.gbk
zh_CN.utf8
zh_HK
zh_HK.big5hkscs
zh_HK.utf8
zh_SG
zh_SG.gb2312
zh_SG.gbk
zh_SG.utf8
zh_TW
zh_TW.big5
zh_TW.euctw
zh_TW.utf8

```

**Comment by OzzieIsaacs** [comment] 2019-04-24 15:59
The locale setting the program is referring to, is only inside calibre-web and has nothing to do with the system locale setting, is program's locale setting is generated from the language you select inside calibre-web.
I did some more tests, I can't reproduce the error. My only idea would be delete/uninstall the babel lib and reinstall it and to be sure also reinstall calibre-web (at least for a test). 
If this isn't helping, I have no further ideas, and I would like to close the issue, as it is somewhat solved for you.

**Comment by OzzieIsaacs** [comment] 2019-04-24 16:10
One very very last idea: You could try (and only try and not use it in a production system) the development branch.

**Comment by pwr** [comment] 2019-04-30 20:35
It is possible this may be a client-side issue?
I've had the same error happen when my browser wasn't sending the `Accept-Language` header in HTTP requests, and babel was unable to negociate the locale, returning `None` from [get_locale()](https://github.com/janeczku/calibre-web/blob/master/cps/web.py#L220).
This may not apply to @vagra setup, but in my case the cause was my messing with the Firefox configuration (I had an empty list of preferred languages); fixing that made the error go away.
Perhaps having a fallback default in get_locale() might help, at least server-side?

**Comment by OzzieIsaacs** [comment] 2019-05-11 06:10
Sorry, I forget to give feedback:
Your suggestion is a good one, I will add this (was also one of my first guesses). 
The added debug output "current-locale" is exactly this variable, and you can see that it's not set to none. I have no idea why this happens and what causes it.
@vagra are there any news on this?

**Closed** 2019-07-06 12:48 UTC

**Comment by p8ul** [comment] 2020-03-12 07:02
@vagra is right you have to exporting the language in the terminal saved my day

`export LANG=en_US.UTF-8`
` export LC_ALL=en_US.UTF-8`
