### ISSUE TITLE
caliBlur theme hides plexBack button on mobile

### ISSUE THREAD

**Issue by ytilis** [janeczku/calibre-web#840] opened 2019-03-13 03:05 UTC
So I'm not sure if this is a bug for this repo or the layer.Cake repo, but I noticed that the back button disappears on mobile when using the caliBlur theme. This means that once you open the details of a book, there's no way to close it without using the device back button. 

I've attached the dev tools screenshot showing it being set to `display: none` at lower resolutions, but I can't quite find where it's happening.

![image](https://user-images.githubusercontent.com/1395508/54250634-f39b0580-451a-11e9-8b90-fd94fcc15b81.png)

**Comment by OzzieIsaacs** [comment] 2019-04-14 13:46
@leram84 could you pleasetake alook at this one?

Thanks a lot

**Comment by leram84** [comment] 2019-04-15 12:16
Feature not a bug :P lol, But in all seriousness, this was a design choice. I felt the top bar would be too busy with a back button on the mobile theme, and the back button wasn't something that existed outside of caliblur to begin with so felt it wasn't a big loss. On mobile, the device back button is superior anyway, and there is the browser back button as well... though i guess with ios you only have one of those.

**Comment by ytilis** [comment] 2019-04-16 22:11
Just to clarify, I mostly reported it because I found it inconsistent with the desktop display. But it was also a bit jarring to go from the Standard theme, where clicking a book opens a modal with two on-screen ways to close it, to the full page navigation of the caliBlur theme where there was no on-screen navigation on mobile. Though the Standard theme's modal made getting back to the page easy, it discouraged back button use, since that would have unintended side effects, and I guess I just fell out of the habit of using it when browsing my library as a result.

But if it was an intentional decision, that's obviously up to your discretion. I just wanted to make you guys aware of it in case it was a bug.

Thanks for clearing that up!

**Comment by OzzieIsaacs** [comment] 2019-04-17 19:18
I‘m closing the issue. Thanks for clarifying

**Closed by OzzieIsaacs** 2019-04-17 19:18 UTC
