### ISSUE TITLE
Send to Pocketbook

### ISSUE THREAD

**Issue by Dinth** [janeczku/calibre-web#1125] opened 2020-01-05 11:13 UTC
Hey. could you please add "Send to Pocketbook" option next to "Send do Kindle"? Apparently - according to https://github.com/janeczku/calibre-web/issues/724 - send to kindle already works with Pocketbooks but just sends a wrong format.
Im an owner of both Kindle and Pocketbook and i would love to be able to send ePubs to my PB in same way as i can send mobis to my Kindle.

**Comment by OzzieIsaacs** [comment] 2020-01-08 20:04
Duplicate of  #1054

**Comment by RafalHo** [comment] 2020-04-15 15:54
I am also in favor of this solution.
Of course, I can use the "Send to Kindle" option, but then mobi files are sent by email, but epub files would be better.

Is there a chance to add such an option?
Alternatively, if you could add a choice, what format is to be sent?

**Comment by OzzieIsaacs** [comment] 2023-08-04 08:49
Meanwhile the button is renamed and it's possilbe to send epubs to a ereader

**Closed by OzzieIsaacs** 2023-08-04 08:49 UTC
Labels: duplicate
