### ISSUE TITLE
SubShelves

### ISSUE THREAD

**Issue by reavessm** [janeczku/calibre-web#1286] opened 2020-04-01 12:56 UTC
**Describe the solution you'd like**
I would like to be able to create a new shelve inside of an existing shelf.  For example, I want to be able to have one big JoJo's Shelf, then have separate shelves for parts 1-7.  I don't want the subshelves visible until after I click into the main shelf.

**Comment by OzzieIsaacs** [comment] 2020-04-05 07:04
Duplicate of  #370

**Closed** 2020-05-24 06:49 UTC
Labels: duplicate
