### ISSUE TITLE
500 Internal Server Error after login

### ISSUE THREAD

**Issue by pedja1** [janeczku/calibre-web#2456] opened 2022-06-24 21:58 UTC
**Describe the bug/problem**
It suddenly started crashing, initially it was working fine. I tried restarting docker container

**To Reproduce**
1. Login
2. 500 is returned with following error

**Logfile**
```
[2022-06-24 23:48:09,283] ERROR {cps:1457} Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 752, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/app/calibre-web/cps/web.py", line 391, in render_books_list
    entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
  File "/app/calibre-web/cps/db.py", line 725, in fill_indexpage
    return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
  File "/app/calibre-web/cps/db.py", line 732, in fill_indexpage_with_archived_books
    random_query = self.generate_linked_query(config_read_column, database)
  File "/app/calibre-web/cps/db.py", line 686, in generate_linked_query
    query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'
```

**Expected behavior**
No crash

**Environment (please complete the following information):**
 - OS: Arch Linux (client), Arch Linux (server) 
 - Python version: 3.8.10 - inside container
 - Calibre-Web version: where can i find this, linuxserver docker is used: linuxserver/calibre-web:latest
 - Docker container: linuxserver/calibre-web:latest
 - Special Hardware: no
 - Browser: Brave 1.40.105, Arch Linux

**Additional context**
linuxserver/calibre is used, reverse proxy is used. It was working just fine until now, i didnt do anything, except update some other docker images (not calibre or calibre-web)

**Comment by OzzieIsaacs** [comment] 2022-07-31 09:32
Duplicate of #2231 and many more. This is some sort of access problem from the docker container. I'm not the owner of the docker container, so I can't help. Please ask for help at the docker container repository

**Closed by OzzieIsaacs** 2022-07-31 09:32 UTC
Labels: Docker
