### ISSUE TITLE
Cannot view cbr files with rar5 compression

### ISSUE THREAD

**Issue by adelatour11** [janeczku/calibre-web#1333] opened 2020-04-28 08:02 UTC
Calibre web cannot display a cbr file i want to open
The file is a cbr (266Mo)
When i open it i just have the blank page with title "Read a book", and on the left i have a small loading text with a progress bar that is stuck at 20%
Page controls (previous, next, settings, and full screen) are shown but as there is no page displayed nothing happens when clicking on previous or next

In the browser console i just have "Unarchiving done in 0.497s"

The cbr is correct and can be opened in local calibre application

I have activated debug log and i have other info than that :
[2020-04-28 09:44:25,112]  INFO {cps.web:1116} Serving book: Book Name - Author

**Comment by OzzieIsaacs** [comment] 2020-04-28 08:12
Could you please open the book with a normal unarchiver:
My guess is the image files are located in a subfolder in the archive, this is as far as I remeber currently not working for rar files (aka cbr files)

**Comment by OzzieIsaacs** [comment] 2020-04-28 08:13
And please check the format of the files inside the cbr file: Which format are they: jpg, png, svg, ...?

**Comment by adelatour11** [comment] 2020-04-28 08:27
thanks for your quick feedback
i have just checked the cbr content using 7zip :

Y:\path\name.cbr\
001-0000.jpg
002-0001.jpg
003-0002.jpg

**Comment by OzzieIsaacs** [comment] 2020-04-28 10:31
Okay, so the files are not in an subfolder in the cbr file. Are you using Microoft Internet Explorer (11 oder Edge, which one?) for accessing the files.
The problem might be related to size (normally not) or related to the files itself (you mentioned the 20% progress bar). One idea would be deleting some of the files to change the size, to check if it depends on this.
You could also replace some of the files in a working file to some of the files of the non working ones, to tear down the problem more. 
Or you send me the file via private email (on my profile page), (well the link to the file) and I check what can be done.
Which version of calibre-web are you using?

**Comment by OzzieIsaacs** [comment] 2020-04-28 10:35
The biggest file I found has 203MB and works without problem

**Comment by adelatour11** [comment] 2020-04-28 11:23
I am using Chrome and the latest version of calibre web (4/27/20, 9:15 PM)
I have sent the link to your email adress, thanks !

**Comment by OzzieIsaacs** [comment] 2020-04-28 15:54
The file is a rar5 file, and calibre-web currently only supports rar4 files

**Comment by adelatour11** [comment] 2020-04-28 19:33
Indeed, it fixed the issue when i changed the file to rar4, thanks again for your quick support

**Comment by OzzieIsaacs** [comment] 2020-04-28 19:35
To be future proof we need support for rar5

**Comment by OzzieIsaacs** [comment] 2020-05-25 19:39
I'm closing this issue as duplicate of issue #1196

**Closed by OzzieIsaacs** 2020-05-25 19:39 UTC
Labels: bug
