### ISSUE TITLE
Delete Book Error

### ISSUE THREAD

**Issue by killercore** [janeczku/calibre-web#1639] opened 2020-09-27 18:46 UTC
I have two instances running of Calibre web. one is running fine and i can delete books. i created a second instance for a friend with an empty metadata.db but deleting books is giving errors.

The weird part is the book is deleted and the name was correct before it got deleted. but it won't get it out of calibre.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 194, in delete_book
    db.session.query(db.Books).filter(db.Books.id == book_id).delete()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3791, in delete
    delete_op.exec_()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1697, in exec_
    self._do_exec()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1928, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1702, in _execute_stmt
    self.result = self.query._execute_crud(stmt, self.mapper)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3438, in _execute_crud
    return conn.execute(stmt, self._params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) error in tokenizer constructor
[SQL: DELETE FROM books WHERE books.id = ?]
[parameters: (1298,)]
(Background on this error at: http://sqlalche.me/e/e3q8)
[2020-09-27 18:43:45,824] ERROR {cps.helper:288} Deleting book 1298 failed, book path not valid: Natasha Madison/Flirten met de buurman (1298)

```

**Comment by OzzieIsaacs** [comment] 2020-09-27 18:57
Please try a library check in calibre desktop application (in library -> library maintenance)
Updating Calibre-Web to the newest version might also be a good idea (you didn't tell me which version you are using)

**Comment by OzzieIsaacs** [comment] 2020-09-27 19:06
You are using 0.6.6, meanwhile version 0.6.9 is out. The error is handled meanwhile in a newer version. (To update got to: admin section -> search for Update -> perform update)

**Comment by muziling** [comment] 2020-09-28 14:41
version 0.6.9, book delete success ,book download 404, file deleted success, but  book still in the list ,can be searched, etc ,    Does database record not deleted?

**Comment by killercore** [comment] 2020-09-28 16:14
i got the same. updated to 0.6.9 and the book gets deleted as a file but the entry is staying in the calibre db. if i try to delete it again it says the book is missing.

**Comment by maltokyo** [comment] 2020-09-29 07:50
@OzzieIsaacs I have the same thing in version 0.6.9.  I can delete the PDF (file itself) but the entry of the book stays in the DB.  Cannot do anything after that as when you try to delete the entry it complains that there is no file to delete.

**Comment by killercore** [comment] 2020-10-02 17:37
was anyone able to fix this yet?

**Comment by OzzieIsaacs** [comment] 2020-10-10 08:49
@maltokyo: I need more details. Where are the files located (remote, synced to the location by some background programs ???) What are the file and folder permissions of the calibre-database file itself (metadata.db) and the corresponding book folders and files? 
I need a reproducible scenario for fixing it. Currently I can only tell you: I'm testing it regulary automated with different test cases and scenarios and everything works well.

**Comment by killercore** [comment] 2020-10-10 10:44
Its on a synology with calibre web docker. Permissions are open for everyone as test. I think its related to the metadata.db file for some reason as my other instance with 1200 books has no issue. Only the new one. Could you maybe upload a empty metadata.db which you use or something?

**Comment by OzzieIsaacs** [comment] 2020-10-10 10:47
You could use this one as example (https://github.com/OzzieIsaacs/calibre-web-test/blob/master/test/Calibre_db/metadata.db), there are 11 files in it and the test files are also located in the folder. Have you tried the Calibre-web maintenance function on your library?

**Comment by BoneAsh** [comment] 2020-11-04 04:20
I create an empty metadata.db, you can try this. https://github.com/BoneAsh/Calibre-web-metadata. @killercore @muziling @maltokyo

**Comment by BoneAsh** [comment] 2020-11-04 09:19
I have the same thing in version 0.6.9 and hope someone to resolve it. now you can use this metadata.db to avoid the problem.

**Comment by BoneAsh** [comment] 2020-11-04 10:53
I have the same problem in 0.6.9, so i create an empty metadata.db by Ozzielsaacs`s link and it works well, you can try it. https://github.com/BoneAsh/Calibre-web-metadata @maltokyo @killercore hope someone to fix the problem.

**Comment by OzzieIsaacs** [comment] 2020-11-07 11:17
I can't reproduce it. Please send me the database (the metadata.db file is enough) per private email (on my profile page). I can have a look at it, otherwise I can't help you.

**Comment by BoneAsh** [comment] 2020-11-11 00:47
ok, I will send you an email.

**Comment by killercore** [comment] 2020-11-16 16:52
this empty db worked for me. maybe it's an idea to put it between the test files in case someone needs it.

**Comment by OzzieIsaacs** [comment] 2020-11-25 18:42
You issue:
You installed calibre version 5.xx, accessed the the database with this program and afterwards Calibre-Web not working anymore. Now you can change calibre-Web versions forth and back, the error is still the same, trying to delete a book creates the error, even with Calibre-Web versions which worked before.
You are using an older Linux distro like Ubuntu 18.04, ...

Having this information, the solution is very easy, it has nothing to do with Calibre-Web. Calibre added new tables in the database, this tables require new features, which the sqlite driver of your distro is not supporting (e.g. 3.22 for Ubuntu, visible in about section). 
You are lucky, because if I hadn't had the same problem, I would never found it with the information you provided. I created the issue template for asking basic infomration, this would have helped here a lot and would have saved both of use time.

Solution:
Please install `pysqlite3-binary` from pip, search for the installed package (something like ..site-packages/pysqlite3/_sqlite3.cpython-36m-x86_64-linux-gnu.so) symlink the shared library to the calibre-web root folder with a filename `_sqlite3.so`.
Restart Calibre-web, you'll see the new driver version in the about section:
![grafik](https://user-images.githubusercontent.com/6438895/100268718-b1fff780-2f55-11eb-89d8-d9de2240ecbb.png)

**Comment by doctorjames** [comment] 2020-11-27 20:32
I'm using the latest linuxserver.io docker image and ran into this as well. It currently contains SQLite 3.22.0 and is based on Ubuntu 18.04:

```
# cat /etc/issue
Ubuntu 18.04.5 LTS
```

**Comment by palmfighter** [comment] 2020-11-30 10:03
I have the same issue on my linuxserver/calibre-web, hope they add the new driver soon for sqlite ;)

**Comment by jackhadrill** [comment] 2020-12-01 01:30
Thanks for raising the issue over on the linuxserver/docker-calibre-web repo @BoneAsh. I've updated your issue with a few more details.

**Comment by palmfighter** [comment] 2020-12-01 09:11
they mentioned in order to get a new build is to submit a pull request (I guess with linuxserver?). I have no experience with that, is someone possible to do so?

**Comment by skylar01** [comment] 2020-12-15 02:31
Having the same issue, I've successfully deleted the book but it kept showing in my library. When I try to delete the book again it returns:
Deleting book, book path not valid:
Book Successfully Deleted

The book is still there, I guess it's still on the database?
I'm also using docker - linuxserver/calibre-web

**Comment by palmfighter** [comment] 2020-12-15 11:43
Hi,

as they are not planning to update soon (linuxserver) I would recommend switching to another version:
technosoft2000/calibre-web

this one works fine for me, the reason I guess is because it has the correct sql driver.

**Comment by OzzieIsaacs** [comment] 2021-01-03 12:44
I'll close this one here, as I can't do anymore

**Closed by OzzieIsaacs** 2021-01-03 12:44 UTC
Labels: not reproducible, question
