### ISSUE TITLE
Uploading pdf file fails with whitespace title

### ISSUE THREAD

**Issue by kuba1909** [janeczku/calibre-web#2824] opened 2023-07-05 23:26 UTC
**Description**
When uploading a pdf file with the title " " (notice the whitespace), the server returns a 500 internal error. Removing that exif tag works around the issue and the upload succeeds.

**Steps to Reproduce**
1. Choose a valid pdf file
2. Run `exiftool -Title=" " filename.pdf`
3. Upload the pdf file

<details><summary>Logfile</summary>
<p>
[2023-07-06 00:48:42,878] ERROR {cps:1449} Exception on /upload [POST]<br>
Traceback (most recent call last):<br>
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app<br>
    response = self.full_dispatch_request()<br>
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request<br>
    rv = self.handle_user_exception(e)<br>
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request<br>
    rv = self.dispatch_request()<br>
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request<br>
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)<br>
  File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view<br>
    return login_required(func)(*args, **kwargs)<br>
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 290, in decorated_view<br>
    return current_app.ensure_sync(func)(*args, **kwargs)<br>
  File "/app/calibre-web/cps/editbooks.py", line 61, in inner<br>
    return f(*args, **kwargs)<br>
  File "/app/calibre-web/cps/editbooks.py", line 252, in upload<br>
    meta, error = file_handling_on_upload(requested_file)<br>
  File "/app/calibre-web/cps/editbooks.py", line 738, in file_handling_on_upload<br>
    meta = uploader.upload(requested_file, config.config_rarfile_location)<br>
  File "/app/calibre-web/cps/uploader.py", line 263, in upload<br>
    return process(tmp_file_path, filename_root, file_extension, rarExcecutable)<br>
  File "/app/calibre-web/cps/uploader.py", line 92, in process<br>
    if not meta.author.strip() or meta.author.lower() == 'unknown':<br>
AttributeError: 'str' object has no attribute 'author'
</p>
</details>

**Expected behavior**
PDF file should be successfully uploaded, possibly omitting the title tag and using the file name instead.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.10.6
 - Calibre-Web version: V0.6.20
 - Docker container: linuxserver/calibre-web:latest@sha256:4365c4851dc6a41f71429d56770b478587b85cdf91f3cb6005604c806762fed9
 - Special Hardware: usual amd64
 - Browser: Firefox 115

**Additional context**
Access via reverse proxy, but that shouldn't make any difference.

**Comment by OzzieIsaacs** [comment] 2023-08-12 12:07
The PR #2775 addresses this issue

**Comment by OzzieIsaacs** [comment] 2023-08-12 12:10
Thanks for the detailed description 
The problem is fixed in the newest nightly build, so if you update to this version, it should work

**Closed** 2023-10-23 07:52 UTC
Labels: bug, Fixed in Nightly
