### ISSUE TITLE
Calibre-web won't start after update

### ISSUE THREAD

**Issue by michal-b-kaminski** [janeczku/calibre-web#1235] opened 2020-02-29 08:38 UTC
**Describe the bug/problem**
After updating docker image to latest version, calibre-web won't start. Logs show this error repeating all the time:

```
AttributeError: type object 'User' has no attribute 'restricted_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 34, in <module>
    from cps import create_app
  File "/app/calibre-web/cps/__init__.py", line 68, in <module>
    config = config_sql.load_configuration(ub.session)
  File "/app/calibre-web/cps/config_sql.py", line 348, in load_configuration
    update({"restricted_tags": conf.config_mature_content_tags}, synchronize_session=False)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3910, in update
    update_op.exec_()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1692, in exec_
    self._do_exec()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1873, in _do_exec
    values = self._resolved_values
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1839, in _resolved_values
    desc = _entity_descriptor(self.mapper, k)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/base.py", line 402, in _entity_descriptor
    "Entity '%s' has no property '%s'" % (description, key)
sqlalchemy.exc.InvalidRequestError: Entity '<class 'cps.ub.User'>' has no property 'restricted_tags'
```

Another instance of calibre-web - targeting another calibre library - works correctly after same update. 

Rolling image back to version from 6 days ago (LinuxServer.io 0.6.6-ls51) fixes the problem.

**Environment (please complete the following information):**
 - OS: Raspbian
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]: 0.6.7 Beta - 32a6beae65248060dbbe5c59110288f3f866d026 - 2020-02-23T13:17:59+01:00
 - Docker container [ None/Technosoft2000/Linuxuser]: Linuxserver.io version 0.6.6-ls53
 - Special Hardware [e.g. Rasperry Pi Zero]: Raspberry Pi 4B

**Comment by OzzieIsaacs** [comment] 2020-02-29 08:53
Duplicate of #1224
It's already fixed in master. 
So if you update to the newest commit it will work again (I think linuxserver updates it's container every sunday). You could also use the self update function of Calibre-Web (now where you got it running again)

**Closed by OzzieIsaacs** 2020-02-29 08:53 UTC

**Comment by CHBMB** [comment] 2020-02-29 11:19
@OzzieIsaacs We update every Friday night and every time you push a new Calibre-Web release.
