### ISSUE TITLE
[Enhancement] Check admin before deleting user

### ISSUE THREAD

**Issue by hurui200320** [janeczku/calibre-web#935] opened 2019-06-07 16:52 UTC
I recommend to check the admin permission before deleting a user. Today after proper configured calibre-web, I tried to delete the only one admin account and it succeed. Then I found it's no way to manage user again due to no user can manage user the set someone as admin. So I recommend you add a function which will be called before deleting a user to check if there any admin left after delete operation. Also I cannot find a way to change user's username unless I delete it and recreate it with another one. Currently using 0.6.3 Naoko.

**Comment by hurui200320** [comment] 2019-06-07 17:00
Also I cannot bind some specific address: I try to make it only listen on 127.0.0.1 so that I can use nginx to reverse proxy it to add SSL feature. I deploy calibre-web with an existing server so that's make me easier than using SSL configuration in calibre-web.

**Comment by OzzieIsaacs** [comment] 2019-06-10 17:31
The request for bnding it to a single address is a duplicate of: #667

**Comment by OzzieIsaacs** [comment] 2019-06-10 17:32
The last admin can't be deleted anymore with the lasted commit.

**Comment by OzzieIsaacs** [comment] 2019-06-10 17:36
I created another issue for the renaming of users, you should get informed if something is posted there, I also put you on the list for #667.

**Closed by OzzieIsaacs** 2019-06-10 17:36 UTC
