### ISSUE TITLE
[Docker] Unable to send to kindle via own mailserver, application crashes when log level set to debug

### ISSUE THREAD

**Issue by AugustoGarcia** [janeczku/calibre-web#1145] opened 2020-01-18 10:14 UTC
I am unable to send ebooks to my kindle using the my own smtp server.

- If I use the gmail smtp server, everything works fine
- My own mailserver works fine under thunderbird
- If I copy the thunderbird settings to calibre-web, it fails to send e-mails
- If I set the log level to debug to see what's wrong, the application crashes as soon as I send a test mail. (And the RAM usage spikes to up to 3 gb)

How can I fix this? Thanks for your help!

**Comment by OzzieIsaacs** [comment] 2020-01-18 11:08
Could you please tell me which operating system, python version and version of calibre-web you are using?
Are you using docker, or the "plain" python version?

**Comment by OzzieIsaacs** [comment] 2020-01-18 11:15
One idea you could try is: setting the logfilename to /dev/stdout, then the out would be streamed to the console. Afterwards we could maybe see more of the output before the application crashes.

**Comment by Johnpojohn** [comment] 2020-01-18 13:07
linuxserver/calibre-web running on a docker container in synology DSM. Otherwise working perfectly.
I changed the logfile as instructed and sended a test mail with the gmail smtp server, the application crashed all the same, so I suppose it's two separate issues. Absolutely no e-mail related entries in stdout (no debug entries for that matter), as soon as I try to send the test e-mail everything is blocked and there are no further log/console entries.

**Comment by Johnpojohn** [comment] 2020-01-18 13:14
Just tried converting to .mobi and then sending to kindle, the debug log is working and I see the conversion related entries. As soon as it proceeds to send the e-mail it's toast.

**Comment by tbrunain** [comment] 2020-01-19 10:32
I have a similar issue, I think .

I'm using calibre in a docker container (linuxserver/calibre-web image) , and I tried to send an ebook to my kindle, with gmx smtp configuration ... it eats up all my RAM (32 Gigs !) in no time and the only thing I can do is restart my server . I already tried to play with the logs output but no luck .

**Comment by OzzieIsaacs** [comment] 2020-01-19 10:37
without docker it's working. I think this problem is related to the docker container. Did you also report the issue on the linuxserver repro?

**Comment by Johnpojohn** [comment] 2020-01-20 09:11
Just did https://github.com/linuxserver/docker-calibre-web/issues/60#issue-552165025

So it seems the log bug is container-related but the mail bug is program-related? I'll get back here once the underlying problem is solved.

**Comment by Johnpojohn** [comment] 2020-02-07 20:15
I just managed to get it to work (not the logs, the mailserver) by using SSL/TLS instead of STARTTLS. So my issue is solved, but I'm still unable to get STARTTLS to work

**Comment by CHBMB** [comment] 2020-02-16 12:15
I can't reproduce this.

I registered for a gmx account to test, using STARTTLS and setup Calibre-web as follows

[Email Settings](https://i.imgur.com/XXqCWWz.png)
[Debug logging](https://i.imgur.com/phuW5Dn.png)

```
[2020-02-16 11:58:49,162] DEBUG {cps.admin:518} update_mailsettings {'mail_server': 'mail.gmx.com', 'mail_port': '587', 'mail_use_ssl': '1', 'mail_login': 'testaccount@gmx.com', 'mail_password': 'MYPASSWORD', 'mail_from': 'testaccount@gmx.com', 'test': 'test'}
[2020-02-16 11:58:49,163] DEBUG {cps.config_sql:259} _ConfigSQL updating storage
[2020-02-16 11:58:49,542] DEBUG {cps.worker:125} send: 'ehlo [172.19.0.15]\r\n'
[2020-02-16 11:58:49,566] DEBUG {cps.worker:125} send: 'STARTTLS\r\n'
[2020-02-16 11:58:49,642] DEBUG {cps.worker:125} send: 'ehlo [172.19.0.15]\r\n'
[2020-02-16 11:58:49,666] DEBUG {cps.worker:125} send: 'AUTH PLAIN RANDOMSTRING==\r\n'
[2020-02-16 11:58:49,812] DEBUG {cps.worker:125} send: 'mail FROM:<testaccount@gmx.com> size=550\r\n'
[2020-02-16 11:58:49,837] DEBUG {cps.worker:125} send: 'rcpt TO:<my-email-address@gmail.com>\r\n'
[2020-02-16 11:58:49,863] DEBUG {cps.worker:125} send: 'data\r\n'
```

I tried both with and without the `Calibre` docker mod.

I'm running Docker on a Slackware based Unraid system using an x64 processor and my RAM usage is minimal as shown here.

[RAM Usage](https://i.imgur.com/FeFrChH.png)

**Comment by OzzieIsaacs** [comment] 2020-02-16 12:25
Thanks for the feedback. So the only difference might be the Synology the user has. Maybe it's an ARM related issue?  
@Johnpojohn Which type of "Synology" are you using?
@tbrunain Could you tell us something about your system? Which docker container, what type of hardware (x86, ARM, ...) are you using?

**Comment by CHBMB** [comment] 2020-02-16 12:30
@OzzieIsaacs I wondered about ARM but @Johnpojohn has already stated he's using an x64 device [here](https://github.com/linuxserver/docker-calibre-web/issues/60#issue-552165025)

**Comment by OzzieIsaacs** [comment] 2020-02-16 12:49
@CHBMB, sorry I didn't realize this. We both can't reproduce it.

**Comment by fbclol** [comment] 2020-03-27 01:15
hello , I same problem :(

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 295, in _assert_activecode="7s2a",

sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)


(sqlite3.InterfaceError) Error binding parameter 5 - probably unsupported type.
[SQL: UPDATE settings SET mail_server=?, mail_port=?, mail_use_ssl=?, mail_login=?, mail_password=?, config_google_drive_watch_changes_response=? WHERE settings.id = ?]

[parameters: ('smtp.gmail.com', 465, 2, 'test@GMAIL', '*******!', {'kind': 'api#channel', 'id': '2071eb06-317e-4e2c-b799-646f56abee3f', 'resourceId': '7nS3Kt5AooP_vhk8gYLLejJNcjY', 'resourceUri': 'https://www.googlea ... (162 characters truncated) ... se&maxResults=100&supportsAllDrives=false&supportsTeamDrives=false&alt=json', 'token': 'target=calibreweb-watch_files', 'expiration': '1585785958000'}, 1)]

**Comment by CHBMB** [comment] 2020-05-06 10:56
@fbclol I don't think that is the same issue, I can defininitely confirm there isn't an issue with gmail as I use that as my email provider.

**Comment by fbclol** [comment] 2020-05-10 14:02
I could see that it had a link with dropbox synchronization which makes web caliber very slow and unstable

**Comment by OzzieIsaacs** [comment] 2020-05-10 14:14
I doublechecked it, the send email routine has a 10minute timeout set. 
I don't support any type of syncing files or reading files from remote storage in the background. Many strange issues arise from this usecases and I'm not willing to spend hours of my time to create accounts, set up storage integration and debug this type of application and chasing after this problems(maybe depending on connection speed). (->  https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request)

**Comment by OzzieIsaacs** [comment] 2020-05-24 06:51
I close it as it's not reproducible

**Closed by OzzieIsaacs** 2020-05-24 06:51 UTC
Labels: not reproducible
