### ISSUE TITLE
Cannot do advanced search when library has custom columns

### ISSUE THREAD

**Issue by Mongkii** [janeczku/calibre-web#2466] opened 2022-06-30 15:50 UTC
**Describe the bug/problem**
My library has custom columns.

Before the custom columns were added, advanced search worked fine, since there were custom columns, only quick search (the input box at the top left of window) works, click advanced search will show 'Internal Server Error' message.

**To Reproduce**
1. Create custom columns. (I created two: one is text column, id: `#group`, name: `书籍组`; the other is select column, id: `#priority`, name: `阅读优先级`, options: `高,中,低`, colors: `red,orange,green`)
2. Load library in calibre-web
3. Click advanced search

**Logfile**
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 1357, in advanced_search_form
return render_prepare_search_form(cc)
File "/app/calibre-web/cps/web.py", line 720, in render_prepare_search_form
return render_title_template('search_form.html', tags=tags, languages=languages, extensions=extensions,
File "/app/calibre-web/cps/render_template.py", line 122, in render_title_template
return render_template(instance=config.config_calibre_web_title, sidebar=sidebar, simple=simple,
File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
return _render(
File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
rv = template.render(context)
File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "/app/calibre-web/cps/templates/search_form.html", line 1, in top-level template code
{% extends "layout.html" %}
File "/app/calibre-web/cps/templates/layout.html", line 150, in top-level template code
{% block body %}{% endblock %}
File "/app/calibre-web/cps/templates/search_form.html", line 213, in block 'body'
{% for opt in c.get_display_dict().enum_values %}
File "/app/calibre-web/cps/db.py", line 389, in get_display_dict
display_dict = ast.literal_eval(self.display)
File "/usr/lib/python3.8/ast.py", line 99, in literal_eval
return _convert(node_or_string)
File "/usr/lib/python3.8/ast.py", line 88, in _convert
return dict(zip(map(_convert, node.keys),
File "/usr/lib/python3.8/ast.py", line 98, in _convert
return _convert_signed_num(node)
File "/usr/lib/python3.8/ast.py", line 75, in _convert_signed_num
return _convert_num(node)
File "/usr/lib/python3.8/ast.py", line 66, in _convert_num
_raise_malformed_node(node)
File "/usr/lib/python3.8/ast.py", line 63, in _raise_malformed_node
raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <_ast.Name object at 0x7f4ca59c98b0>
```

**Expected behavior**
Advanced search works properly

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS Monterey 12.4 (for docker image: Linux 5.10.60)
 - Python version: 3.8.10
 - Calibre-Web version: 0.6.18 - fee76741a02899d2dfdc2ce29cfc27901a06383c - 2022-04-03T20:17:34+02:00
 - Docker container: LinuxServer
 - Special Hardware: No
 - Browser: Chrome 103.0.5060.53

**Additional context**
I guess it's a problem of supports for select columns or Chinese text.

**Comment by OzzieIsaacs** [comment] 2022-07-31 10:45
Duplicate of #2398. 
Please update to newest nightly version.

**Closed** 2022-07-31 15:52 UTC
Labels: duplicate, Fixed in Nightly
