### ISSUE TITLE
Infinite thread spawning in latest version

### ISSUE THREAD

**Issue by unleashit** [janeczku/calibre-web#2584] opened 2022-10-25 06:07 UTC
**Describe the bug/problem**
Just updated my docker image to the latest and couldn't connect afterwards. Looking at the log, I saw the following error, repeated dozens of times:

RuntimeError: can't start new thread

Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())

I walked away for a bit, then got a notification that my server was using 100% CPU so I killed the container and downgraded to 0.6.18. It's now working again so for me at least, something in the new patch version (or in the official container image since then) is a problem.

**To Reproduce**
1. pull latest Docker image
2. restart container
3. curl localhost from server (can't connect)

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

Log output above. Sorry, I downgraded before I thought to see if there was a debug option. If it helps, I don't mind going back and getting the full logs.

**Expected behavior**
That it would work as it always has and not take down my server :)

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.6 (docker host)
 - Python version: 3.8.10 (docker image)
 - Calibre-Web version: 0.6.19
 - Docker container: LinuxServer
 - Special Hardware: standard amd64 VM
 - Browser: Firefox, Curl, etc.

**Additional context**
The database is read only. The books library and DB are in the volume of another container (Nextcloud) causing the permissions issue. But as I only really use Calibreweb to read and download books that I've uploaded through the desktop version, I've never looked very far into it.

**Comment by markchaik** [comment] 2022-10-30 16:38
Calibre-web not working suddenly led me to this issue.  I can confirm that I can reproduce this exactly.  CPU is pegged at high CPU, downgrading to 0.6.18 fixes the issue.

**Comment by djsordo** [comment] 2022-10-31 12:37
Confirm the issue. I can reproduce exactly since the last version

**Comment by shikasta-net** [comment] 2022-12-08 14:29
I was having this issue on version 0.6.14, upgraded to 0.6.19 didn't help but lead me here and I downgraded to 0.6.18 and it works again.

**Comment by skn** [comment] 2022-12-29 13:46
This is due to host being incompatible with images based on Ubuntu Jammy. See details and resolution at https://docs.linuxserver.io/faq#jammy

**Comment by shikasta-net** [comment] 2022-12-29 18:36
Confirmed resolved by switching to docker version 20.10.12

**Closed** 2023-01-11 20:43 UTC
Labels: invalid, Docker
