### ISSUE TITLE
I forget my root's password.😟

### ISSUE THREAD

**Issue by nanjolono** [janeczku/calibre-web#1098] opened 2019-12-06 11:13 UTC
Such as titile. Where's my password's position?

**Comment by OzzieIsaacs** [comment] 2019-12-06 13:26
duplicate of #1063

**Comment by OzzieIsaacs** [comment] 2019-12-06 13:28
The password is stored in the app.db file as hash. (You can view and change it with the sqlitebrowser program)

**Comment by OzzieIsaacs** [comment] 2019-12-15 20:00
A password reset function is implemented in the newest commit

**Closed by OzzieIsaacs** 2019-12-15 20:00 UTC
Labels: enhancement
