### ISSUE TITLE
Internal Server Error on /book/:id

### ISSUE THREAD

**Issue by yowmamasita** [janeczku/calibre-web#1182] opened 2020-02-08 12:09 UTC
Log:

```
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/web.py", line 166, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 1471, in show_book
is_xhr=request.is_xhr, title=entries.title, books_shelfs=book_in_shelfs,
File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 347, in __getattr__
return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
```

**Comment by OzzieIsaacs** [comment] 2020-02-08 12:28
duplicate of #1181

**Comment by OzzieIsaacs** [comment] 2020-02-08 12:42
Problem is you are using a version of "werkzeug" which is to new.
As workaround till I find a fix 
please try: 
`pip3 install --target vendor -I werkzeug==0.15.4`
Please refer to #1181 for the final fix. So I don't have to post everything twice.

**Closed by OzzieIsaacs** 2020-02-08 12:42 UTC
