### ISSUE TITLE
Readd the ability to see downloaded books of other users

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#1937] opened 2021-04-05 16:23 UTC
**Is your feature request related to a problem? Please describe.**
Previously, when you clicked on a user, you could see their downloaded books. This seems to have been removed for the sidebar menu item "Downloaded Books", but this category only contains books I myself downloaded.

**Describe the solution you'd like**
For an admin to have some way in the UI to see the books another user downloaded

**Describe alternatives you've considered**
Look through the DB, but this is really inconvenient

**Additional context**
While this might not be useful for users to see this data, it helps me as an admin to know which books a person downloaded,

**Comment by OzzieIsaacs** [comment] 2021-04-05 16:25
Duplicate of #1730 (I’m working on it)

**Closed** 2021-04-05 16:25 UTC
Labels: duplicate
