### ISSUE TITLE
Nginx Proxy issue

### ISSUE THREAD

**Issue by Fmstrat** [janeczku/calibre-web#523] opened 2018-06-14 17:56 UTC
Two items:

1) The nginx configuration in the README has some errors when used as-is. Right now, it's:

```
http {
    upstream calibre {
        server  127.0.0.1:8083;
    }
    server {
            location /calibre {
                proxy_bind              $server_addr;
                proxy_pass              http://127.0.0.1:8083;
                proxy_set_header        Host            $http_host;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Scheme        $scheme;
                proxy_set_header        X-Script-Name   /calibre;
        }
    }
}
```
But it should be:
```
http {
    upstream calibre {
        server  127.0.0.1:8083;
    }
    server {
            location /calibre {
                proxy_bind              $server_addr;
                proxy_pass              http://calibre;
                proxy_set_header        Host            $http_host;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Scheme        $scheme;
                proxy_set_header        X-Script-Name   /calibre;
        }
    }
}
```
Notice the `proxy_pass` line and it using the `upstream` name of `calibre`.

But, even with this change, there's a problem. If this is running on a non-standard port, Calibre-web is responding with headers that are causing nginx to redirect out. For instance:

```
        server {
                listen 12345;
                server_name HOST.DOMAIN.com;
                gzip off;
                ssl on;
                ssl_certificate /letsencrypt/live/DOMAIN.com/fullchain.pem;
                ssl_certificate_key /letsencrypt/live/DOMAIN.com/privkey.pem;
                ssl_session_cache shared:SSL:10m;
                ssl_protocols TLSv1.2;
                ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!3DES';
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

                location / {
                        proxy_pass http://127.0.0.1:8083;
                        proxy_set_header Host $http_host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-Host $server_name;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                        proxy_set_header X-Forwarded-Ssl on;
                }
        }
```
I've even tried the standard:
```
                        proxy_redirect https://HOST.DOMAIN.com/ https://HOST.DOMAIN.com:12345/;
```
To no avail.

**Comment by Fmstrat** [comment] 2018-06-14 18:03
I figured out that Calibre-web is adding "http://" to the beginning of the response, even if running behind a proxy. I had to use:

```
proxy_redirect http://HOST.DOMAIN.com/ https://HOST.DOMAIN.com:12345/;
```

To get things working. Is Calibre-web adding "http" vs leveraging headers?

**Comment by Fmstrat** [comment] 2018-06-14 19:06
You should also add:
```
client_max_body_size 20M;
```
To the sample configuration. Otherwise uploads won't work due to file size.

**Comment by OzzieIsaacs** [comment] 2018-07-07 11:42
I could not reproduce everything, but I have merged your PR (mostly)

**Closed by OzzieIsaacs** 2018-07-07 11:42 UTC
