### ISSUE TITLE
Send to Kindle - title from metadata, not from book

### ISSUE THREAD

**Issue by bonk1990** [janeczku/calibre-web#841] opened 2019-03-14 00:11 UTC
Hi,
first of all: great soft!

Is it possible to send converted mobi with metadata frmm database and not from file itself?

For example calibe saves meta to local files (not ebook itself) but if I sent the book to my device using the Send to device feature then metadata from db will be written to that file.

**Comment by OzzieIsaacs** [comment] 2019-03-14 06:58
Duplicate of #607

**Comment by bonk1990** [comment] 2019-03-14 07:39
I certainly do not want the metadata to change the original file in any way. Retail is what i want.

But mayby a workaround:
In E-Book converter settings a want to add:
`--read-metadata-from-opf=metadata.opf --mobi-file-type=both`

Could you help me with setting path to metadata.opf?
Is thera a way to make this universal?

**Comment by OzzieIsaacs** [comment] 2019-03-16 14:54
Currently this can't work. I've to implement something. Please give me some time to check

**Comment by bonk1990** [comment] 2019-03-16 22:44
I will wait, thanks!

**Comment by OzzieIsaacs** [comment] 2024-02-29 20:27
Metadata can now be embedded before sending to e reader

**Closed** 2024-07-06 12:22 UTC
Labels: enhancement, Fixed in Nightly
