### ISSUE TITLE
PDF cover Images inverted or incorrect single image grabbed from cover page

### ISSUE THREAD

**Issue by Stew-rt** [janeczku/calibre-web#1068] opened 2019-10-19 21:47 UTC
I'm getting a fair amount of cover grabbing failures across various PDF files.
Either:
* the image is grabbed with inverted colours
* An image from the cover is grabbed

Looking at the code, it looks like it grabs the first image from the first page of the `PdfFileReader` object.

the Calibre desktop app appears to get PDF covers using shell execution of `pdftoppm`

I've also found a possible alternative in the python module, pdf2image (which uses poppler)

If I find time, I'll see if I can knock together something as a POC.
Would you be open to a PR using either of these methods?

**Comment by OzzieIsaacs** [comment] 2019-10-20 13:53
Could you please send me an example of a non working pdf via privatemessage (e-mail adress on my profile page). I'd like to check what causes the problem, if the problem is not solvable with the current lib we can change it to something different.

**Comment by OzzieIsaacs** [comment] 2019-10-21 17:35
I got the files, and can confirm the problems.
- I was able to solve the inverted cover one (the picture has a CMYK color palette which wasn't handled properly)
- The only partly taken picture is caused by several objects forming the cover picture, which is currently also not handled properly
- The to big picture is some sort of "the cover is only part of the picture", which is currently also not properly handled.
I'll work on it.

**Comment by Stew-rt** [comment] 2019-10-21 17:49
:+1: Wonderful

**Comment by OzzieIsaacs** [comment] 2019-10-22 17:12
The picture part extraction is now working

**Comment by OzzieIsaacs** [comment] 2019-10-24 10:22
with the last example, You got me now. It looks like the position of the pictures on the page is not extracted by pypdf2. But I‘m more a fan of a pure python solution like minecart

**Comment by Stew-rt** [comment] 2019-10-24 11:16
I think given you've managed to resolve the other 2, an upstream issue to pypdf2 would be the best course of action.

**Comment by OzzieIsaacs** [comment] 2019-10-24 18:25
Sounds easier than it is. Pypdf2 last merged commit is from august 2018, there is a new repro called pypdf4. It's supposed to be the successor of pypdf2, all work will start there in August 2018, the latest commit there is 4 month ago. Looks to my the development stalled.
For minecart or the underlying pdfminer, there is at least an active community at the pdfminer.six repro. I'll check how much effort it will generate and how big the gain will be.

**Comment by Stew-rt** [comment] 2019-10-25 08:13
I imagine a longer-term plan to migrate to a different PDF library would be wise then. pdfminer sounds like a good shout.

**Closed** 2019-11-03 09:50 UTC
Labels: bug

**Comment by OzzieIsaacs** [comment] 2019-11-03 09:52
Finially I got it. I did a very stupid mistake half a year ago. There is already a very good extraction function inside calibre-web -> "Imagemagick".  I re-enabled it and now all books are extracted perfect. No need to change anything, everything is compatible to the old version and working now.
Thanks for pointing me towards it.
