### ISSUE TITLE
Continuous Reading for ePub

### ISSUE THREAD

**Issue by Cloud500** [janeczku/calibre-web#1837] opened 2021-01-28 12:25 UTC
The possibility to activate continuous reading for ePub.
I've searched a lot but haven't found anything related, hope I haven't overlooked anything ...

epub.js seems to have the function:
https://github.com/futurepress/epub.js/#continuous

I tried to test it by edit the epub.min.js and reader.min.js but without success
(I don't know enough about JavaScript to really expect a success ...)

It would be nice to have this option because it is so much more pleasant to read on browsers. IMOH

With best regards
Cloud500

PS: Supported by Google translator ;-)

**Comment by ashtonx** [comment] 2021-04-05 14:50
Ah indeed seems like there's bunch of options. Though there's no configuration on the reader from what I've seen.
I'm guessing it'd need to be configured in calibre-web ui settings, though i didn't see such option. I'm guessing it should be easy mod for personal use, though it'll also most likely be overwritten once calibre-web gets updated.

**Comment by OzzieIsaacs** [comment] 2021-04-05 14:56
Currently this option is not implemented in calibre-web

**Comment by OzzieIsaacs** [comment] 2021-04-06 17:21
Duplicate of #732

**Closed** 2023-03-01 19:13 UTC
Labels: duplicate
