### ISSUE TITLE
Metadata Search and Image issues

### ISSUE THREAD

**Issue by warmstarter** [janeczku/calibre-web#2657] opened 2023-01-15 11:22 UTC
**Describe the bug/problem**
Metadata search and cover image loading problems.

**To Reproduce**
1. Fetch Metadata, this will often show with broken image links.
2. Select the right option for the book, normal metadata loads in, but cover shows broken link.
3. Save and the cover appears just fine.
4. Go back to this book (or pretty much any), and try Fetch Metadata again, and it errors on the search.
5. Restart Calibre and try step 4 again, and it works just fine (though issues in 1-3 still there)

**Logfile**
Error mentioned in 4 for the book I just got the metadata for:
```
[2023-01-15 11:12:37,095] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=An+Illustrated+Encyclopaedia+of+Traditional+Symbols&i=digital-text&sprefix=An+Illustrated+Encyclopaedia+of+Traditional+Symbols%2Cdigital-text&ref=nb_sb_noss
[2023-01-15 11:12:37,373] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/calibreweb/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
```
Error mentioned in 4 for a different book (seems identical):

```
[2023-01-15 11:14:08,959] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=Signs+and+symbols+:+their+design+and+meaning&i=digital-text&sprefix=Signs+and+symbols+:+their+design+and+meaning%2Cdigital-text&ref=nb_sb_noss
[2023-01-15 11:14:09,440] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/calibreweb/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
```
With the first, this just succeeded. Other parts of this issue are producing no error message.

**Expected behavior**
Thumbnail should show up when searching for metadata.
Image should show up after selecting metadata.
Searches for the metadata beyond the first should not break requiring a restart.

**Screenshots**
![Step 1 Screenshot](https://user-images.githubusercontent.com/79870389/212537615-8c768fb1-4a1a-455d-8952-31c74093eda5.png)
![Step 2 Screenshot](https://user-images.githubusercontent.com/79870389/212537616-bd6dbec1-a734-4b6c-9bb0-46f877e5d75b.png)
![Step 3 Screenshot](https://user-images.githubusercontent.com/79870389/212537617-d721505a-6008-4b2c-b0f6-6f6e21c743bf.png)
![Step 4 Screenshot](https://user-images.githubusercontent.com/79870389/212537618-5b787b26-36a5-48c2-b417-f2803cf76bd6.png)

**Environment (please complete the following information):**
 - OS: [Debian 11 Bullseye]
 - Python version: [Python 3.9]
 - Calibre-Web version: [12/27/22 Current Version]:
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [AWS EC2]
 - Browser: [Chrome Version 109.0.5414.41 (Official Build)]

**Additional context**
Nginx in front of the cps server, but very straight-forward, and was no issues before the latest update.

**Comment by warmstarter** [comment] 2023-01-17 16:35
Here's another example error. Same Python issue, but with extra amazon search errors before, not just 503, but 404s and 503s, and why is it searching for Himalayan Moisturizer?

```
[2023-01-17 16:30:39,504]  WARN {cps.metadata_provider.amazon:65} 404 Client Error: Not Found for url: https://www.amazon.com/https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fs%3Fk%3DEleogap%3A%2BThe%2BSpirit%2Bof%2Bthe%2BWaters%26i%3Ddigital-text%26sprefix%3DEleogap%3A%2BThe%2BSpirit%2Bof%2Bthe%2BWaters%252Cdigital-text%26ref%3Dnb_sb_noss&marketPlaceId=ATVPDKIKX0DER&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select
[2023-01-17 16:30:39,539]  WARN {cps.metadata_provider.amazon:65} 404 Client Error: Not Found for url: https://www.amazon.com/https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fs%3Fk%3DEleogap%3A%2BThe%2BSpirit%2Bof%2Bthe%2BWaters%26i%3Ddigital-text%26sprefix%3DEleogap%3A%2BThe%2BSpirit%2Bof%2Bthe%2BWaters%252Cdigital-text%26ref%3Dnb_sb_noss&marketPlaceId=ATVPDKIKX0DER&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select
[2023-01-17 16:30:39,541]  WARN {cps.metadata_provider.amazon:65} 503 Server Error: Service Unavailable for url: https://www.amazon.com//EcoSmart-ECO-11-Modulating-Technology/dp/B001LZRF9M/ref=sr_1_2?keywords=Eleogap%3A+The+Spirit+of+the+Waters&qid=1673973038&s=digital-text&sprefix=Eleogap%3A+The+Spirit+of+the+Waters%2Cdigital-text&sr=1-2-catcorr
[2023-01-17 16:30:39,550]  WARN {cps.metadata_provider.amazon:65} 503 Server Error: Service Unavailable for url: https://www.amazon.com//Majestic-Pure-Himalayan-Essential-Moisturize/dp/B01K8PEZMU/ref=sr_1_4?keywords=Eleogap%3A+The+Spirit+of+the+Waters&qid=1673973038&s=digital-text&sprefix=Eleogap%3A+The+Spirit+of+the+Waters%2Cdigital-text&sr=1-4-catcorr
[2023-01-17 16:30:49,485] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=jake_Stratton-Kent_-_Serpent_Tongue&i=digital-text&sprefix=jake_Stratton-Kent_-_Serpent_Tongue%2Cdigital-text&ref=nb_sb_noss
[2023-01-17 16:30:49,914] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/calibreweb/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
```

Again, restarting the server and it works just fine, but having to restart after every attempt to get metadata really kills usability.

**Comment by warmstarter** [comment] 2023-01-17 16:38
Here is with DEBUG turned on, but little different, just the last line giving version:

```[2023-01-17 16:37:01,281] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=jake_Stratton-Kent_-_Serpent_Tongue&i=digital-text&sprefix=jake_Stratton-Kent_-_Serpent_Tongue%2Cdigital-text&ref=nb_sb_noss
[2023-01-17 16:37:03,508] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/admin/.virtualenvs/calibre-web/lib/python3.9/site-packages/calibreweb/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
[2023-01-17 16:37:12,913] DEBUG {cps.updater:323} Nightly version: ce0b3d8d103f72a3bea4b6019992aaa49613d4b9, 2022-12-27T09:13:15+01:00```

**Comment by warmstarter** [comment] 2023-01-17 16:59
Potentially fixed in the latest nightly, testing currently.

**Comment by warmstarter** [comment] 2023-01-17 17:12
Looks like mostly fixed in nightly. Still giving broken links for cover images in search, but not longer have to restart after each search.

**Comment by OzzieIsaacs** [comment] 2023-01-22 07:05
Please update to the newest nightly version (from right now), the issue should now hopefully fixed (or at least improved a lot). 
The problem is related to parsing metadata from amazon, in case of an parsing error the wrong value was returned. 
`503 Server Error: Service Unavailable for url`
Remark: Amazon has a very strict spam blocking, so if you perform to much search requests in a short time, the server returns an error instead of a valid response.

**Comment by warmstarter** [comment] 2023-01-22 18:45
Initial check and this is looking a lot better. Cover images now appear in a metadata search.

I noted 5 days ago that the latest nightly seemed to fix the 503, and it *did* for the most part, but I did have it crop up again once or twice, just not every time.

It is up to you if you wish to close this and consider it fixed, or give me maybe a week to feel it out with more uploads, and see if it crops up in some edge case.

**Comment by OzzieIsaacs** [comment] 2023-01-22 18:47
I‘ll wait and close the issue with the next release

**Closed** 2023-03-27 18:43 UTC
Labels: bug, Fixed in Nightly

**Comment by ant1fr** [comment] 2024-08-13 16:11
Calibre-web v0.6.23 (docker) here and having 503 each time I tried to retrieve metadata from Amazon. Is the fix only available on nightly builds since Jan 2023 and not on stable builds?

**Comment by MathijsG** [comment] 2024-08-18 16:17
Same problem. I get "[2024-08-18 16:03:54,260] ERROR {cps.metadata_provider.amazon:127} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=getting+things&i=digital-text&sprefix=getting+things%2Cdigital-text&ref=nb_sb_noss
" in the logs.
