### ISSUE TITLE
Feature: Auto-add Books to library from a watch folder

### ISSUE THREAD

**Issue by yabdali** [janeczku/calibre-web#412] opened 2017-12-12 15:53 UTC
Hi,

I use LazyLibrarian along with Transmission to download books into a folder.  I would like to have Calibre-Web to watch for any new files added to the folder "drop/watch" and automatically add it to my Library.  Is this available, can I run a scheduled task?

**Comment by OzzieIsaacs** [comment] 2017-12-12 16:26
This is a duplicate of #344.
I still recommend using a shell script for doing so. The project supports calibre librarys nothing else.
```
if [ "$(ls -A /[autoaddfolder])" ]; then
     calibredb add -r "/[autoaddfolder]" --library-path="/[calibrelibraryfolder]"
     rm /[autoaddfolder]/*
fi
```
And call this script frequently via cron job.

**Closed by OzzieIsaacs** 2017-12-12 16:26 UTC
Labels: duplicate, wontfix
