### ISSUE TITLE
Error when executing advanced search

### ISSUE THREAD

**Issue by Schmidtze2** [janeczku/calibre-web#1839] opened 2021-01-29 09:44 UTC
Hi,

when executing an advanced search, I get this ('list' object has no attribute 'strip'):

```
Internal Server Error
'list' object has no attribute 'strip'
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/calibre-web/app/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/calibre-web/app/cps/web.py", line 728, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/calibre-web/app/cps/web.py", line 419, in render_books_list
return render_adv_search_results(term, offset, order, config.config_books_per_page)
File "/calibre-web/app/cps/web.py", line 1022, in render_adv_search_results
author_name = author_name.strip().lower().replace(',', '|')
AttributeError: 'list' object has no attribute 'strip'

```
Best regards
Friedemann

**Comment by OzzieIsaacs** [comment] 2021-01-29 10:43
Last time we got to the point #1818, that it could be related to python version or dependency versions. 
If you could send me the debug_package from the admin page (via email) I can have a look at it and solve it for everyone, or:
You start an update of your python version, update all dependencies (which ismost probalbly the cause) and we close this one

**Comment by Schmidtze2** [comment] 2021-01-30 00:58
Hi,

thanks for answering :-) 

I attached the debug package:
[Calibre-Web-debug-pack.zip](https://github.com/janeczku/calibre-web/files/5897077/Calibre-Web-debug-pack.zip)

I also try to update the python package, but I'm using a docker image and I'm not sure by now if I get it working ;-)

Best regards
Friedemann

**Comment by Schmidtze2** [comment] 2021-01-30 01:18
Ah, I see, it's Alpine Linux in the Docker image and I used

  `apk update`
  `apk upgrade`

and a lot of packages have been upgraded, also Python 2 and Python 3. But the problem still exists... Do I miss something maybe?

Best regards
Friedemann

**Comment by Schmidtze2** [comment] 2021-01-30 01:37
Still Python 2.7 is used, should it be 3.0 maybe? If so, how can I change it?

I changed it now with an entry "alias python=python3" in .bashrc, and on the console Python 3 is used now. But Calibre Web still uses 2.7...

Best regards
Friedemann

**Comment by Schmidtze2** [comment] 2021-01-30 01:54
Now it works, I removed the symbolic link for Python and recreated it for Python 3 :-)

I'm not a Linux expert, taht's why it took some time to search for what I have to do...

The issue can be closed now...

Thank you so much and best regards
Friedemann

**Comment by OzzieIsaacs** [comment] 2021-01-30 09:43
Thanks for the information
I played a bit around with the versions of the dependencies, but I don't want to spend to much time on a python2 related bug.
I'll close the issue

**Comment by OzzieIsaacs** [comment] 2021-01-30 09:43
Sorry: I could not reproduce the problem, for me it was always working

**Closed by OzzieIsaacs** 2021-01-30 09:43 UTC
Labels: duplicate
