### ISSUE TITLE
send to kindle: stuck in endless loop

### ISSUE THREAD

**Issue by n0valis** [janeczku/calibre-web#75] opened 2016-12-02 11:23 UTC
It just keeps loading. no logs, then I have to restart the server. then I thought it could be something wrong with the email configuration, but no way to test that....think you need to add a test button there...

**Comment by OzzieIsaacs** [comment] 2016-12-02 11:31
Last time i checked it, it worked. 
You have to be aware that the page is reloaded after the e-mail is send, so depending on booksize and connection bandwith this can take some time. 
How long did you wait before restarting? How big is the book, and what is your upload speed?

Nonetheless a test-button and sending in background with progressbar seem to be a good idea.

**Comment by n0valis** [comment] 2016-12-02 13:00
I waited long enough ;) several times. Somerhing between 5 and 15 minutes. It is not an issue outside from the app. Maybe the newest kindlegen.exe has changed something?
As I said if something's wrong with the email youbwon't know. Can I check somehow if the process of conversion has worked properly? Can I find the converted file somewhere?

**Comment by OzzieIsaacs** [comment] 2016-12-02 13:04
Ok. The converted file should be located in the same folder as the original one.
I'm busy the next two weeks, I can try to take a look afterwards

**Comment by n0valis** [comment] 2016-12-02 18:10
ok, I found the file, so it seems that the problem is somewhere in the email department.
I have tested the smpt config in serveral combinations, with ssl, whithout, with StartTls and witgout. Nothing seems to work.
Since I don't have a Kindle yet I have used my standard email to test it. That should be no problem right?

**Comment by OzzieIsaacs** [comment] 2016-12-02 18:13
Yes, every emailadress should work. Could you please tell me the "emailprovider" (e.g. Google), maybe there are special requirements for logging in, which we currently not supporting.

**Comment by n0valis** [comment] 2016-12-02 18:41
domainfactory, I have tried multiple configs.
here is the page, in german tho
https://www.df.eu/int/support/df-faq/e-mail/pop3-imap-postfaecher/mail-programme/

**Comment by n0valis** [comment] 2016-12-02 18:46
I have just tried another conversion and it got caught in the "please wait" loop.
But I got an error msg in the log thus time:
[2016-12-02 19:12:17,028] {C:\calibre-web\cps\helper.py:61} ERROR - make_mobi: kindlegen failed with error while converting book

No reaction from the webserver after that, I have to kill and restart.

**Comment by OzzieIsaacs** [comment] 2016-12-23 09:02
I give it a 30% chance that it is fixed now.
You now have a list showning the installed dependencies on the "about" page, so you can see if kindlegen is recocnized correct.
In edit mail settings there is now a button send test e-mail.
If you set DEVELOPMENT=1 in the config.ini file you should see debug infos during sending e-mails and converting ebooks.
During development of the fix I had a similar problem, which was caused by failed conversion of kindlegen. For I reason I don't understand, kindlegen than didn't end it's process which caused the server to wait forever. If the problem still exisists, please post the output of the calibre-web.log. 
(Please be carefull that you don't post convidential informations accidentially)

**Closed** 2017-01-22 05:42 UTC
