### ISSUE TITLE
Problem with GDrive Watch Metadata.bd

### ISSUE THREAD

**Issue by kelvinalfaro** [janeczku/calibre-web#1532] opened 2020-07-21 15:16 UTC
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
1. Enable Metadata.bd watch
2. Error 500

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/Technosoft2000/Linuxuser]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment] 2020-07-21 16:10
Duplicate of #1528

**Closed by OzzieIsaacs** 2020-07-21 16:10 UTC
Labels: duplicate

**Comment by maltokyo** [comment] 2020-09-27 11:28
I have the same issue. Would you have any advice on how to make this work @OzzieIsaacs 
I have exactly the same setup as the original author here, and exactly the same problem.
