### ISSUE TITLE
Error 500 when try to enter in user information (Solved)

### ISSUE THREAD

**Issue by Wajalot** [janeczku/calibre-web#2601] opened 2022-11-15 10:22 UTC
When I try to open the user information to edit or whatever i find this error.

Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 991, in fetchall
rows = dbapi_cursor.fetchall()
sqlite3.DatabaseError: database disk image is malformed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 1422, in profile
languages = calibre_db.speaking_language()
File "/app/calibre-web/cps/db.py", line 930, in speaking_language
.group_by(text('books_languages_link.lang_code')).all()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2772, in all
return self._iter().all()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1464, in all
return self._allrows()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 401, in _allrows
rows = self._fetchall_impl()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1377, in _fetchall_impl
return self._real_result._fetchall_impl()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1800, in _fetchall_impl
return list(self.iterator)
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 147, in chunks
fetch = cursor._raw_all_rows()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 392, in _raw_all_rows
rows = self._fetchall_impl()
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1819, in _fetchall_impl
return self.cursor_strategy.fetchall(self, self.cursor)
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 995, in fetchall
self.handle_exception(result, dbapi_cursor, e)
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 955, in handle_exception
result.connection._handle_dbapi_exception(
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
raise exception
File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 991, in fetchall
rows = dbapi_cursor.fetchall()
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```
 - Calibre-Web version: 0.6.8
 - Docker container: Both, Synology and Debian 11 as VM, same error.

**Comment by OzzieIsaacs** [comment] 2022-11-15 10:47
Meanwhile SW version 0.6.19 (instead of 0.6.8) is released. The error points to a error in the calibre database. Please try to do a library maintenance in calibre itself, and please consider to update to the newest version (this will not solve the problem)

**Comment by Wajalot** [comment] 2022-11-15 10:49
Sorry, version is 0.6.19.

**Comment by OzzieIsaacs** [comment] 2022-11-15 12:10
Maybe a duplicate of #2388

**Comment by OzzieIsaacs** [comment] 2022-11-15 12:14
Could you please try to:
- stop calibre-web
-  backup the app.db, and delete the app.db in calibre-web folder
- start calibre-web again, configure it and try if the error is still there
-> If yes problem is indeed related to calibre metadata.db
-> If no  problem is indeed related to app.db

Depending on the result it would be needed that you send me the problematic file via private email and I have a look

**Comment by Wajalot** [comment] 2022-11-15 12:51
Solved! As you said it was the metadata.db file. I created a new one, clean, and everything works properly. Thanks,

**Comment by Wajalot** [comment] 2022-11-15 13:18
I add something as recomendation for other users: Stop Calibre-Web while Calibre is working adding books or modifing the metadata.db.

**Closed** 2022-12-05 12:32 UTC
