### ISSUE TITLE
Goodreads API - purpose?  does it pull from "Read" list

### ISSUE THREAD

**Issue by psyciknz** [janeczku/calibre-web#685] opened 2018-10-17 19:12 UTC
The goodreads API, what's it used for?

And does it update the metadata of a book, and/or set the read flag of the book?

**Comment by OzzieIsaacs** [comment] 2018-11-02 13:17
Duplicate of #560. I'm closing this one, feature can be tracked there

**Closed by OzzieIsaacs** 2018-11-02 13:17 UTC
Labels: question
