### ISSUE TITLE
Error 500 with write protected database

### ISSUE THREAD

**Issue by ElFerminador** [janeczku/calibre-web#2337] opened 2022-03-15 09:54 UTC
[calibre-web.log](https://github.com/janeczku/calibre-web/files/8252034/calibre-web.log)
**Describe the bug/problem**
I get an error 500 when clicking on an author link. It's not consistent, though - sometimes (and with some authors) it works, sometimes it doesn't.

**To Reproduce**
1. Log into the server.
2. Click on the author link on any book displayed on the first page (doesn't matter, actually, could also be from a search result or series list).
3. See error "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
4. The error is non-recoverable. I have to restart the docker container to get calibre-web up and running again.

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
When clicking on an author link of a book, it should show a list of all the author's books.

**Screenshots**
n/a

**Environment (please complete the following information):**
- OS: Linux 4.4.180+ #42218 SMP Fri Jan 7 15:31:20 CST 2022 x86_64 x86_64 (on Synology DSM 7.0.1-422218 Update 2)
- CPU architecture: x86_64 (Intel Xeon D-1527, Synology DS3617xsII NAS)
 - Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
 - Calibre-Web version: 0.6.17 - c53817859a0e46820a0a92bbd0697805f7e65445 - 2022-03-06T16:10:41+01:00
 - Docker container: LinuxServer
 - Special Hardware: Synology DS3617xsII
 - Browser: Any browser, for example Google Chrome and Safari on Mac OS, or the OPDS browser in mobile apps like Marvin3 on iOS.

**Additional context**
I'm mounting the directory with the library in read-only mode into the docker container. This used to not be an issue, I could always click on author links without crashing the application in the past. If I mount the library directory in rw mode, the crashes don't happen.

I'm using the docker image from linuxserver.io (https://github.com/linuxserver/docker-calibre-web), they closed my issue (https://github.com/linuxserver/docker-calibre-web/issues/181) saying that they only repackage the application.

**Comment by MinchinWeb** [comment] 2022-03-15 16:42
Is this a duplicate of https://github.com/janeczku/calibre-web/issues/2325 ?

Try upgrading (for now) to the nightly version (of the LinuxServer docker container), and see if that fixes it (it did for me).

**Comment by OzzieIsaacs** [comment] 2022-03-15 16:44
Yes, looks like the issue @MinchinWeb mentions

**Comment by ElFerminador** [comment] 2022-03-15 16:45
Hm, yes, looks like it could be a duplicate. Sorry, hadn't seen that. Any information on when the fix will make it into the "latest" release?

**Comment by ElFerminador** [comment] 2022-03-15 16:48
> Two weeks or so

Excellent, thank you. I'm just wondering if I really need to mount the database in **ro**. If I mounted it in **rw**, this would allow me to mark books as "read" and have that reflected in the Calibre app, right? The reason for mounting it ro only was to avoid corrupting the database. But if I'm being paranoid over nothing ... :-)

**Closed** 2022-03-17 20:13 UTC
Labels: duplicate
