### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' on current master

### ISSUE THREAD

**Issue by blitzmann** [janeczku/calibre-web#1670] opened 2020-10-19 02:01 UTC
**Describe the bug/problem**

Recently updated my personal branch to master, and am getting the following error: 

```
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\cps\web.py", line 201, in decorated_view
return login_required(func)(*args, **kwargs)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\cps\web.py", line 951, in index
return render_books_list("newest", sort_param, 1, page)
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\cps\web.py", line 622, in render_books_list
sort = current_user.get_view_property(data, 'stored')
File "C:\Users\holme\Documents\Sync\Git\blitzmann\calibre-web\cps\ub.py", line 199, in get_view_property
return self.view_settings[page].get(property)
AttributeError: 'str' object has no attribute 'get'
```

Looks like this commit caused it:
497fbdcdfc39856e7641d2ee91fe32ad40b5522c

**To Reproduce**
Checkout master and run. Going to the main page produces the error

**Expected behavior**
I shouldn't see a 500 error

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10
 - Python version: [e.g. python2.7] Python 3.6
 - Calibre-Web version: 497fbdcdfc39856e7641d2ee91fe32ad40b5522c
 - Docker container: None
 - Special Hardware: N/A
 - Browser: Chrome

**Comment by blitzmann** [comment] 2020-10-19 02:05
Hrm, nuking my `app.db` seems to fix the issue at the expense of losing all my configuration. Does the application not properly migrate the database if there's related changes?

Please advise

**Comment by blitzmann** [comment] 2020-10-19 02:16
Digging into it a bit more, here's what's stored as the users (`admin`) view settings:

![image](https://user-images.githubusercontent.com/3904767/96394064-17aad800-118f-11eb-8e26-b279c4316088.png)

But the code seems to expect the key `newest` to have a dictionary as the value, which is does not. 

here's the offending code with the relevant properties:

![image](https://user-images.githubusercontent.com/3904767/96394218-6bb5bc80-118f-11eb-8657-a48e7dc7e0ea.png)

So yeah it looks like there was some sort of database migration that was missed or overlooked. I don't know enough about that bit of the system to help put out a PR, but hopefully the above is enough info :D

**Comment by OzzieIsaacs** [comment] 2020-11-07 11:00
I checked it, I could not reproduce it and I don't see how it can happen in the current master. 
There is one thing I can think of: If you used the same app.db during the development on the develop branch, this is very likely. The code had some iterations on the development tree until it was stable and I don't check for compatibility on the development branch.
I'm closing the issue, and wait for somebody to post a "me, too"

**Closed by OzzieIsaacs** 2020-11-07 11:00 UTC
