### ISSUE TITLE
I Use IIS(windows server 2012R2) And i got the error message below.

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#180] opened 2017-04-15 23:27 UTC
I use IIS(windows server 2012R2).
I installed all requirements and optional-requirements with pip.

and I entered python cps.py. and then i got error messages below. please let me know what the problems are.

Traceback <most recent call last>:
  File "cps.py", line 29, in <module>
    web.start_gevent()
  File "C:\inetpub\wwwroot_abubakr\book_abuba_kr\cps\web.py", line 2753, in start_gevent
    gevent_server.serve_forever()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 360, in serve_forever
    self.start()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 304, in start
    self.init_socket()
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 1451, in init_socket
    StreamServer.init_socket(self)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 127, in init_socket
    self.socket = self.get-listener(self.address, self.backlog, self.family)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 138, in get_listener
    return _tcp_listener(addreess, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 228, in _tcp_listener
    sock.bine(address)
  File "<string>", line 1, in bine
socket.error: [Errno 10013] : ('', 8083)

**Comment by OzzieIsaacs** [comment] 2017-04-16 05:10
Could you please try to uninstall gevent (pip uninstall gevent). 
In this case tornado is used as webserver, this should work, as long as you don't want to use a library on a google drive

**Comment by abubaman** [comment] 2017-04-16 11:22
even though i uninstall gevent, i got new error message like below.
and then after i saw the error message below, i uninstall and re-install tornado, but it was same.

Traceback (most recent call last):
  File "cps.py", line 33, in (module)
    http_server.listen(web.ub.config.config_port_
  File "C:\Python27\lib\site-packages\tornado\tcpserver.py", line 126, in listen

    sockets = bind_sockets(port, address=adress)
  File "C:\Python27\lib\site-packages\tornado\netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10013]

**Comment by OzzieIsaacs** [comment] 2017-04-16 11:29
From the Microsoft support, tegarding error 10013:

A socket error 10013 can be caused by antivirus or firewall software. Basically, a needed socket connection is being denied. Socket error 10013 is a message which implies that a port is blocked and/or unreachable.
 
[...]
 
Let’s also disable antivirus software and Firewall together (as a test) on the computer temporarily and try connecting and check if things get any better.

Note: Make sure you turn-on the antivirus software and Windows Firewall later.
 
If disabling antivirus software works, then you'll need to configure the same so that it no longer interferes.
 
Hope this helps.
Gokul - Microsoft Support 

Could you please check that. Thanks

**Comment by abubaman** [comment] 2017-04-17 07:27
Thank you for your reply.

unfortunately, I dont use antivirus software.
So i turned off firewall. but, it shows same error.

i tried to re-config in-bound, out-bound rule, but i think it didnt help.

please tell me possible scenarios. thank you again.

**Comment by OzzieIsaacs** [comment] 2017-04-17 16:55
one possible reason could be that the port is used by another program (netstat -ban should list used ports, according to google)
Another possibility could be that the user which runs python cps.py is not allowed to open network connections, running it as administrator (run it in a cmd shell with administrator privileges) could solve the problem in this case. 

The error points to a problem outside calibre-web, with access problem to the network port

**Comment by OzzieIsaacs** [comment] 2017-05-25 08:52
Any news on this?

**Comment by abubaman** [comment] 2017-05-27 03:51
After I make IIS stop, i can access calibre-web in localhost. thanks.

but, when i tried to access to domain, i couldn't.
i want to use book.abuba.kr, and 80 port. i have to use sub domain 'book'
how can i setting with this.

**Comment by OzzieIsaacs** [comment] 2017-05-27 08:02
As calibre-web includes its own server and one one machine not 2 Programms can User the same port the first thing you have to change is the port calibre-web listens to (like default 8083). Than you have to set up a "reverse proxy" with your IIS server. 
Exampleconfigurations are are given for Ngnix and apache webserver in the readme, but not for IIS. and I'm sorry I have no idea how to configure IIS that way. You should please try searching on the web on your own. If you make it work I'm happy to include the configuration in our readme.

**Comment by OzzieIsaacs** [comment] 2017-05-27 08:02
Closing issue as this is not a bug in calibre-web

**Closed by OzzieIsaacs** 2017-05-27 08:02 UTC
