### ISSUE TITLE
Additional book metadata search engines?

### ISSUE THREAD

**Issue by rmzg** [janeczku/calibre-web#891] opened 2019-04-23 03:52 UTC
Are there any plans for adding additional metadata search engines or reasons why they couldn't be added?

**Comment by idalin** [comment] 2019-04-23 07:21
Amazon has been considered. But it needs a api key and signature. That's a little more complicated than Douban and Google. using a common key applied by developer or using a key appliey by every user themself?

**Comment by OzzieIsaacs** [comment] 2019-04-23 10:52
If I understand the amazon website correctly you need an AWS (Amazon Web Service Account) which has a monthly fee (it's currently only 0.03USD, and12 month free), but I think not anybody wants to pay for getting metadata once in a while

**Comment by OzzieIsaacs** [comment] 2019-04-23 11:43
Duplicate of #380

**Closed** 2019-11-04 11:15 UTC
