### ISSUE TITLE
auto-reconnect to database [Docker]

### ISSUE THREAD

**Issue by AndreasSchuette** [janeczku/calibre-web#727] opened 2018-12-19 07:55 UTC
I'm syncing my local calibre-database to calibre-web (docker on synology diskstation). Whenever i make any change localy (e.g. add books) the database is synced via resilio sync but calibre-web does not recognize changes. I have to click on reconnect-database in admin-panel to make calibre-web recognize those changes. Is there any posibility to automize that.

**Comment by OzzieIsaacs** [comment] 2018-12-23 12:31
May I ask which docker version you are using: the linuxserver one, or the technosoft2000 one?

**Comment by AndreasSchuette** [comment] 2018-12-23 15:16
Of course ... I'm using the technosoft2000 one! Unfortunately I cannot install calibre-web natively (without Docker) to perform any testing

**Comment by a575606** [comment] 2019-01-09 17:32
I am doing the same thing and have the same issue. I just click reconnect to database every time I use calibre web. Would be nice if it would just do that automatically on login or at intervals.

**Comment by wahlis** [comment] 2019-03-15 11:59
I thave he same issue with the locally installed version. 
My library is on a folder on a Linux server. That library is also read via a Samba share from a Windows 10 client where I run the Calibre app and add/update my books. 
Calibre Web runs behind an Apache reverse proxy.

After making changes I must manually reconnect to the db the see the changes.

**Comment by lighto-kun** [comment] 2021-12-07 14:50
Same issue here.
I'm using the calibre-web docker container from linuxserver on a Synology NAS (DSM 7.0).
It is setup for serving a calibre database located at the `/books` mount in read-only mode, i.e. docker container user has read-only access to the folder that is mounted into `/books` and any database modification features like upload/deletion etc. are disabled in calibre-web admin panel.
I edit the calibre database on my desktop PC using the official Calibre application, and the modified database is automatically synced to the NAS folder, that is mounted into `/books` in calibre-web container.
The issue is that a running calibre-web docker container does not detect/show any database modifications synced from PC to NAS until I either click the "Reconnect Calibre Database" in the calibre-web admin panel or restart the calibre-web docker container. 
Both current solutions require manual intervention by admin users, which is a bit tedious given that I use a separate non-admin accounts for regular use and have to log in as admin every time. It would be nice, if calibre-web could detect and reload the modified database automatically.

**Comment by OzzieIsaacs** [comment] 2022-05-01 08:57
There is a PR merged for doing a scheduled database reconnect:
- Please update to the newest nightly version
- Install APScheduler via pip
- Restart Calibre-Web
- Go into admin section enter edit schedule task settings, enable "Reconnect to Calibre Library", change the regular reconnect time if you want. Save the settings

Enjoy

**Comment by Yann-J** [comment] 2022-06-06 15:52
This looks good @OzzieIsaacs , but is there any reason why the public `/reconnect` API seems to  have been deprecated? It now returns a 404.

A built-in scheduling is great, and the most convenient for most users, but having the possibility to trigger it externally is also useful to have more control on it (e.g. after a book was imported in Calibre)... Right now the scheduling options are pretty limited (once a day)...

**Comment by OzzieIsaacs** [comment] 2022-06-06 15:53
It‘s now deactivated by default, there is a commandline option (-> wiki) to activate it.

**Comment by Yann-J** [comment] 2022-06-06 16:11
OK I see - [here](https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface) if anyone's looking for it.

Unfortunately cmd line args aren't easy to pass into containers 😅 ... any chance we could activate this with an env var instead? 🙏

**Comment by OzzieIsaacs** [comment] 2022-06-06 17:18
I new this would be asked…

**Comment by Tally** [comment] 2022-07-09 19:33
> Ah, got it, according to the code, `CALIBRE_RECONNECT` should do the trick!

I'm using the linuxserver image and having this difficulty. Could you be more explicit regarding how you use this environment variable to address it? Thanks.

**Comment by OzzieIsaacs** [comment] 2022-07-09 19:35
Just set it and the reconnect endpoint is enabled

**Closed** 2022-07-31 16:06 UTC
Labels: enhancement, Fixed in Nightly, Docker
