### ISSUE TITLE
Impossible to upload and to open books

### ISSUE THREAD

**Issue by zedred79** [janeczku/calibre-web#1192] opened 2020-02-11 09:33 UTC
After the last update to version 0.6.5-ls48 when I click on any book, the book details window remains empty, I cannot open the book, edit metadata, etc.

If I try to upload a book in calibre-web there are these errors:

Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):

```
File “/usr/local/lib/python3.6/dist-packages/flask/app.py”, line 2446, in wsgi_app
response = self.full_dispatch_request()
File “/usr/local/lib/python3.6/dist-packages/flask/app.py”, line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File “/usr/local/lib/python3.6/dist-packages/flask/app.py”, line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File “/usr/local/lib/python3.6/dist-packages/flask/_compat.py”, line 39, in reraise
raise value
File “/usr/local/lib/python3.6/dist-packages/flask/app.py”, line 1949, in full_dispatch_request
rv = self.dispatch_request()
File “/usr/local/lib/python3.6/dist-packages/flask/app.py”, line 1935, in dispatch_request
return self.view_functionsrule.endpoint
File “/app/calibre-web/cps/web.py”, line 166, in decorated_view
return login_required(func)(*args, **kwargs)
File “/usr/local/lib/python3.6/dist-packages/flask_login/utils.py”, line 272, in decorated_view
return func(*args, **kwargs)
File “/app/calibre-web/cps/web.py”, line 1471, in show_book
is_xhr=request.is_xhr, title=entries.title, books_shelfs=book_in_shelfs,
File “/usr/local/lib/python3.6/dist-packages/werkzeug/local.py”, line 347, in getattr
return getattr(self._get_current_object(), name)
AttributeError: ‘Request’ object has no attribute ‘is_xhr’
```

**Comment by CHBMB** [comment] 2020-02-11 10:04
I think this is due to a change in these packages:

- `Flask_Login` = `0.4.1` to `0.5.0`
- `Werkzeug` = `0.16.1` to `1.0.0`

See the issue on our container here:

https://github.com/linuxserver/docker-calibre-web/issues/61

**Comment by OzzieIsaacs** [comment] 2020-02-11 10:20
Duplicate of #1181.

**Comment by CHBMB** [comment] 2020-02-11 10:25
@OzzieIsaacs Yep, I've just built our container with the previous version of `Werkzeug` and it works fine.  However as we use your releases rather than clone from master I'll have to pin the version until you push a new release. Thanks!

**Comment by OzzieIsaacs** [comment] 2020-02-25 15:27
Release 0.6.6 is out, which fixes the problem.

**Closed by OzzieIsaacs** 2020-02-25 15:27 UTC
Labels: duplicate
