### ISSUE TITLE
Calibre-web crashes if author is repeated twice

### ISSUE THREAD

**Issue by LivingWithHippos** [janeczku/calibre-web#1513] opened 2020-06-30 14:20 UTC
**Describe the bug/problem**
Uploading a certain ebook crashed my calibre-web server. The uplod bar filled up and then became red with the text `<!DOCTYPE html> <html class="http-error" lang="en"> <head> <title>Calibre-Web | HTTP Error (Internal...`

Reloading the page will result in an error page `500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.` with the trace reported below.

Restarting the docker container fixes it (book still not uploaded). Other books get uploaded fine.

I tried to edit its metadata before uploading, and I noticed it worked if I changed the author name. In the Author field the name was `AuthorX & Author` where X is my edit.
After changing various occurrences the problem was from this lines in content.opf

`    <dc:creator opf:file-as="Author, My." opf:role="aut">My Author</dc:creator>`
`<dc:creator opf:role="aut">My Author</dc:creator>`

Removing the second line worked, too

I've seen you mention in #1053 a similar issue, it probably is the same.

**To Reproduce**
1. change the two lines in content.opf to be the same 
2. Upload the book
3. ????
4. Profit

**Logfile**

calibre-web.log

```
[2020-06-30 14:41:45,267]  INFO {cps:98} Starting Calibre Web...
[2020-06-30 14:41:45,434]  INFO {cps.server:156} Starting Tornado server on :8083
[2020-06-30 14:42:05,956] ERROR {cps:1892} Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1264, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 587, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: books_authors_link.book, books_authors_link.author

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 201, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 273, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/editbooks.py", line 818, in upload
    calibre_db.session.flush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 540, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/dependency.py", line 1177, in process_saves
    uowcommit, secondary_insert, secondary_update, secondary_delete
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/dependency.py", line 1239, in _run_crud
    connection.execute(statement, secondary_insert)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1264, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 587, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: books_authors_link.book, books_authors_link.author
[SQL: INSERT INTO books_authors_link (book, author) VALUES (?, ?)]
[parameters: ((287, 98), (287, 98))]
(Background on this error at: http://sqlalche.me/e/gkpj)
[2020-06-30 14:42:21,450] ERROR {cps:1892} Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 201, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 623, in index
    entries, random, pagination = calibre_db.fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/app/calibre-web/cps/db.py", line 511, in fill_indexpage
    return self.fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
  File "/app/calibre-web/cps/db.py", line 527, in fill_indexpage_with_archived_books
    len(query.all()))
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3319, in all
    return list(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3503, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3518, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3496, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 296, in _assert_active
    code="7s2a",
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: books_authors_link.book, books_authors_link.author
[SQL: INSERT INTO books_authors_link (book, author) VALUES (?, ?)]
[parameters: ((287, 98), (287, 98))]
(Background on this error at: http://sqlalche.me/e/gkpj) (Background on this error at: http://sqlalche.me/e/7s2a)
[2020-06-30 14:42:29,733]  INFO {cps.server:207} webserver stop (restart=False)
[2020-06-30 14:42:29,735]  INFO {cps.server:184} Performing shutdown of Calibre-Web
[2020-06-30 14:42:38,173]  INFO {cps:98} Starting Calibre Web...
[2020-06-30 14:42:38,322]  INFO {cps.server:156} Starting Tornado server on :8083
```

**Expected behavior**
One of the two lines get ignored maybe? To be honest I think this is a malformed ebook issue, but maybe calibre web shouldn't stop working and just refuse the upload.

**Environment (please complete the following information):**
 - OS: ubuntu 20
 - Calibre-Web version: 0.6.8
 - Docker container: linuxserver.io
 - Browser: firefox latest

**Additional context**
access via reverse proxy -> nginx

**Comment by OzzieIsaacs** [comment] 2020-06-30 17:15
Thank you for the detailed report. I think my idea regarding 1053 was not the same, I found this bug one or 2 weeks ago.
It should be already fixed in the newest master commit (you could change updater to nightly and update to it). The code now searches through all authors/tags/languages, ... and removes duplicate entries. You could also create this issue if you edit books and change author to: author name & author name (but no need to try it)

**Comment by LivingWithHippos** [comment] 2020-06-30 17:29
Yeah the issue is different my bad, what I meant is in the last message you mention about having unknown & Unknown as author name as a problem

**Comment by OzzieIsaacs** [comment] 2020-06-30 17:32
Okay, I currently think end of July/beginning of August we might get a new version out

**Comment by OzzieIsaacs** [comment] 2024-08-15 17:06
The issue is fixed meanwhile (can't remember when)

**Closed by OzzieIsaacs** 2024-08-15 17:06 UTC
Labels: bug
