### ISSUE TITLE
Where is the "Read in browser" button?

### ISSUE THREAD

**Issue by XiovV** [janeczku/calibre-web#1231] opened 2020-02-27 15:02 UTC
**To Reproduce**

1. Click on a book

**Expected behavior**
To see a "Read in browser" button next to the Download button

**Environment (please complete the following information):**
 - OS: Ubutnu Server 19.10
 - Python version: 2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]
 - Calibre-Web version: 0.6.7 Beta
 - Docker container:Technosoft2000
 - Browser: Firefox and Chromium

**Comment by OzzieIsaacs** [comment] 2020-02-27 19:40
Please check if eBook viewer is activated for the user in admin -> edit user section:
![grafik](https://user-images.githubusercontent.com/6438895/75479740-50980180-59a0-11ea-9dff-fd9d156e8222.png)
The integrated eBook viewer is available for pdf, epub, txt and cbr, cbz and cbt files. Is eBook in ne of the named formats?

**Comment by XiovV** [comment] 2020-02-27 20:08
@OzzieIsaacs the button is showing now but I'm getting this error: 
`PDF.js v2.2.228 (build: d7afb74a)
Message: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".`

**Comment by OzzieIsaacs** [comment] 2020-02-27 20:09
Duplicate of #1223

**Closed** 2020-03-02 20:29 UTC
Labels: duplicate
