### ISSUE TITLE
LDAP Login - No stable login procedure

### ISSUE THREAD

**Issue by leckmirdienuss** [janeczku/calibre-web#1567] opened 2020-08-13 07:49 UTC
**Describe the bug/problem**
Got LDAP working. User import works too. But if i want to login as an LDAP Users, it only works after 3 or more trys. The logs seems to be not helpful.

**Logfile**
```
2020-08-13 09:11:12,021] DEBUG {cps.services.simpleldap:96} LDAP login 'Achim Menzel': None
[2020-08-13 09:11:12,021]  INFO {cps.web:1413} LDAP Login failed for user "Achim Menzel" IP-adress: 172.16.5.88
[2020-08-13 09:11:14,359] DEBUG {cps.services.simpleldap:96} LDAP login 'Achim Menzel': None
[2020-08-13 09:11:14,360]  INFO {cps.web:1413} LDAP Login failed for user "Achim Menzel" IP-adress: 172.16.5.88
[2020-08-13 09:11:16,524] DEBUG {cps.services.simpleldap:96} LDAP login 'Achim Menzel': True
[2020-08-13 09:11:16,524] DEBUG {cps.web:1396} You are now logged in as: 'Achim Menzel'
[2020-08-13 09:12:04,731] DEBUG {cps.web:1456} User logged out
[2020-08-13 09:12:21,900] DEBUG {cps.services.simpleldap:96} LDAP login 'Marco NachName': None
[2020-08-13 09:12:21,900]  INFO {cps.web:1413} LDAP Login failed for user "Marco NachName" IP-adress: 172.16.5.88
[2020-08-13 09:12:40,247] DEBUG {cps.services.simpleldap:96} LDAP login 'Marco NachName': None
[2020-08-13 09:12:40,247]  INFO {cps.web:1413} LDAP Login failed for user "Marco NachName" IP-adress: 172.16.5.88
[2020-08-13 09:12:49,524] DEBUG {cps.services.simpleldap:96} LDAP login 'Marco NachName': None
[2020-08-13 09:12:49,524]  INFO {cps.web:1413} LDAP Login failed for user "Marco NachName" IP-adress: 172.16.5.88
[2020-08-13 09:12:53,193] DEBUG {cps.services.simpleldap:96} LDAP login 'Marco NachName': None
[2020-08-13 09:12:53,194]  INFO {cps.web:1413} LDAP Login failed for user "Marco NachName" IP-adress: 172.16.5.88
[2020-08-13 09:12:56,925] DEBUG {cps.services.simpleldap:96} LDAP login 'Marco NachName': True
[2020-08-13 09:12:56,925] DEBUG {cps.web:1396} You are now logged in as: 'Marco NachName'
```

Programm Bibliothek | Installierte Version
0.6.8

**Comment by CHBMB** [comment] 2020-08-24 19:20
I've been using LDAP as a backend for quite a while and it's been rock solid stable, so I feel I can confidently suggest there isn't an inherent calibre-web issue.

I'm using openldap run as a docker image osixia/openldap

**Comment by OzzieIsaacs** [comment] 2020-09-01 17:42
I'm testing the login procedure regularly and never had an issue like that. 
Calibre-Web sends a request for getting user details this looks like it worked every time in your case (otherwise the debug message would be different from LDAP login).
Then it tries to "bind the user"  -> verify the password for the user. In your case this second request seems to fail. My guess would be that there is some timing issue, rate limiting (??) on your LDAP server. 
The LDAP library I use offers no logging possibility. I opened an issue to fix this: https://github.com/alexferl/flask-simpleldap/issues/78, but have no feedback so far. Maybe you can try to apply the patch I suggested in the library (you will then get a lot of output)

Why am I doing this?
I think I do this for the fallback login to determine if the user is valid in LDAP and only the password is wrong -> no fallback login. If username not valid in LDAP -> try fallback login

**Comment by OzzieIsaacs** [comment] 2020-09-01 17:47
You could try to change the file /service/simpleldap.py from:
```
        if _ldap.get_object_details(username):
            result = _ldap.bind_user(username, password)
            log.debug("LDAP login '%s': %r", username, result)
            return result is not None, None
        return None, None       # User not found
```
to
```
        result = _ldap.bind_user(username, password)
        log.debug("LDAP login '%s': %r", username, result)
        return result is not None, None
```
(The spaces, tabs at the beginning are important). 

My regards to Achim Mentzel

**Comment by OzzieIsaacs** [comment] 2020-10-10 09:02
As It's mpt reproducable to me, I'm closing the issue

**Closed by OzzieIsaacs** 2020-10-10 09:02 UTC
Labels: question
