### ISSUE TITLE
Multiple calibre web libraries

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#1481] opened 2020-06-09 21:38 UTC
Many people have more than one library. Currently you can only have one in calibre web. You could use more than one library and be able to switch between them.

**Comment by flying-sausages** [comment] 2020-06-11 17:42
Dupe of #1445 ?

**Comment by OzzieIsaacs** [comment] 2020-06-12 15:52
Yes, it's a duplicate.
And I'm not going to implement it, as I mentioned several times:
https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-handle-multiple-calibre-libs

**Closed by OzzieIsaacs** 2020-06-12 15:52 UTC
