### ISSUE TITLE
Several errors (major and minor)

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#1671] opened 2020-10-19 15:26 UTC
Describe the bug/problem:

1 - When you start the program, the default setting ( 60 books per page ) appears, but there are large gaps between the covers. 

![1](https://user-images.githubusercontent.com/65027248/96470441-9440c380-122e-11eb-8c15-3b8faf3d9430.png)

![2](https://user-images.githubusercontent.com/65027248/96470464-99057780-122e-11eb-8dc7-166e3b93c459.png)

2 - Small errors in the Spanish translation ( Downloaded Books - Books List )

![traduccion](https://user-images.githubusercontent.com/65027248/96470770-ec77c580-122e-11eb-853b-756d5bf3c823.png)

3 - Error in Gevent ( ssl not active )

![gevent1](https://user-images.githubusercontent.com/65027248/96471000-2a74e980-122f-11eb-943c-49b6b69dcd50.png)

4 - Error en Gevent - Greenlet ( SSL active - External https access without problems )

![ssl1](https://user-images.githubusercontent.com/65027248/96471437-a2dbaa80-122f-11eb-80ec-2dc7786d9760.png)

![ssl2](https://user-images.githubusercontent.com/65027248/96471460-aa9b4f00-122f-11eb-90bc-6c492a26af37.png)

System: Linux Mint 20, Calibre-web Master 0.6.10 Beta ( Installed on 19/10/2020 )

![system](https://user-images.githubusercontent.com/65027248/96472015-42993880-1230-11eb-9cad-21fc895ecebd.png)

**Comment by yeraycito** [comment] 2020-10-19 19:04
I have created an entry with the problems in gevent:

https://github.com/gevent/gevent/issues/1688

**Comment by OzzieIsaacs** [comment] 2020-10-20 15:37
1) There is a PR addressing this issue on the way: #1667
2) You are free to provide additional translations: https://github.com/janeczku/calibre-web/blob/master/cps/translations/es/LC_MESSAGES/messages.po
3) There is something in the background requesting the port of calibre-web. Let me guess: Bittorrent?
4) I also created a issue in gevent: https://github.com/gevent/gevent/issues/1671. I can't exactly remember the root case, I think it was some caching problem with the browsers.
I could not reproduce the OSERROR, which is also mentioned in several questions. I will add the OS_ERROR to the catched erros, it will then also output an WARN message

**Comment by OzzieIsaacs** [comment] 2020-11-22 07:47
The PR is merged to master branch, please update

**Closed by OzzieIsaacs** 2020-11-22 07:47 UTC
