### ISSUE TITLE
Login issue through HAProxy

### ISSUE THREAD

**Issue by SCUZNUTS** [janeczku/calibre-web#465] opened 2018-03-14 02:06 UTC
Odd issue;

Admin > Config > anonymous browsing 'off'
Visit https://calibre.blah.com/
- Fails to load, spins around - The page cannot be displayed
- The URL does try redirect to https://calibre.blah.com/login?next=%2F

Admin > Config > anonymous browsing 'on'.
Admin > Config > public registration 'on' (To get the login button).
Visit https://calibre.blah.com/
- Loads fine

Click 'Login'
- Loads fine

Login with account info, hit submit
- Fails to load, spins around - The page cannot be displayed
- But change the URL to https://calibre.blah.com/ It will load fine and show im logged in.

Very basic HAProxy through pfsense is being used. No other services appear to have any issues.

**Comment by OzzieIsaacs** [comment] 2018-03-27 17:45
I have no glue about this proxy program, and so I have no idea whats the reason.
The only suggestion I can give is: After changing configuration delete browser cache, and maybe even reboot your server.
Iknow this is not very helpful.

**Comment by OzzieIsaacs** [comment] 2018-07-08 08:19
As nobody seems to have an idea, I'll close this one

**Closed by OzzieIsaacs** 2018-07-08 08:19 UTC
Labels: question

**Comment by MattW2** [comment] 2019-09-03 03:05
Would like to reopen this question if possible. I also run HAProxy and have found that if I connect to the Calibre-web server using an internal network it works and will continue to work thru the reverse proxy. However, if a new computer that has not connected thru the internal network tries to connect to https://calibre.bla.com it will not work. The same HAProxy settings with a different back end redirect work great for Home Assistant. Any ideas?

**Comment by vgracanin2** [comment] 2020-05-03 06:49
> Would like to reopen this question if possible. I also run HAProxy and have found that if I connect to the Calibre-web server using an internal network it works and will continue to work thru the reverse proxy. However, if a new computer that has not connected thru the internal network tries to connect to https://calibre.bla.com it will not work. The same HAProxy settings with a different back end redirect work great for Home Assistant. Any ideas?

If you are using docker as me we have exactly the same setup, I managed to get it working by adding some parameters. I will mention that someone who is more knowledgeable on HAProxy should re-check on this as I basically copied what was intended for nginx.
On [Docker HUB](https://hub.docker.com/r/linuxserver/calibre-web) states this needs to be added to nginx config.
`        location /calibre-web {
                proxy_pass              http://your-ip:8083;
                proxy_set_header        Host            $http_host;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Scheme        $scheme;
                proxy_set_header        X-Script-Name   /calibre-web;
        }` 

I added one "http-request header set" action in HAProxy frontend for each "proxy_set_header" mentioned above and it worked.

**Comment by OzzieIsaacs** [comment] 2020-05-03 06:52
Sounds plausible, Calibre-Web detects the 'X-Script-Name' and 'X-Forwarded-For' header fields and adds the path information to the links in the html files generated

**Comment by Stewge** [comment] 2020-08-18 03:00
Thought I would add that this is a working HAProxy Backend for Calibre-web:

```
backend calibre
        mode http
        option forwardfor
        http-request set-header X-Scheme https
        server calibre 127.0.0.1:8083
```

It just requires the X-Scheme header set to "https", assuming you are using HAProxy for SSL termination.
