### ISSUE TITLE
File uploads and then move fails with errors

### ISSUE THREAD

**Issue by ITestInProd** [janeczku/calibre-web#2062] opened 2021-07-21 13:30 UTC
### Describe the bug/problem
Upload fails with partial file move into an "Unknown" directory completed. The eBook is left in a halfway imported state. Attempting to further modify the eBook properties fails, such as setting author names, unless switching to Calibre itself.

### To Reproduce
1. Calibre database as well as eBooks reside on NFS storage presented to the Docker host
2. Enable debug logging in Calibre-Web
3. Enable file upload
4. Allow Calibre-Web to restart automatically
5. Upload a file
6. Observe errors in web browser

#### Debug log output from app:
```
[2021-07-20 13:49:04,282] DEBUG {cps.uploader:315} Temporary file: /tmp/calibre_web/ef5a8b75c7087bc7d0f66747e5788b65
[2021-07-20 13:49:09,389] ERROR {cps.helper:386} Rename title from: /tmp/calibre_web/ef5a8b75c7087bc7d0f66747e5788b65 to /books/Unknown/hakcing-police (363): [Errno 1] Operation not permitted: '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'
[2021-07-20 13:49:09,390] DEBUG {cps.helper:387} [Errno 1] Operation not permitted: '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/calibre_web/ef5a8b75c7087bc7d0f66747e5788b65' -> '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/calibre-web/cps/helper.py", line 367, in update_dir_structure_file
    shutil.move(os.path.normcase(path), os.path.normcase(os.path.join(new_path, db_filename)))
  File "/usr/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 436, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 381, in copystat
    lookup("chmod")(dst, mode, follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted: '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'
[2021-07-20 13:49:09,396] ERROR {cps.editbooks:976} Failed to move cover file /books/Unknown/hakcing-police/cover.jpg: [Errno 2] No such file or directory: '/books/Unknown/hakcing-police/cover.jpg'
[2021-07-20 13:49:09,595] DEBUG {cps.services.worker:72} Add Task for user: admin: <cps.tasks.upload.TaskUpload object at 0x7f2c0032f940>
```

#### Web browser errors:
```
Failed to Move Cover File /books/Unknown/hakcing-police/cover.jpg: [Errno 2] No such file or directory: '/books/Unknown/hakcing-police/cover.jpg'

Rename title from: '/tmp/calibre_web/ef5a8b75c7087bc7d0f66747e5788b65' to '/books/Unknown/hakcing-police (363)' failed with error: [Errno 1] Operation not permitted: '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'
```

### Expected behavior
Upload succeeds and the eBook is imported successfully into the Calibre database.

### Environment (please complete the following information):
 - OS: CentOS 7.9.2009
 - Python version: Python 3.8.10 (from LinuxServer Docker container)
 - Calibre-Web version: 0.6.12 - 54d06e580d73ba58274e7ed4efbd8fc94b7e1856
 - Docker container: LinuxServer / my own build
 - Browser: Firefox / Chrome

### Additional context
Observed while using the `linuxserver/docker-calibre-web:latest` image. Duplicated with my own image using vanilla CentOS. Happens with existing _and_ new Calibre database.

There are no known file permissions issues between the host OS and the Docker container. Calibre-Web is launched under the same UID/GID as owns the eBook NFS mount point and data. User running Calibre-Web is able to read/write to the eBook path from within the container.

#### Perms (from host OS) on directory root:
```
[root@docker02 ~]# stat /nfs/data/books
  File: ‘/nfs/data/books’
  Size: 11        	Blocks: 97         IO Block: 32768  directory
Device: 33h/51d	Inode: 4           Links: 9
Access: (0775/drwxrwxr-x)  Uid: (21023/ UNKNOWN)   Gid: (30502/ UNKNOWN)
Context: system_u:object_r:nfs_t:s0
Access: 2018-03-09 09:23:06.132849066 -0600
Modify: 2021-07-20 15:14:24.647097807 -0500
Change: 2021-07-20 15:14:24.647097807 -0500
 Birth: -
[root@docker02 ~]#
```

#### Perms and file creation test (from container):
```
root@cc990ad4ca17:/# id abc
uid=21023(abc) gid=30502(abc) groups=30502(abc),100(users)
root@cc990ad4ca17:/# stat /books/
  File: /books/
  Size: 126       	Blocks: 33         IO Block: 32768  directory
Device: 33h/51d	Inode: 41          Links: 124
Access: (0775/drwxrwxr-x)  Uid: (21023/     abc)   Gid: (30502/     abc)
Access: 2018-03-09 09:45:41.028502312 -0600
Modify: 2021-07-20 15:35:10.500390257 -0500
Change: 2021-07-20 15:35:10.500390257 -0500
 Birth: -
root@cc990ad4ca17:/# touch /books/abcxyz
root@cc990ad4ca17:/# stat /books/abcxyz 
  File: /books/abcxyz
  Size: 0         	Blocks: 1          IO Block: 131072 regular empty file
Device: 33h/51d	Inode: 33039       Links: 1
Access: (0775/-rwxrwxr-x)  Uid: (    0/    root)   Gid: (30502/     abc)
Access: 2021-07-20 16:02:39.555236962 -0500
Modify: 2021-07-20 16:02:39.555237730 -0500
Change: 2021-07-20 16:02:39.555243387 -0500
 Birth: -
root@cc990ad4ca17:/#
```

**Comment by ITestInProd** [comment] 2021-07-21 13:35
Appears to be similar to https://github.com/janeczku/calibre-web/issues/1875

**Comment by OzzieIsaacs** [comment] 2021-07-21 14:36
This case has more details and the hint what to look for ("Invalid cross-device link"). The temp folder is on different drive tahn the library, and the code uses the wrong copy function for this, I'll have a look at it

**Comment by OzzieIsaacs** [comment] 2021-07-21 18:58
This looks to be relevant: https://bugs.python.org/issue26791(https://bugs.python.org/issue26791#msg374648)

**Comment by OzzieIsaacs** [comment] 2021-07-21 19:27
During coping of the file the code (builtin python code) tries to do copy attributes from the source file in tmp folder to the destination file, this is denied with "PermissionError: [Errno 1] Operation not permitted:"
First it calls stat command and saves the attributes, the following "chmod" command fails. So is calibre-web user allowed to change the attributes via "chmod"?

**Comment by CHBMB** [comment] 2021-07-21 20:29
@OzzieIsaacs I can't reproduce this on my docker host.  I think we've ruled out NFS as the cause (seen some mounted filesystem issues in the past when dealing with docker)

We did some initial testing [here](https://github.com/linuxserver/docker-calibre-web/issues/153)

On my host I can indeed perform a `chmod` as the `abc` user (the pseudonym for the UID provided as the env var)

```bash
root@731a7470b442:/# apt update && apt install sudo
root@731a7470b442:/# mkdir /books/calibre-web/
root@731a7470b442:/# ls -la /books/
total 7984
drwxr-xr-x 1 root root        6 Jul 21 19:58  calibre-web
root@731a7470b442:/# sudo -u abc -s /bin/bash -c chmod 444 /books/calibre-web
root@731a7470b442:/# ls -la /books/
total 7984
dr--r--r-- 1 root root        6 Jul 21 19:58  calibre-web
```

One other thought I've had is regarding SElinux.  None of my hosts run SELinux so I can't test that, and it's thrown up some interesting issues with perm in the past.
https://github.com/linuxserver/docker-dokuwiki/issues/31#issuecomment-814295529

Worth considering @ITestInProd?

**Comment by ITestInProd** [comment] 2021-07-23 14:54
I believe @OzzieIsaacs nailed it regarding permissions. The `chmod` call fails in the NFS directory. I did some digging and the most likely reason for `chmod` to fail is due to this being a dual-share environment using CIFS **and** NFS. The NAS is apparently rejecting `chmod` commands as the share perms are CIFS style.

Mounting the share using CIFS I ran into https://github.com/janeczku/calibre-web/issues/2010.

**Comment by CHBMB** [comment] 2021-07-23 20:33
Great, always satisfying to work something like this out!

**Comment by OzzieIsaacs** [comment] 2021-07-27 05:54
@ITestInProd I'm using "nobrl" on my machine (but without docker) without problems for some years now. 

As the initial problem is not located in Calibre-Web, I'll close the issue.

Thanks for the good work and the effort you all put in.

**Closed by OzzieIsaacs** 2021-07-27 05:54 UTC
Labels: bug

**Comment by pmcgeever** [comment] 2024-09-19 15:20
For anybody finding this much later (like I did), adding the 'noperm' option to the CIFS mount as discussed [here](https://superuser.com/questions/744384/allow-chmod-on-cifs-mount) fixed it for me.

**Comment by profucius** [comment] 2025-04-12 17:49
> For anybody finding this much later (like I did), adding the 'noperm' option to the CIFS mount as discussed [here](https://superuser.com/questions/744384/allow-chmod-on-cifs-mount) fixed it for me. Though, I agree it is not a calibre-web issue.

Finally the answer I needed! the `noperm` (and `nobrl` perhaps) made this finally work for me on my SMB mounted Calibre Library on my Proxmox Host with LXC Docker container of Calibre-Web.
