### ISSUE TITLE
Checking the Read box when the file system is RO it crashes the app

### ISSUE THREAD

**Issue by awfki** [janeczku/calibre-web#1356] opened 2020-05-06 01:09 UTC
Of course that's a misconfiguration but I wouldn't think it would crash the app, just generate an error saying that it couldn't write.

When I check the button and click Update on the book it appears to have worked until I click on something else and then I get the stuff below.
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/web.py", line 165, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 483, in index
entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "/app/calibre-web/cps/helper.py", line 739, in fill_indexpage
len(db.session.query(database).filter(db_filter).filter(common_filters()).all()))
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3178, in all
return list(self)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
return self._execute_and_instances(context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
querycontext, self._connection_from_session, close_with_result=True
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
mapper=self._bind_mapper(), clause=querycontext.statement, **kw
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
conn = self.session.connection(**kw)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1124, in connection
execution_options=execution_options,
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
engine, execution_options
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 408, in _connection_for_bind
self._assert_active()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
code="7s2a",
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO custom_column_8 (book, value) VALUES (?, ?)]
[parameters: (23130, 1)]
(Background on this error at: http://sqlalche.me/e/e3q8) (Background on this error at: http://sqlalche.me/e/7s2a)
Please report this issue with all related information: Create issue
```

**Comment by awfki** [comment] 2020-05-06 01:15
I'd seen this before when the /books directory was RO but when I went to turn it on I found it had write enabled.  Not sure why it crashed but it was after I checked the Read box on a book, then Update, and then clicked something else, I think another book or the link back to recent additions.

**Comment by awfki** [comment] 2020-05-06 01:16
I keep saying Update button but it's actually Close at the bottom of the book's dialog.  I tried it again on another book and it crashed again.

**Comment by OzzieIsaacs** [comment] 2020-05-06 15:55
Please restart the app. One of the database requests in the past caused a problem and the session wasn't closed, now every now write request will cause a new traceback. (this one is related to #953)

**Comment by OzzieIsaacs** [comment] 2020-05-25 19:35
Fixed in current master branch

**Closed by OzzieIsaacs** 2020-05-25 19:35 UTC
Labels: bug

**Comment by khimaros** [comment] 2021-04-16 03:50
@OzzieIsaacs -- thank you for building this awesome service.

i'm still running into this problem with `0.6.11 - 4a4d02ea6a91ba3e77337cfce65e756e2e806599`. i am using the linuxserver docker image without any mods.

the issue is seems to be stemming from my use of read only docker volume for the /books path. of course, i wouldn't expect write operations to work, but somewhat surprising to see it fail on what seem to be GET operations.
 
this is the full error, which occurs when navigating to `/author?data=author&sort_param=stored` (by clicking the "Authors" link in the sidebar once, waiting for load, and then clicking "Authors" in the sidebar again:

```
[2021-04-16 03:35:09,188] ERROR {cps:1891} Exception on /author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 37, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 796, in author_list
    entries = calibre_db.session.query(db.Authors, func.count('books_authors_link.book').label('count')) \
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
    conn = self._get_bind_args(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
    return fn(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1142, in connection
    return self._connection_for_bind(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new
(sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE authors SET name=? WHERE authors.id = ?]
[parameters: ('<elided>', 100)]
```

**Comment by khimaros** [comment] 2021-04-16 04:04
i suspect this is the offending code https://github.com/janeczku/calibre-web/blob/b38877e19361eb41f328642667d1f44170a7ed5d/cps/web.py#L838
