### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by gtaranti** [janeczku/calibre-web#849] opened 2019-03-18 09:22 UTC
From the logs :

```
[2019-03-10 07:28:03,647] {/usr/lib/python2.7/site-packages/flask/app.py:1761} ERROR - Exception on /discover [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 344, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 1313, in discover
    title=_(u"Random Books"), page="discover")
  File "/app/calibre-web/cps/web.py", line 703, in render_title_template
    return render_template(instance=config.config_calibre_web_title, accept=EXTENSIONS_UPLOAD, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/app/calibre-web/cps/templates/discover.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/calibre-web/cps/templates/layout.html", line 190, in top-level template code
    {% block body %}{% endblock %}
  File "/app/calibre-web/cps/templates/discover.html", line 22, in block "body"
    {% if loop.index > config_authors_max and config_authors_max != 0 %}
UndefinedError: 'config_authors_max' is undefined
[2019-03-18 09:10:19,223] {/usr/lib/python2.7/site-packages/flask/app.py:1761} ERROR - Exception on /discover [GET]
```

The errors started to happen on every page outside the main page, after doing the last update (0.6.1).

The error is always the same : about the **config_authors_max**

**Comment by OzzieIsaacs** [comment] 2019-03-18 10:11
The project is currently in transition from updating everybody with everything to a stable/nightly system. Unfortunately there was a bug in the updater, so I had to revert this system. It looks now you've updated from an older version right into this system and you now stuck in a "buggy commit". Could you please change the updater to nightly (admin -> basic configuration -> server settings). Then you should have the option to update to a newer commit, where is issue is fixed. It's recommend afterwards to revert the updater setting to "stable"

**Comment by OzzieIsaacs** [comment] 2019-03-18 10:11
Duplicate of #847

**Comment by gtaranti** [comment] 2019-03-18 10:19
I've done exactly what you've suggested, and my problems solved.

Thanks!

**Closed** 2019-03-18 10:20 UTC
Labels: question
