### ISSUE TITLE
Tornado reverse proxy issue

### ISSUE THREAD

**Issue by douglasak** [janeczku/calibre-web#1477] opened 2020-06-08 13:34 UTC
**Describe the bug/problem**
I'm having an issue with version 0.6.8 in the LinuxServer docker. Version 0.6.7 works fine. The issue occurs when accessing Calibre-Web through an SSL reverse proxy. The error message shows up in the log below and Nginx reports "502 Bad Gateway". 

Calibre-Web works fine when accessing directly outside the reverse proxy.

**To Reproduce**
Access webpage through SSL reverse proxy.

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

[2020-06-08 14:26:07,040] ERROR {tornado.application:67} Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/http1connection.py", line 273, in _read_message
    delegate.finish()
  File "/usr/local/lib/python3.6/dist-packages/tornado/httpserver.py", line 280, in finish
    self.request_callback(self.request)
  File "/usr/local/lib/python3.6/dist-packages/tornado/wsgi.py", line 114, in __call__
    WSGIContainer.environ(request), start_response
  File "/usr/local/lib/python3.6/dist-packages/tornado/wsgi.py", line 154, in environ
    port = int(hostport[1])
ValueError: invalid literal for int() with base 10: '443,calibre.internaldomain.net

**Expected behavior**
Calibre-Web should load correctly through the reverse proxy.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Docker
 - Python version: Python 3.6
 - Calibre-Web version: 0.6.8 not 0.6.7
 - Docker container: LinuxServer 0.6.8-ls66 and 0.6.8ls65 but not 0.6.7-ls64

**Additional context**
Access via reverse proxy

**Comment by mediacrave** [comment] 2020-06-08 14:56
I experience the same issue with the same Environment above.

Back on 0.6.7 for now

**Comment by OzzieIsaacs** [comment] 2020-06-08 15:01
Looks to me not like a problem with calibre-web itself. 
Seems to be a missconfiguration in the environment variables (CALIBRE_PORT), instead of `443` the configuration value looks like `443,calibre.internaldomain.net`.
Please report the issue at the LinuxServer docker repro

**Comment by mediacrave** [comment] 2020-06-08 17:33
I know nothing, but when I'm on the 0.6.7 docker by linuxserver and upgrade within the docker it also breaks even without updating to the latest 0.6.8 docker.
I have tried setting CALIBRE_PORT variable within the docker template with no luck.

Again, I know very little...

**Comment by tobbenb** [comment] 2020-06-08 19:21
@OzzieIsaacs You can close this issue. The issue is in our letsencrypt container and is fixed by updating the proxy.conf in the /config/nginx/ folder.

**Comment by OzzieIsaacs** [comment] 2020-06-08 19:22
Thanks for fixing it

**Closed by OzzieIsaacs** 2020-06-08 19:22 UTC
Labels: question

**Comment by douglasak** [comment] 2020-06-08 19:28
Thank you both.

**Comment by tobbenb** [comment] 2020-06-08 19:33
It was already fixed in October last year :)
The issue was the line below in the reverse proxy config for calibre-web in combination with using an old version of the proxy.conf and version 0.6.8 of Calibre-web.

`proxy_set_header Host $http_host;`

The only change in the proxy.conf was from
`proxy_set_header Host $host:$server_port;`
to
`proxy_set_header Host $host;`

The line from the
