### ISSUE TITLE
cannot remove the books through the ‘remove selections’ button in the books list

### ISSUE THREAD

**Issue by BenBenJian** [janeczku/calibre-web#2330] opened 2022-03-08 02:54 UTC
1. Go to 'books list'
2. Click on 'any of the books'
3. Click on remove selections
4. cannot remove any of the books.
[Calibre-Web-debug-pack.zip](https://github.com/janeczku/calibre-web/files/8202326/Calibre-Web-debug-pack.zip)

**Comment by OzzieIsaacs** [comment] 2022-03-09 13:48
I can't reproduce this. Just to make sure:
The remove selections removes the selection (the ticked checkbox):
![grafik](https://user-images.githubusercontent.com/6438895/157454157-2165d489-f008-4afe-9b9a-ccd9874983f7.png)
To delete the books, please tick the "trashcan":
![grafik](https://user-images.githubusercontent.com/6438895/157454381-35ca27dc-09a3-4e6e-9bf8-6949627fad93.png)
Currently it's only possible to delete books one by one

**Comment by BenBenJian** [comment] 2022-03-10 10:58
Oh got it!
It is a translation error in chinese.🤣

it means “delete all books which seleted”

**_Currently it's only possible to delete books one by one_**
Hope add the Bulk delete function，thanks

**Comment by OzzieIsaacs** [comment] 2022-03-12 09:23
It's on the list, but it's a long list. I'll close the issue.
If the translation is missleading it would be great if you could correct this and create a pull request:
https://github.com/janeczku/calibre-web/blob/master/cps/translations/zh_Hans_CN/LC_MESSAGES/messages.po
(After changing the text it still will not show up in Calibre-Web, I can manage this)

**Closed by OzzieIsaacs** 2022-03-12 09:23 UTC
Labels: not reproducible
