### ISSUE TITLE
built in reader error

### ISSUE THREAD

**Issue by chutzler** [janeczku/calibre-web#982] opened 2019-07-28 11:35 UTC
Whenever I attempt to access the built-in reader via the 'epub' link while viewing a book info, I get the following...

```
Could not build url for endpoint 'bookmark' with values ['book_format', 'book_id']. Did you mean 'web.bookmark' instead?
File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/calibre-web/cps/web.py", line 146, in decorated_view return login_required(func)(*args, **kwargs)
File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 228, in decorated_view return func(*args, **kwargs)
File "/opt/calibre-web/cps/web.py", line 207, in inner return f(*args, **kwargs)
File "/opt/calibre-web/cps/web.py", line 1309, in read_book return render_title_template('read.html', bookid=book_id, title=_(u"Read a Book"), bookmark=bookmark)
File "/opt/calibre-web/cps/web.py", line 240, in render_title_template *args, **kwargs)
File "/usr/lib/python3/dist-packages/flask/templating.py", line 134, in render_template context, ctx.app)
File "/usr/lib/python3/dist-packages/flask/templating.py", line 116, in _render rv = template.render(context)
File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render return original_render(self, *args, **kwargs)
File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True)
File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise raise value.with_traceback(tb)
File "/opt/calibre-web/cps/templates/read.html", line 86, in top-level template code bookmarkUrl: "{{ url_for('bookmark', book_id=bookid, book_format='EPUB') }}",
File "/usr/lib/python3/dist-packages/flask/helpers.py", line 333, in url_for return appctx.app.handle_url_build_error(error, endpoint, values)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1805, in handle_url_build_error reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise raise value
File "/usr/lib/python3/dist-packages/flask/helpers.py", line 323, in url_for force_external=external)
File "/usr/lib/python3/dist-packages/werkzeug/routing.py", line 1776, in build raise BuildError(endpoint, values, method, self)
```

I'm sure it's something I've done wrong, but I can't seem to figure out whats going on here...

**Comment by OzzieIsaacs** [comment] 2019-07-28 11:48
It's a duplicate of #969, please update to the newest commit version

**Closed** 2019-07-28 19:30 UTC
Labels: duplicate
