### ISSUE TITLE
Python 3.5 - Sending email through SMTP email server crashs the program

### ISSUE THREAD

**Issue by pjortiz** [janeczku/calibre-web#861] opened 2019-03-25 22:44 UTC
Hello,

After setting up the SMTP email server settings I then attempt to create a new user through the registration option. After clicking the 'Register' button, I look at the console and it almost immediately floods the console window with a `DEBUG` message. [Screenshot](https://i.imgur.com/AlPrP87.png)

After I restart the server, I can see that it successfully created the new user, but it seems to me that when it attempts to send the email it gets an error and is stuck in an infinite loop. The only way to stop it is to wait for it to run out of memory or hold down `ctrl+c`. 

The `calibre-web.log` has no useful information in it. It only shows the server trying the shutdown.

I am currently using the following SMTP settings:
SMTP hostname: `smtp.gmail.com`
SMTP port: `465`
Encryption: `SSL/TLS`
SMTP login: `[email]@gmail.com`
SMTP password: `[password]`

I had these setting working a while ago, but now seem to be broken after some update.

System Info:
Virtual Machine
OS: Ubuntu 16.04.5 server 64-bit
Python Version: 3.5.2

**Comment by robgkmunn** [comment] 2019-04-14 07:19
I'm also seeing the same issue with the exact same settings/error.

**Comment by OzzieIsaacs** [comment] 2019-04-14 12:15
In general I can not reproduce the error. I found one error regarding misconfigured smtpserver which could cause emails not being send. Could you please update to the newest commit?
After setting the email server settings, could you please use the send test email and save button. Please check the result in the task section. Is the result: successful? If yes, please try to register a new user and check the result in the task overview? What is the output?

**Comment by pjortiz** [comment] 2019-04-16 21:28
I just updated to the newest commit and checked it. It still seems to be having the same issue.

The only thing that showed up in the log this time was the repeated message `DEBUG in worker: reply: retcode (235); Msg: b'2.7.0 Accepted`.

I also noticed that I cannot start the server without root privileges. Last time I posted an issue (#830) this had something to do with Python3.

If this helps I also transcribed a simplified output of the console messages:

`DEBUG in worker: send: 'ehlo 600\r\n''` _Repeated_
_Python error (I could only read the last half of the error):_
```
File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
   self.handle(record)
File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
   self.callHandlers(record)
File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
   self.handle(record)
File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
   self.emit(record)
File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
   stream.write(self.buffer)
File "/home/calibre/calibre-web/cps/worker.py", line 522, in write
   self.logger.debug(self.buffer)
Unable to print the message and arguments - possible formatting error.
```
`DEBUG in worker: reply: b'250-smtp.gmail.com at your service, [MY IP ADDRESS]\r\n'` _Repeated_
`DEBUG in worker: reply: b'250-SIZE 35882577\r\n'` _Repeated_
`DEBUG in worker: reply: b'250-8BITMINE\r\n'` _Repeated_
`--- Logging error ---`
`DEBUG in worker: reply: b'250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\r\n'` _Repeated_
_Python error (same as previous)_
`DEBUG in worker: reply: b'250-ENHANCEDSTATUSCODES\r\n'` _Repeated_
`--- Logging error ---`
`DEBUG in worker: reply: b'250-PIPELINING\r\n'` _Repeated_
`DEBUG in worker: reply: b'250-CHUNKING\r\n'` _Repeated_
`DEBUG in worker: reply: b'250 SMTPUTF8\r\n'` _Repeated_
`DEBUG in worker: reply: retcode (250); Msg: b'250-smtp.gmail.com at your service, [MY IP ADDRESS]\nSIZE 35882577\n8BITMINE\nAUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'` _Repeated_
`--- Logging error ---`
`DEBUG in worker: send: 'AUTH PLAIN AHBqcy5jYWxpYnJ1LmxpYnJhcn1AZ21haWwY29tAGt1eDIzNzQz\r\n'` _Repeated_
_Python error (same as previous)_
`DEBUG in worker: reply: b'235 2.7.0 Accepted\r\n'` _Repeated_
`--- Logging error ---`
`DEBUG in worker: reply: retcode (235); Msg: b'2.7.0 Accepted`
`Killed`

It seems to me that every time there is a `--- Logging error ---` the log file gets overwriten. I think this is might be because I'm running the server on a VM that only has 1 GB of ram and a 10 GB virtual disk with only around 800 MB free.

**Comment by pjortiz** [comment] 2019-04-16 21:46
I forgot to say this be for but the test e-mail failed too.

**Comment by OzzieIsaacs** [comment] 2019-04-17 17:39
Okay, could you please delete the line 522 ("self.logger.debug(self.buffer)") in cps/worker.py.
This line causes the error, because the text seems not to be formatable, but this error should be  catched, I don't understand why this isn't working. If this isn't helping, please delete the following line (print...) in the same file

**Comment by pjortiz** [comment] 2019-04-20 22:01
I commented out line 522 and that seems to have fixed the issue.

**Comment by OzzieIsaacs** [comment] 2019-04-21 05:11
Could you please paste the output on the console once more, so I can check which outputline causes the problem, and find a fix for this?

**Comment by pjortiz** [comment] 2019-04-21 08:09
I'm not sure which output you wanted, so here is the output of the console after commenting out line 522. If you wanted the output without commenting it out let me know, but I don't think it will change.

_Console Output:_
```
::ffff:192.168.1.15 - - [2019-04-21 03:53:15] "POST /admin/mailsettings HTTP/1.1" 200 13424 0.012526
::ffff:192.168.1.15 - - [2019-04-21 03:53:15] "GET /ajax/domainlist?order=asc HTTP/1.1" 200 280 0.003264
send: 'ehlo 600\r\n'
reply: b'250-smtp.gmail.com at your service, [MY.IP.ADDRESS]\r\n'
reply: b'250-SIZE 35882577\r\n'
reply: b'250-8BITMIME\r\n'
reply: b'250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\r\n'
reply: b'250-ENHANCEDSTATUSCODES\r\n'
reply: b'250-PIPELINING\r\n'
reply: b'250-CHUNKING\r\n'
reply: b'250 SMTPUTF8\r\n'
reply: retcode (250); Msg: b'smtp.gmail.com at your service, [MY.IP.ADDRESS]\nSIZE 35882577\n8BITMIME\nAUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'
send: 'AUTH PLAIN AHBqcy5jYWxpYnJlLmxpYnJhcnlAZ21haWwuY29tAGt1eDIzNzQz\r\n'
reply: b'235 2.7.0 Accepted\r\n'
reply: retcode (235); Msg: b'2.7.0 Accepted'
send: 'mail FROM:<mail@example.com> size=556\r\n'
reply: b'250 2.1.0 OK g206sm4630770qkb.75 - gsmtp\r\n'
reply: retcode (250); Msg: b'2.1.0 OK g206sm4630770qkb.75 - gsmtp'
send: 'rcpt TO:<MY.EMAIL@hotmail.com>\r\n'
reply: b'250 2.1.5 OK g206sm4630770qkb.75 - gsmtp\r\n'
reply: retcode (250); Msg: b'2.1.5 OK g206sm4630770qkb.75 - gsmtp'
send: 'data\r\n'
reply: b'354  Go ahead g206sm4630770qkb.75 - gsmtp\r\n'
reply: retcode (354); Msg: b'Go ahead g206sm4630770qkb.75 - gsmtp'
data: (354, b'Go ahead g206sm4630770qkb.75 - gsmtp')
send: b'Content-Type: multipart/mixed; boundary="===============2529207707919567154=="\r\nMIME-Version: 1.0\r\nSubject: Calibre-Web test e-mail\r\nMessage-Id: <155583319613.1810.7389026291798138699.calibre-web@ubuntuServer>\r\nDate: Sun, 21 Apr 2019 03:53:16 -0400\r\nFrom: automailer <mail@example.com>\r\nTo: MY.EMAIL@'
reply: b'250 2.0.0 OK  1555833196 g206sm4630770qkb.75 - gsmtp\r\n'
reply: retcode (250); Msg: b'2.0.0 OK  1555833196 g206sm4630770qkb.75 - gsmtp'
data: (250, b'2.0.0 OK  1555833196 g206sm4630770qkb.75 - gsmtp')
send: 'quit\r\n'
reply: b'221 2.0.0 closing connection g206sm4630770qkb.75 - gsmtp\r\n'
reply: retcode (221); Msg: b'2.0.0 closing connection g206sm4630770qkb.75 - gsmtp'
```

**Comment by OzzieIsaacs** [comment] 2019-04-21 09:32
I can reproduce the problem. It's related to python 3.5 with python 2.7 or 3.6 everything works fine.

**Comment by OzzieIsaacs** [comment] 2019-04-21 10:57
Good and bad new:
The good news, it's working in the development branch
The bad news: I don't know why and so I can't backport it to the main branch, you have to wait until the current development branch is merged to the master branch. Until then the workaround is deleting line 522 in cps/worker.py. 
Sideffect: Logging is not working for email messages

**Comment by pjortiz** [comment] 2019-04-21 21:10
I just tried with python3.6 but I got a similar result as I did with 3.5. Only difference is the application killed its self at `send: 'ehlo 600\r\n'`. This might have to do with the fact that I still have 3.5 installed. Unfortunately I don't think I am able to remove it to check because other services I am running may require it.

**Comment by OzzieIsaacs** [comment] 2019-04-22 07:37
No problem, just delete the line and you should be fine for now

**Comment by OzzieIsaacs** [comment] 2019-07-22 19:12
The development branch is merged back to master branch, it should now work

**Closed** 2019-07-27 08:18 UTC
Labels: bug
