### ISSUE TITLE
Condensed views of OPDS feed

### ISSUE THREAD

**Issue by PeterJT** [janeczku/calibre-web#1601] opened 2020-09-03 02:12 UTC
Is there anyway to customize the opds feed? I'd like the ability to show "condensed" views of selections like Authors; rather than seeing all authors with a Next button at the bottom I'd like to see a list of the letters A through Z, then clicking on a letter would start displaying all authors with the corresponding last name.

**Comment by timholl** [comment] 2020-09-08 12:34
Duplicate of #1582

**Comment by OzzieIsaacs** [comment] 2021-05-28 17:38
The letter view is available meanwhile

**Closed by OzzieIsaacs** 2021-05-28 17:38 UTC
