### ISSUE TITLE
Make use of static analysis

### ISSUE THREAD

**Issue by jvoisin** [janeczku/calibre-web#1328] opened 2020-04-24 16:20 UTC
I've thrown calibre-web at LGTM.com and it found a [bunch of low-hanging issues]( https://lgtm.com/projects/g/janeczku/calibre-web/?mode=list ).

I'm sure that correctly configured, LGTM will find even more, and so will [coverity]( https://scan.coverity.com/ ). This will help reducing the number of bugs present in calibre-web, without adding overhead for contributors nor maintainers, while providing low-hanging bugs to fix for newcomers.

**Comment by OzzieIsaacs** [comment] 2020-04-24 16:43
I like the codacy static code analysis I'm currently using more. It gives an A rating
![grafik](https://user-images.githubusercontent.com/6438895/80236291-42422b00-865b-11ea-830c-f02b00d3483a.png)
The problem is, via introducing the github actions, codacy isn't working anymore automatically, because I need to insert a action hook, and I'm not the repository owner, and didn't manage it to contact the owner, yet.

**Comment by OzzieIsaacs** [comment] 2020-05-25 19:38
I'll close this issue. Codacy is used for code analysis. 
A eslint config file is located in the root folder to also run eslint offline

**Closed by OzzieIsaacs** 2020-05-25 19:38 UTC
