### ISSUE TITLE
Calibre-web 0.6.19 does not start

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#2503] opened 2022-08-01 13:30 UTC
Clean installation on Manjaro

![Captura de pantalla de 2022-08-01 15-24-21](https://user-images.githubusercontent.com/65027248/182158931-ab20c452-7e57-4862-9948-981b3b75d543.png)

**Comment by OzzieIsaacs** [comment] 2022-08-01 13:31
You are missing flask_login, please install it

**Comment by yeraycito** [comment] 2022-08-01 13:33
It is installed:

APScheduler>=3.9.1,<3.10.0
werkzeug<2.2.2
Babel>=2.10.3,<3.0
Flask-Babel>=2.0.0,<2.1.0
Flask-Login>=0.6.2,<0.6.3
Flask-Principal>=0.4.0,<0.5.1
backports_abc>=0.5
Flask>=2.1.3,<2.1.4
iso-639>=0.4.5,<0.5.0
PyPDF3>=1.0.6,<1.0.7
pytz>=2022.1
requests>=2.28.1,<2.28.2
SQLAlchemy>=1.4.39,<1.5.0
tornado>=6.2,<6.3
Wand>=0.6.8,<0.7.0
unidecode>=1.3.4,<1.4.0
lxml>=4.9.1,<4.9.2
flask-wtf>=1.0.1,<1.1.0
chardet>=5.0.0,<5.1.0
advocate>=1.0.0,<1.1.0

**Comment by OzzieIsaacs** [comment] 2022-08-01 14:07
The screenshot says no. This is the problem with python, you can have several independent virtual environments with different installed versions and libraries. Without any context what you did (exactly!) I can‘t help you to find you problem

**Comment by yeraycito** [comment] 2022-08-01 15:21
Solved. The problem was that I did the installation using the old pip3 install --target vendor -r requirements.txt command.
Doing it with the manual installation ./venv/bin/python3 -m pip install -r requirements.txt all ok.
The manual installation is different from the recommended one and I see that it is done in a virtualised way. Could you explain to me what the differences are between one and the other?
Is manual and virtual installation more secure?

**Comment by OzzieIsaacs** [comment] 2022-08-01 15:30
The "old" version with the target vendor folder, is not common. I don't support it it anymore therefore. 
I called version with the virtual environment the manual version. It places all config, log files in the calibre-web folder, so just deleting the calibre-web folder deletes everything.
The other installation would be the installation using pip, this will place calibre-web somewhere deep in the system folders and places the config and log files in the users home directory. Additional benefit is, that it also generates a starter script.

I don't think there is a difference in security.

As the problem is solved, I'll close the issue. If you have any more questions, please post it to this issue. I will respond, if you ask in the next few days

**Closed by OzzieIsaacs** 2022-08-01 15:30 UTC
Labels: invalid
