### ISSUE TITLE
update not available

### ISSUE THREAD

**Issue by Riccardomirto** [janeczku/calibre-web#875] opened 2019-04-04 16:23 UTC
I am running version 0.6.1 and since a while now I do not receive any update when I Check for update from the Admin page. I installed a docker image and I am not very expert on reconfiguring the application, but I love it and I find it very useful. Is there anything wrong with the updater or simply no more update released? Thanks

**Comment by OzzieIsaacs** [comment] 2019-04-04 17:51
duplicate of #815

**Closed by OzzieIsaacs** 2019-04-04 17:51 UTC
