### ISSUE TITLE
python cps.py fail on Windows 10 

### ISSUE THREAD

**Issue by candidodmv** [janeczku/calibre-web#205] opened 2017-06-20 21:15 UTC
OSError: [WinError 10013] Foi feita uma tentativa de acesso a um soquete de uma maneira que é proibida pelas permissões de acesso

**Comment by OzzieIsaacs** [comment] 2017-06-21 16:43
Could you please check the hints in #180? 
The port is blocked by another program (apache?, IIS?).

**Comment by gabriellluz** [comment] 2017-06-25 20:12
Eu uso Windows 10 e funciona perfeitamente. Quais os passos que você executou? / I use Windows 10 and it works perfectly. Which steps you've taken?

**Comment by OzzieIsaacs** [comment] 2017-07-16 20:15
Are there any news on this, otherwise I would close it.

**Comment by gabriellluz** [comment] 2017-07-16 22:21
Works for me. I think a clean install of Windows 10 would solve the problem. But I can't reproduce the problem described by the op.

**Comment by gabriellluz** [comment] 2017-07-16 22:21
You can close.

**Closed** 2017-07-17 04:49 UTC
