### ISSUE TITLE
Bookshelves Question

### ISSUE THREAD

**Issue by gelsas** [janeczku/calibre-web#482] opened 2018-04-03 02:00 UTC
Hello, its me another time, sorry for all the questions but I am in love with this software!

Is it possible to add Bookshelfs inside of Bookshelfs?

E.g.:
MAGZINE
   -> MAGAZINE (2018)
        -> Magazines (this is no bookshelf)
   -> MAGAZINE (2017)
        -> Magazines (this is no bookshelf)
MAGZINE 3
   -> MAGAZINE 3 (2018)
        -> Magazines 3 (this is no bookshelf)
   -> MAGAZINE 3 (2017)
        -> Magazines 3 (this is no bookshelf)
etc.

and it would be great to have the possiblity to tag if it is an bookshelf for books or if it is a bookshelf for magazines

kind regards

(EDIT: I hope I am not annoying you with all the questions. These features just would make this the perfect all in one tool for me)

**Comment by OzzieIsaacs** [comment] 2018-04-03 13:30
Duplicate of  #370.
I'll close this one and track the feature in the above issue.

**Closed by OzzieIsaacs** 2018-04-03 13:30 UTC
