### ISSUE TITLE
Magic Link on Tolino

### ISSUE THREAD

**Issue by Flo-63** [janeczku/calibre-web#244] opened 2017-07-19 19:20 UTC
Hi there,
even though I'm able to login to calibre web using the web browser on my tolino, I can't download epubs. I receive the error message that the book is corrupted... of course it is not. 
Any idea how I'd be able to make this work? Or do I use "Magic Link" logon not in the right way?

Many thanks,

Flo

**Comment by Kyosfonica** [comment] 2017-07-19 19:32
It is a known issue that I don't believe will be fixed.
The problem is that the tolino browser doesn't support the way the downloads are handled by the server.
Try using the OPDS service instead. The address is the same but ended with /opds

**Comment by OzzieIsaacs** [comment] 2017-07-20 05:16
Same issue as#137

**Comment by Flo-63** [comment] 2017-07-23 17:16
First, sorry that I missed #137... 
I get an error message when I try to connect my tolino to odps catalog on my server:
"Could not verify your access level for that URL. You have to login with proper credentials".
Apparently, the login dialog box which is shown when connecting from my PC cannot be shown on tolino.... Any Idea how to work around this? 
Thanks,
Flo

**Comment by teflontoni** [comment] 2017-09-02 10:06
On my Tolino Vision 3HD Download works as expected. Perhaps a newer Tolino Firmware fixed the faulty behaviour?

**Comment by Flo-63** [comment] 2017-09-02 10:26
Hi teflontoni,
I use a vision 3HD as well, software is 10.1.0.
However, I can't authenticate to calibre-web as the dialogue is not shown. As well https://username:password@myebooks.tld doesn't work. So, I'm pretty curious how you are able to connect to opds service - do you allow unauthorized guest access?
Thx,
Flo

**Comment by Flo-63** [comment] 2017-09-02 10:27
..oops. Closed by mistake...

**Comment by teflontoni** [comment] 2017-09-02 10:29
I don't use opds, instead the web interface. I don't have my reader in reach right now. Will test it as soon as I'm at home.

**Comment by OzzieIsaacs** [comment] 2017-12-02 13:35
No news on this one?

**Closed by OzzieIsaacs** 2017-12-02 13:35 UTC
Labels: duplicate
