### ISSUE TITLE
Unable to send emails

### ISSUE THREAD

**Issue by neiliid** [janeczku/calibre-web#1381] opened 2020-05-11 15:45 UTC
Hi,

I am running Calibre-web in a docker container, when I try to send an email STARTTLS, Calibre Web is unable to progress past the EHLO stage of the handshake. Calibre-web is providing the internal IP address of the docker container to the mail server as per the log below.

[2020-05-11 16:34:51,710] DEBUG {cps.worker:125} send: 'ehlo [172.17.0.12]\r\n'
[2020-05-11 16:34:51,721] DEBUG {cps.worker:125} send: 'STARTTLS\r\n'
[2020-05-11 16:34:51,746] DEBUG {cps.worker:125} send: 'ehlo [172.17.0.12]\r\n'
[2020-05-11 16:34:51,822] ERROR {cps.worker:520} Error sending email: 

When I switch the SSL encryption, the log files show the following:

[2020-05-11 16:23:41,385] ERROR {cps.worker:520} Error sending email: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)

No-encryption is not a reasonable option. I have restarted the server between changes and I have validated the configuration with Thunderbird to confirm the username and password and STARTTLS work on the mailserver.

Have a great day.

**Comment by OzzieIsaacs** [comment] 2020-05-11 16:03
I don‘t think it‘s the same problem. This error message tells me there is something wrong with the ssl encryption (wrong version, what is the Server expecting, python is no longer accepting sslv3)

**Comment by OzzieIsaacs** [comment] 2020-05-11 17:04
Sorry, I didn't read part regarding the WRONG_VERSION_NUMBER right. This is correct If you try to contact an ssl server with unencrypted traffic, the resonse is like you describe it. So forget my last post

**Comment by OzzieIsaacs** [comment] 2020-05-11 17:31
In my latest commit (from just now) I added up some more debug outputs. Normally you can sneak into the the docker container and replace files, so please replace worker.py (from the cps folder) with the newest one from master branch, restart Calibre-Web (and the docker container?) and try sending email again. We should then hopefully get a better output in the logfile

**Comment by OzzieIsaacs** [comment] 2020-06-03 17:15
I created a new release with the improved debug output, if the problem is still there, please post debug logs. If you could solve the problem meanwhile, please close the issue

Thanks

**Comment by OzzieIsaacs** [comment] 2023-08-04 08:53
No response

**Closed** 2023-08-04 08:53 UTC
Labels: question
