### ISSUE TITLE
opds address dont work

### ISSUE THREAD

**Issue by Obi8** [janeczku/calibre-web#1096] opened 2019-11-29 22:50 UTC
Hello Guys,

i installed calibre-web on my raspberry pi.
It looks really good and the performance is also good. :-)
My problem is if i try to enter the opds calibre-web address like hostname:port/opds/
i must download a file "application/atom+xml".

If try with a opds reader (freda) i get a error:

```
ERROR:tornado.access:500 GET /opds/series/2 (192.168.178.58) 59.74ms
WARNING:tornado.access:401 GET /opds/series/2 (192.168.178.58) 14.42ms
WARNING:tornado.access:401 GET /opds (192.168.178.58) 14.16ms
 ERROR in app: Exception on /opds/series/2 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi                                                       _app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full                                                       _dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in hand                                                       le_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full                                                       _dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in disp                                                       atch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/calibre-web/cps/web.py", line 285, in decorated
    if not auth or not check_auth(auth.username, auth.password):
  File "/home/pi/calibre-web/cps/web.py", line 270, in check_auth
    return bool(user and check_password_hash(user.password, password))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/security.py", line 221,                                                        in check_password_hash
    return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/security.py", line 153,                                                        in _hash_internal
    rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/security.py", line 53, i                                                       n pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/security.py", line 87, i                                                       n pbkdf2_bin
    return hashlib.pbkdf2_hmac(hash_name, data, salt, iterations, keylen)
TypeError: pbkdf2_hmac() argument 2 must be string or buffer, not None
```

Can any one help me?

My System:
Raspberry Pi 3
Rasbian
All dependecies are installed

**Comment by OzzieIsaacs** [comment] 2019-11-30 08:25
Looks like some problem with the password during authentication for the opds feed.
So:
You can download the feed (which looks like a xml file) from a normal browser like firefox/chrome/..., right?
Did you enable anonymous browsing? -> Then no password should be necessary. 
If not could you please try it, if you have it could you please try the one with authentication?
If you have authentication enabled, your password is not empty? (Should work, too)
I'll try to check it.

**Comment by OzzieIsaacs** [comment] 2019-11-30 08:41
I doublechecked it, for me it's working (on ubuntu on x86 PC)

**Comment by Obi8** [comment] 2019-11-30 09:12
I activate anonymous browsing and in the browser i can only download the xml file.

In the opds reader (fred) i clear the user login and can connect to the calibre-web (works with user login too, sorry i forget to write it).
If i choose any ebook i get the message `download failed pls check the internet connection`.

I try with another reader (Android: Challenger Comics Viewer) i get the message `Error: error while checking file "address of file" in opds. : HTTP/1.1 403/Forbidden`.

The user password is not empty and the user has the privileg to download e-books. it works without opds.
The integrated viewer doesnt work for me too.

**Comment by OzzieIsaacs** [comment] 2019-11-30 09:13
Which version are you using?

**Comment by Obi8** [comment] 2019-11-30 09:19
Calibre-web has the version 0.6.4.
I forget to write that i use calibre-web for reading comics in the cbr format.
Libraries installed:

`Tornado 	v5.1.1

Sqlite 	v3.27.2

lxml 	v4.3.2.0

Image Magick 	ImageMagick 6.9.10-23 Q16 arm 20190101 https://imagemagick.org

Wand 	0.5.7

Flask 	v1.1.1

Babel 	v2.7.0

pytz 	v2019.3

PyPdf 	v1.26.0

pySqlite 	v2.6.0

Flask Login 	v0.4.1

ebook_converter 	Nicht konfiguriert

Iso 639 	v0.4.5

Python 	2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]

Sqlalchemy 	v1.3.11

Jinja2 	v2.10.3

Werkzeug 	v0.16.0

Requests 	v2.22.0

Pillow 	v6.2.1

Flask Principal 	v0.4.0`

**Comment by OzzieIsaacs** [comment] 2019-11-30 13:45
In opds Feed some errors have been found recently. An update to the newest nightly version might be worth a try. (Admin section, basic Setup, server setup, setup channel and than execute a search for updates. You can go back by setting update channel to stable and search for an update)

**Comment by Obi8** [comment] 2019-11-30 14:17
Hello Ozzielsaacs,
i updated to the latest nightly version 26.11.2019. But the problem is the same. :-)
Thank you for youre help.

**Comment by OzzieIsaacs** [comment] 2019-12-01 08:51
I found the problem causing the exception. Freda tries several authentication methods (digestion and afterwards basic authentication, which is the right one). Handling wrong authentication type wasn't checked and properly handled. Non the less everything else is working for me. I used the admin account with unchanged password and the following rights:
![grafik](https://user-images.githubusercontent.com/6438895/69911669-4016d000-141f-11ea-900c-28d053506d44.png)
I don't own a android device, so I use Oracle Virtualbox with an android simulator. I installed there Freda v4.31 rev2.
With authentication enabled the book-covers aren't displayed (not my fault, Freda is requesting the covers only with the wrong authentication method and gives afterwards up). 
Download and view work both without any trouble.  
For your reference my setup on a raspberry pi zero-w:
![grafik](https://user-images.githubusercontent.com/6438895/69911740-232ecc80-1420-11ea-81d6-4a342127fa08.png)

**Comment by OzzieIsaacs** [comment] 2019-12-01 08:55
Something you could try to figure out the problem a bit more. If you use a "normal browser" and go to
"http://[servername]:8083/opds/new" it should prompt you for your credentials and you should be able to download the xml file. Open the file and check for a random book and try to enter  
"http://[servername]:8083//opds/download/[fileno]/epub/ in your browser. It should download the file afterwards without trouble.

**Comment by OzzieIsaacs** [comment] 2019-12-01 09:13
Also checked the Challenger Comics Viewer: Works perfect. I checked the download of a cbz file. It was viewable afterwards without any trouble.

**Comment by Obi8** [comment] 2019-12-01 10:09
I have adjusted the rights as seen in the picture of you.
In Challenger Comics Viewer i can now download the ebook and read it.
In the browser i enter these address `servername:8083/opds/download/[fileno]/cbr/`  from the xml file and download the ebook.

Thanks for youre help.

**Comment by OzzieIsaacs** [comment] 2019-12-01 10:48
Raspi zero is very slow (from my point of view), but I also checked it with my normal linux pc and my linux  server (ubuntu und linux mint). On all of them I could download the file. I think the problem might be more on the android side (do you have some sort of firewall, virusscanner or ... installed on your android phone? I guess you are using android and not windows mobile?)
The result from the test you did above shows that the server is able to provide the book for download.
Last test: Could you please enable the access log in calibre-web (admin section -> basic config -> logfile). Try to re download the file. Afterwards the content of the access.log file should be like the one below: 
```
[2019-12-01 11:37:40,206] 401 GET /opds/cover/396 (192.168.188.40) 5.02ms
[2019-12-01 11:37:40,293] 401 GET /opds/cover/396 (192.168.188.40) 6.76ms
[2019-12-01 11:37:41,203] 401 GET /opds/download/396/epub/ (192.168.188.40) 6.97ms
[2019-12-01 11:37:41,209] 401 GET /opds/cover/396 (192.168.188.40) 3.62ms
[2019-12-01 11:37:41,227] 401 GET /opds/download/396/epub/ (192.168.188.40) 2.86ms
[2019-12-01 11:37:41,707] 200 GET /opds/download/396/epub/ (192.168.188.40) 476.93ms 
```
The numbers (401, 200) are the http code, "401" means access denied, "200" means access allowed, content delivered. So you see the covers are requested 2 times and both requests are denied. The download is requested 3 times, and the last one in 200, and this one takes a certain amount of time (because the file is transferred).
Could you please check the output and post it here. If a message "200" is listed there for the download than the problem is definitely on the client (the android side) and as long as I can't reproduce it, I don't know how to solve it.

**Closed** 2019-12-15 09:05 UTC
Labels: question
