### ISSUE TITLE
pdf.js can't render

### ISSUE THREAD

**Issue by szdefine** [janeczku/calibre-web#1313] opened 2020-04-16 04:11 UTC
**Describe the bug/problem**
can't open pdf in the browser. 

**To Reproduce**
1. Go to 'the detail of book'
2. Click on 'open in the browser'

**Logfile**
PDF.js v2.2.228 (build: d7afb74a)
Message: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

**Expected behavior**
open the pdf file normally in the browser

**Screenshots**
[image](https://user-images.githubusercontent.com/48077232/79410971-483d6980-7fd4-11ea-9cb6-ddd5f6cd758e.png)

**Environment (please complete the following information):**
 - OS: [docker 19.03.8]
 - Python version [ python3.6.9]
 - Calibre-Web version [Linuxserver.io version:- 0.6.6-ls58 Build-date:- 2020-04-13T13:56:31+01:00]:
 - Docker container [ linuxserver/calibre-web]:
 - Browser [chrome 80.0.3987.163 (x64)]

**Additional context**
**safari(13.1 (15609.1.20.111.8)) works fine**

**Comment by OzzieIsaacs** [comment] 2020-04-16 05:36
Duplicate of  #1223. 
I will create a new release end of the month, which will release the fix

**Comment by OzzieIsaacs** [comment] 2020-05-05 18:40
There is a new release out, which addresses this issue

**Closed by OzzieIsaacs** 2020-05-05 18:40 UTC
Labels: duplicate
