### ISSUE TITLE
Guest account  show English language and can not change it.

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#681] opened 2018-10-15 09:16 UTC
Guest account  show English language and can not change it. 
I want change chinaese language   test by lastest version.

admin account   or other account  can change language.

**Comment by Vince4Git** [comment] 2018-11-11 20:47
Thank you for the application. Simple to install and to use :)

I'm using the docker image based on Alpine Linux https://hub.docker.com/r/technosoft2000/calibre-web/ behind Nginx.

I have the same issue than @flashliao. I would like to allow the users to use the calibre-web in another language (French) than the default one (English). I don't know if it is related to the issue #621 which seems related to the login page and not directly to the anonymous mode.

If it is possible, I would like to have a way to rename "Guest" user or do not display its name when the anonymous mode is enabled.

I configured the Guest account with the french language with the admin account but the modification is not taken into account when I use calibre-web with anonymous user. Maybe the issue #621 is not included in the docker image... I don't know how to get the version of calibre-web running in the technosoft2000 docker image. 

Please let me know how I can check if the fix is included in the technosoft2000 docker image. 
Thank you and Best Regards.

**Comment by OzzieIsaacs** [comment] 2018-11-13 19:34
Could you please check which info your browser displays for Accept-Language:
![grafik](https://user-images.githubusercontent.com/6438895/48438033-41794a00-e783-11e8-9583-e4b23711284f.png)
(firefox: extras-> web developer -> web-console, reload page, open first request like shown on the screenshot, chrome should be similar)

**Comment by idalin** [comment] 2018-11-14 06:30
In the case of Simplified Chinese, it's because I chose the locale 'zh_Hans_CN' when I translated it for some reason. But the browse send the Accept-Language header to zh-CN.
I will create a PR to fix this.

**Comment by Vince4Git** [comment] 2018-11-14 18:40
Thank you for you answer @OzzieIsaacs 

Due to an issue with my PC (client side), after an Ubuntu upgrade, I decide to fully re-install the system changing the distribution for Debian. I don't thing that this change explain the difference that I'm observing now. I didn't changed anything in the server nor calibre-web.

Now, Calibre-web displays the page in French. In Firefox, the accepted language is "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3" 
The user is still named "Guest".

I'm no more able to reproduce the problem.
From your answer, I understand that the language of the Guest page is not selected according to the calibre-web configuration of Guest user, but based on the content of the browser request.
It makes sens as we should not take any assumption about the user's language for a guest :).

But maybe we should remove this language parameter from the Guest configuration (like the password has been removed)? Or the language parameter of the Guest user is used for another purpose?

Anyway, think you very much.
I think the issue was in the configuration of my previous Firefox (maybe configured in english...).

Best Regards.

**Closed** 2018-11-17 15:33 UTC
Labels: duplicate

**Comment by hashevskyi** [comment] 2019-02-04 14:05
Browser language is select Ukrainian, but Calibre-web in Guest is - English. 
![screenshot from 2019-02-04 16-03-01](https://user-images.githubusercontent.com/24765590/52213002-84d0e980-2896-11e9-8b53-1c43e2ca2c70.png)

**Comment by OzzieIsaacs** [comment] 2019-02-04 17:58
The language selection is no longer used for the guest user (but it's still displayed in the option). The language is set by the Accept-Header from your browser. If I change mine to "uk" I see ukrainian translated UI:
![grafik](https://user-images.githubusercontent.com/6438895/52226808-3a5b6700-28ae-11e9-847b-852e4efdcde6.png)
It will switch to ukrainian if the header is set accordingly:
![grafik](https://user-images.githubusercontent.com/6438895/52226917-81e1f300-28ae-11e9-8569-7becf3e835d2.png)
Are you using an english firefox?

**Comment by vagra** [comment] 2019-10-16 04:22
me too!

I using Firefox Chinese Version, the Http Get Header is:

Accept-Language: zh-CN,zh-SG;q=0.8,en-GB;q=0.5,en;q=0.3
