### ISSUE TITLE
Books synced over Kobo Sync do not store progress correctly on the device

### ISSUE THREAD

**Issue by flying-sausages** [janeczku/calibre-web#1439] opened 2020-05-27 01:55 UTC
**Describe the bug/problem**
When I read from a book synced from calibre-web, close it, and open it again, I am thrown at the beginning of the chapter. This does not happen when the same files are loaded directly.

**To Reproduce**
1. Load up [ePub](https://transfer.sh/9dUyM/The%20Teleportation%20Accident%20-%20Ned%20Beauman.epub) to calibre-web
2. Set up kobo sync
3. Download books to Kobo device
4. Flip through pages
5. Exit book reader
6. Open same book
7. See yourself at the beginning of the chapter.

**Logfile**
Kobo-side issue with the generated file, N/A

**Expected behavior**
1. Read book
2. Close book
3 Re-open book at the same place it was left on

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
![image](https://user-images.githubusercontent.com/23618693/82968546-79428e00-9fc5-11ea-9645-cced446abe1e.png)
 - Special Hardware: Kobo Forma
 - Browser: FF 68 ESR

**Additional context**
I loaded up the same file onto the reader to check if this was the case with the specific file and it works just right with the normal ePub. I'm wondering if this is something that happens to the file when it is being treated as a "Kobo ePub" as it comes from calibre-web.

**Comment by flying-sausages** [comment] 2020-05-27 02:06
Here is a [link to the file](https://transfer.sh/L0htJ/0aed9e03-f6a7-405d-bfc2-f30a54ec2c7f) that is stored in `/media/KoboReader/.kobo/kepub` which corresponds to the book linked above

**Comment by LordSushiPhoenix** [comment] 2020-05-31 13:07
I'm seeing the same behaviour on a Kobo Clara HD running the latest linuxserver/calibre-web docker on Debian Buster.

**Steps to reproduce:**

1. Add book to Calibre-web and download to device
2. Start reading and stop mid-chapter, closing the book.
3. Open same book, be at first page of chapter. 


![image](https://user-images.githubusercontent.com/19640845/83353056-d9b33180-a31d-11ea-97bf-84ad1ef3518d.png)

**Comment by flying-sausages** [comment] 2020-06-08 17:35
I've found some information on this that might help fix this.

>The kepub format is compatible with ePub leading some to theorize that they could just change the extension to .kepub.epub to make a Kepub from an ePub. However there are some differences. In a kepub, each sentence is wrapped in a span. This is assigned a unique id. The location system uses these ids. If you just change the extension, when you close and reopen a book, you will always be taken to the start of the chapter you were in. And any annotations stored will not be redisplayed in the book. A conversion of ePub to kepub will add the spans to the epubs. There are also some extra divs and CSS that the kepub ereader expects which helps with the way it does the formatting. The DRM system is also different for eBooks using DRM. Kepub also supports ePub 3 formatting which is still not supported for ePub. 

https://wiki.mobileread.com/wiki/Kepub#Kepub_compared_to_ePub

**Comment by flying-sausages** [comment] 2020-06-08 23:31
I just updated to 0.6.8 and enabled the kepubify integration, deleted all my kobo books and re-downloaded them, however I still have the same behaviour. Any suggestions on getting reset in this regard?

**Comment by AntonioDeTeo** [comment] 2020-06-11 13:30
I have noticed that if the downloaded book is originally in kepub format, this problem does not appear.
The saving of highlights and notes does not work either if the book is not a kepub, as I have already mentioned in this issue: #1484 
To force calibre-web to send books in kepub format, there must be no alternative version on epub, because if exists, it will be the downloaded one. 
A quick fix for this could be that the kepub version was the preferred version for the download (or even, if the kepub version doesn't exist but the path to kepubify is set, the conversion could be done on the fly and downloaded)

**Comment by flying-sausages** [comment] 2020-06-11 13:38
@AntonioDeTeo oh thanks, I assumed already that kepubify was used on the fly before the conversion, I suppose that's where my confusion is coming from. This explains a lot, thanks!

I'd still prefer to have a proper kepubified version downloaded over an epub with a changed filename, or not allowing plain epub downloads at all as they are somewhat broken-ish.
It would be awesome to have an option to create kepub versions of epubs on import, or convert the epubs to kepubs on the fly during a kobo sync.

**Comment by AntonioDeTeo** [comment] 2020-06-11 14:06
The only option I see at the moment is to convert the whole library to kepub and delete the original epub files, but this creates another problem, because I share the library with a friend who has a kindle... and if I just leave the kepub files, he could no longer convert them to mobi to send them to his kindle. I would have to convert the epubs to mobi and also to kepub and then delete the original epub... a real mess.
I hope it will be possible to correct the kobo sync and that kepub downloading will be the first option (the conversion to kepub on the fly would be great, but I guess it would involve more work)

**Comment by flying-sausages** [comment] 2020-06-11 17:46
I made a separate issue #1448 for conversions being done on the fly, and other discussion about automated conversion for the purpose of sync.

The objective of this ticket would be to stop offering epubs masqueraded as kepubs over the kobo sync, and only allow true kepubs to be synced, or implement #1448.

**Comment by dmogle** [comment] 2020-08-16 23:54
I've been poking at this recently and as far as I can tell the sync API offers download URLs for epub and kepub formats if they exist. Based on my experience, I assume the ereader just grabs the first URL available and downloads from there. It seems like the best fix would be not to offer epub URLs if a kepub file exists.

**Comment by flying-sausages** [comment] 2020-08-26 04:37
For anyone who finds this in the future, here's a little script to help you get all your books into kepub

https://gist.github.com/flying-sausages/2684b07e326a17f7245ca3f1812376ef

**Comment by AntonioDeTeo** [comment] 2020-08-26 07:31
> For anyone who finds this in the future, here's a little script to help you get all your books into kepub
> 
> https://gist.github.com/flying-sausages/2684b07e326a17f7245ca3f1812376ef

Hello, this script adds a kepub version of the books, but i guess kobo sync will download the epub version anyway and the problem will persist, right?

**Comment by flying-sausages** [comment] 2020-08-26 21:05
> Hello, this script adds a kepub version of the books, but i guess kobo sync will download the epub version anyway and the problem will persist, right? 

In the current form, yes. If the PR #1439 gets merged into master (or if you merge it into your fork) it should do what it should.

**Comment by AntonioDeTeo** [comment] 2020-08-27 13:11
> > Hello, this script adds a kepub version of the books, but i guess kobo sync will download the epub version anyway and the problem will persist, right?
> 
> In the current form, yes. If this [PR](https://github.com/dmogle/calibre-web/commit/d951ee4b83a9e67c3296f2ef0a3dcb6f7570f0f0) gets merged into master (or if you merge it into your fork) it should do what it should.

That's great! thanks.

**Closed** 2021-05-28 17:21 UTC

**Comment by jeff47** [comment] 2022-01-05 01:41
Hmm, I am seeing this behavior occurring again.  My Kobo ePubs all jump back to the beginning of the chapter when I close them.  I convert my books to kepub using kepubify in Calibre, but maintain the epub version as well.

The behavior seems to have started recently.

**Comment by mrboatsman** [comment] 2022-01-13 18:45
I got this behaivor when i added 
`/usr/bin/kepubify`   in  Basic Configuration `Path to Kepubify E-Book Converter`

removed the string in the configuration and re-downloaded the books and now it keeps the page,  instead of just the chapter. 

One other thing I had issues with was that annotaions did not got saved when `Path to Kepubify E-Book Converter` was set to `/usr/bin/kepubify`
