### ISSUE TITLE
Stuck in a login loop

### ISSUE THREAD

**Issue by Serneum** [janeczku/calibre-web#2721] opened 2023-03-16 20:21 UTC
**Describe the bug/problem**
When trying to do just about anything in the Calibre-Web interface, the user is constantly logged out, requiring another login. This prevents me from creating new users, editing users, or just using Calibre-Web in general.

https://user-images.githubusercontent.com/1091716/225745643-37aafa9c-68ba-4942-af9a-10aa625e9b41.mp4

**To Reproduce**
1. Log in as the admin user
2. Go to the Admin view
3. Try to add a new user
4. Submit the user

It's hard to say which of those steps will trigger a need to log in, but for me the issue occurs at each individual login

**Logfile**
[calibre-web.log](https://github.com/janeczku/calibre-web/files/10995516/calibre-web.log)

The log file has not received any new lines in over a week. When I try to change the log level in the UI, it does not seem to save

EDIT:
I downloaded a log file via the UI which as additional lines:
[calibre-web (1).log](https://github.com/janeczku/calibre-web/files/10995581/calibre-web.1.log)

**Expected behavior**
A user should only need to log in once and should not be logged out while navigating the application.

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 22.04.1 LTS)
 - Python version: Whatever is in the LinuxServer Docker image
 - Calibre-Web version: [0.6.19](https://github.com/janeczku/calibre-web/releases/tag/0.6.19)
 - Docker container: LinuxServer
 - Browser: Safari 16.2 (18614.3.7.1.5), Brave 1.47.186 Chromium: 109.0.5414.119

**Additional context**
I am accessing via a reverse proxy:
```
<my domain> {
  import cloudflare-tls
  reverse_proxy <docker host>:8083 { 
    header_up X-Scheme https
  }
}
```

**Comment by OzzieIsaacs** [comment] 2023-03-25 15:58
I think this is a duplicate of this one: https://github.com/janeczku/calibre-web/issues/2422

**Comment by Serneum** [comment] 2023-03-25 16:19
That does seem to be very similar at a minimum. I'll give the solution around the custom unit file a try and close this issue out

**Closed** 2023-03-25 16:20 UTC
Labels: duplicate

**Comment by Plaidstallion** [comment] 2026-08-24 23:20
Not sure if this applies to your setup since I don't see mention of what's in front of Calibre-Web, but wanted to flag a specific cause that produces this exact symptom (login loop while doing normal things in the UI), in case it's useful to check.

If you're running Calibre-Web behind a reverse proxy (Traefik, nginx, etc.) and/or a CDN like Cloudflare, this is worth ruling out: Flask-Login's session protection compares the client IP on each request against the IP recorded when the session was created. If your proxy isn't configured to trust/forward the real client IP (e.g. missing `forwardedHeaders.trustedIPs` on a Traefik entrypoint, or the equivalent for your proxy), Calibre-Web can end up seeing a different apparent "client IP" on different requests within the same session, especially on page loads that fire many parallel requests (Calibre-Web's cover-image grid does this constantly). Each mismatch triggers this:

```
set-cookie: remember_token=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0
set-cookie: session=... (fresh)
```

which forces an immediate re-login. Given your report says it can happen on almost any action and the log file goes quiet for weeks (suggesting the app itself isn't erroring), this proxy-IP mismatch is a plausible fit.

Worth checking your proxy's access log or Calibre-Web's own `access.log` to see whether the client IP stays consistent across a single browsing session. If it's bouncing around request to request, that's the smoking gun, and the fix is making sure your proxy trusts and forwards the real client IP on whichever entrypoint handles your actual traffic.
